export default {
  // copulas (incomplete)
  es: ['Copula', 'PresentTense'],
  est: ['Copula', 'PresentTense'],
  suis: ['Copula', 'PresentTense'],
  sommes: ['Copula', 'PresentTense'],
  etes: ['Copula', 'PresentTense'],
  sont: ['Copula', 'PresentTense'],

  ete: ['Copula', 'PastTense'],
  etais: ['Copula', 'PastTense'],
  etions: ['Copula', 'PastTense'],

  serons: ['Copula', 'FutureTense'],
  seront: ['Copula', 'FutureTense'],
  serai: ['Copula', 'FutureTense'],

  cent: ['Multiple', 'Cardinal'],
  mille: ['Multiple', 'Cardinal'],
  million: ['Multiple', 'Cardinal'],
  milliard: ['Multiple', 'Cardinal'],
  quadrillion: ['Multiple', 'Cardinal'],
  centième: ['Multiple', 'Ordinal'],
  millième: ['Multiple', 'Ordinal'],
  millionième: ['Multiple', 'Ordinal'],
  milliardième: ['Multiple', 'Ordinal'],
  billionième: ['Multiple', 'Ordinal'],
  trillionième: ['Multiple', 'Ordinal'],
  // plural numbers
  septs: ['TextValue', 'Cardinal'],

  cents: ['Multiple', 'Cardinal'],
  milles: ['Multiple', 'Cardinal'],
  millions: ['Multiple', 'Cardinal'],
  milliards: ['Multiple', 'Cardinal'],

  sommes: ['Copula', 'PresentTense'],
  êtes: ['Copula', 'PresentTense'],
  sont: ['Copula', 'PresentTense'],
  étions: ['Copula', 'PresentTense'],
  serez: ['Copula', 'PresentTense'],
  seront: ['Copula', 'PresentTense'],
  été: ['Copula'],
  fus: ['Copula', 'PastTense'],
  fut: ['Copula', 'PastTense'],
  fûmes: ['Copula', 'PastTense'],
  fûtes: ['Copula', 'PastTense'],
  furent: ['Copula', 'PastTense'],
  fusse: ['Copula', 'PastTense'],
  fusses: ['Copula', 'PastTense'],
  fût: ['Copula', 'PastTense'],
  fussions: ['Copula', 'PastTense'],
  fussiez: ['Copula', 'PastTense'],
  fussent: ['Copula', 'PastTense'],
  serais: ['Copula', 'PresentTense'],
  serais: ['Copula', 'PresentTense'],
  serait: ['Copula', 'PresentTense'],
  serions: ['Copula', 'PresentTense'],
  seriez: ['Copula', 'PresentTense'],
  seraient: ['Copula', 'PresentTense'],
  sois: ['Copula', 'PresentTense'],
  soyons: ['Copula', 'PresentTense'],
  soyez: ['Copula', 'PresentTense'],
  être: ['Copula', 'PresentTense'],



}