import test from 'tape'
import nlp from '../_lib.js'
let here = '[past-tense] '
nlp.verbose(false)

test('vb-conjugate:', function (t) {
  let arr = [
    ['accélérer', 'accéléré'],
    ['acheter', 'acheté'],
    ['agir', 'agi'],
    ['aider', 'aidé'],
    ['aimer', 'aimé'],
    ['ajouter', 'ajouté'],
    ['aller', 'allé'],
    ['annoncer', 'annoncé'],
    ['apprendre', 'appris'],
    ['arrêter', 'arrêté'],
    ['arriver', 'arrivé'],
    ['assister', 'assisté'],
    ['attendre', 'attendu'],
    ['attraper', 'attrapé'],
    ['avertir', 'averti'],
    ['avoir', 'eu'],
    ['battre', 'battu'],
    ['boire', 'bu'],
    ['casser', 'cassé'],
    ['changer', 'changé'],
    ['chauffer', 'chauffé'],
    ['chercher', 'cherché'],
    ['choisir', 'choisi'],
    ['comprendre', 'compris'],
    ['conduire', 'conduit'],
    ['connaître', 'connu'],
    ['construire', 'construit'],
    ['continuer', 'continué'],
    ['coudre', 'cousu'],
    ['couler', 'coulé'],
    ['couper', 'coupé'],
    ['courir', 'couru'],
    ['couvrir', 'couvert'],
    ['craindre', 'craint'],
    ['créer', 'créé'],
    ['crier', 'crié'],
    ['croire', 'cru'],
    ['danser', 'dansé'],
    ['décider', 'décidé'],
    ['découvrir', 'découvert'],
    ['décrire', 'décrit'],
    ['défendre', 'défendu'],
    ['demander', 'demandé'],
    ['dépenser', 'dépensé'],
    ['déplacer', 'déplacé'],
    ['développer', 'développé'],
    ['devoir', 'dû'],
    ['dire', 'dit'],
    ['discuter', 'discuté'],
    ['donner', 'donné'],
    ['dormir', 'dormi'],
    ['écarter', 'écarté'],
    ['échanger', 'échangé'],
    ['échouer', 'échoué'],
    ['écouter', 'écouté'],
    ['ecouter', 'écouté'],
    ['écrire', 'écrit'],
    ['effacer', 'effacé'],
    ['élever', 'élevé'],
    ['embaucher', 'embauché'],
    ['employer', 'employé'],
    ['entendre', 'entendu'],
    ['entrer', 'entré'],
    ['envoyer', 'envoyé'],
    ['éprouver', 'éprouvé'],
    ['essayer', 'essayé'],
    ['éteindre', 'éteint'],
    ['étendre', 'étendu'],
    ['étudier', 'étudié'],
    ['éviter', 'évité'],
    ['expliquer', 'expliqué'],
    ['explorer', 'exploré'],
    ['faire', 'fait'],
    ['fermer', 'fermé '],
    ['fermer', 'fermé'],
    ['finir', 'fini'],
    ['fixer', 'fixé'],
    ['fluctuer', 'fluctué'],
    ['fouiller', 'fouillé'],
    // ['frais', 'fris'],
    ['frapper', 'frappé'],
    ['gagner', 'gagné'],
    ['garder', 'gardé'],
    ['gérer', 'géré'],
    ['gripper', 'grippé'],
    ['guérir', 'guéri'],
    ['habiter', 'habité'],
    ['indiquer', 'indiqué'],
    ['installer', 'installé'],
    ['jeter', 'jeté'],
    ['jouer', 'joué'],
    ['kisser', 'kissé'],
    ['lancer', 'lancé'],
    ['lire', 'lu'],
    ['manger', 'mangé'],
    ['marcher', 'marché'],
    ['mener', 'mené'],
    ['mettre', 'mis'],
    ['monter', 'monté'],
    ['montrer', 'montré'],
    ['mourir', 'mort'],
    ['naître', 'né'],
    ['nettoyer', 'nettoyé'],
    ['offrir', 'offert'],
    ['ordonner', 'ordonné'],
    ['organiser', 'organisé'],
    ['ouvrir', 'ouvert'],
    ['pardonner', 'pardonné'],
    ['parler', 'parlé'],
    ['partir', 'parti'],
    ['passer', 'passé'],
    ['payer', 'payé'],
    ['peindre', 'peint'],
    ['penser', 'pensé'],
    ['plaire', 'plu'],
    ['pleurer', 'pleuré'],
    ['plier', 'plié'],
    ['porter', 'porté'],
    ['poser', 'posé'],
    ['posséder', 'possédé'],
    ['pouvoir', 'pu'],
    ['prendre', 'pris'],
    ['promettre', 'promis'],
    ['proposer', 'proposé'],
    ['protéger', 'protégé'],
    ['raconter', 'raconté'],
    ['ralentir', 'ralenti'],
    ['ramasser', 'ramassé'],
    ['réaliser', 'réalisé'],
    ['recevoir', 'reçu'],
    ['réfléchir', 'réfléchi'],
    ['refuser', 'refusé'],
    ['regarder', 'regardé'],
    ['rejeter', 'rejeté'],
    ['remplir', 'rempli'],
    ['rendre', 'rendu'],
    ['répondre', 'répondu'],
    ['reposer', 'reposé'],
    ['résister', 'résisté'],
    ['résoudre', 'résolu'],
    ['respirer', 'respiré'],
    ['rester', 'resté'],
    ['retenir', 'retenu'],
    ['retourner', 'retourné'],
    ['réunir', 'réuni'],
    ['réussir', 'réussi'],
    ['revenir', 'revenu'],
    ['rêver', 'rêvé'],
    ['rire', 'ri'],
    ['rouler', 'roulé'],
    ['sauter', 'sauté'],
    ['savoir', 'sû'],
    ['sentir', 'senti'],
    ['servir', 'servi'],
    ['signer', 'signé'],
    ['sonner', 'sonné'],
    ['sortir', 'sorti'],
    ['souffrir', 'souffert'],
    ['souvenir', 'souvenu'],
    ['suggérer', 'suggéré'],
    ['supporter', 'supporté'],
    ['surveiller', 'surveillé'],
    ['téléphoner', 'téléphoné'],
    ['tenter', 'tenté'],
    ['tomber', 'tombé'],
    ['toutir', 'toulu'],
    ['traiter', 'traité'],
    ['travailler', 'travaillé'],
    ['troubler', 'troublé'],
    ['trouver', 'trouvé'],
    ['tuer', 'tué'],
    ['utiliser', 'utilisé'],
    ['vendre', 'vendu'],
    ['venir', 'venu'],
    ['visiter', 'visité'],
    ['vivre', 'vécu'],
    ['voir', 'vu'],
    ['voler', 'voli'],
    ['vouloir', 'voulu'],
  ]
  arr.forEach(a => {
    let [inf, past] = a
    let doc = nlp(inf)
    t.ok(doc.has('#Infinitive'), inf, here)
    // t.ok(nlp(past).has('#Verb'), past, here)
    doc.verbs().toPastTense()
    t.equal(doc.text(), past, here + ' ' + past)
  })
  t.end()
})