// generated in ./lib/models
export default {
  "noun": {
    "plural": {
      "fwd": "s:¦oeurs:œurs,œur¦ses:x¦2ux:vail,ial,éal¦2x:au¦2es:is¦3es:tit,nti,usé¦4es:igné¦5es:scent,ustin",
      "both": "5ses:celeur,ordeur,yageur,ucheur,rcheur¦5ères:apetier¦5rices:nventeur,lisateur,édacteur,ommateur¦5es:étenu,ipant,rrent,diant¦5e:ésent¦5ux:égétal¦5nes:toyen,ncien¦4es:féré,dian,rmal,etch,eant,idat¦4rices:oniteur,nnateur,ucateur¦4x:llou,enou¦4nes:bien¦4ses:aneur¦4ux:pital,nimal¦3ux:oral,eval,otal,éral¦3es:han,ômé,tué,gué¦3rices:éateur¦3x:hou,jeu,ieu,veu¦2es:yé¦2ux:nal,cal,pal¦oeuvres:œuvre¦oeufs:œuf¦oeuds:œud¦oeux:œu",
      "rev": "1:és,rs,ts,ns,ls,is,os,ps,as,us,ms,bs,cs,ks,gs,hs,ys,ws¦2:ies,mes,des,pes,ges,bes,ves,ifs,xes,rds,efs,nds,ees,eds,ïds,yes,ids,afs,fes,oux,rfs,ofs¦3:tres,ètes,ones,nées,ines,utes,rtes,sses,nces,ires,ures,ases,ites,vues,oles,ônes,bles,aces,ques,cées,eaux,êtes,ôles,ules,nses,înes,èles,lles,rces,ltes,bres,èces,oses,unes,cles,fres,stes,ttes,yses,ises,gues,cres,iles,dres,otes,tues,sées,lées,ènes,hées,dées,ares,éennes,phes,thes,xtes,ûres,gnes,ores,èses,yaux,tches,rres,pres,rses,uaux,nres,ôtes,ples,rues,eues,rnes,ytes,uces,gles,sues,yles,éates,ctes,ênes,îtes,dues,tées,mnes,oues,oces,bées,vées,rles,sces,ptes,cues,lnes,âles,pées,ûtes¦4:fices,ipses,hères,ivres,rches,uantes,uches,nnelles,nantes,onnes,oches,vices,éales,ffles,dentes,nrées,ngées,tères,nches,nanes,trées,intes,aches,hates,iches,ganes,gères,mates,fères,dantes,èvres,oates,rales,nates,auses,tates,tices,enties,sales,ontes,cales,caines,canes,âches,rmées,rates,tales,ouses,ciennes,pices,annes,lices,arées,sanes,banes,ranes,mères,rantes,tanes,èches,dales,ûches,pères,pales,vrées,fanes,êches,yères,quées,manes,muses,rères,coises¦5:tennes,mières,rières,ntantes,lientes,ouanes,ngales,auvres,scères,venues,liales,vières,udices,ulantes,santes,nières,égates,rcices,jointes,avanes,onaises,oirées,éduses,sières,ndices,signées,pentes,meuses,teuses,onales,guanes,ginales,xcuses,imales,ventes¦1œur:hoeurs¦2eur:ctrices,ltrices,utrices¦2l:taux¦2er:cières¦3il:avaux¦3r:deuses,ueuses,seuses¦3l:ciaux,déaux,ivaux¦3eur:ratrices,matrices¦3f:ptives¦4r:lleuses,ileuses¦4x:ineuses,gieuses¦5eur:dicatrices",
      "ex": "yeux:œil¦oeufs:œuf¦oeuvre:œuvre¦oeillets:œillet¦oeilletons:œilleton¦oestrogènes:œstrogène¦2es:un¦11es:constituant,intervenant¦10nes:amérindien,australien¦13les:professionnel¦10es:enseignant,délinquant,adolescent¦7rices:producteur¦8rices:agriculteur,informateur¦8es:résident,ambulant,conjoint,marginal,augustin¦8ses:demandeur,cueilleur¦12es:représentant,contrevenant¦9rices:distributeur¦6es:client,garant,accusé¦9es:immigrant,répondant,américain,apprenant,plaignant,postulant,survivant¦6nes:coréen¦3x:jeu,feu,pou,eau¦11rices:administrateur¦5es:match,petit¦4ux:métal,rival¦10ères:conférencier¦4es:aîné¦5ses:joueur,fileur¦2ux:mal¦7es:lauréat,migrant,mauvais¦7nes:gardien¦9nes:praticien¦10rices:interlocuteur,revendicateur¦5ves:captif¦5x:bijou,hibou,fléau¦6ses:tisseur,pondeur¦3s:rue,vue,île,ale¦7s:attente,matière,entente,pieuvre,moyenne,filière,matrice,retenue,sulfate,rizière,litière¦9s:nébuleuse,frontière,constante,chaudière,cicatrice,sénatrice,chargeuse,érablière,cimetière,gouttière¦5s:fente,vente,purée,pente,durée,bière,tente,tenue,rente,tante,bouée¦6s:plante,finale,misère,fiente,agente¦4s:date,pâte,mère,cale,père,pale,fane,buse,veuf,cane,vice,ruse¦1oeurs:mœurs,cœur,sœur¦10s:obsidienne,imprimante,mésentente,bleuetière¦11s:visionneuse¦8s:variante,éolienne,descente¦11x:biomatériau¦2s:if¦12s:charpentière¦13s:photocopieuse"
    }
  },
  "adjective": {
    "female": {
      "fwd": "1:e¦lle:au¦ue:û¦se:x¦1e:d¦1que:ïc¦1ue:g¦2se:as¦2e:un,ir,ur,ul,ar,ol¦2te:oi¦3e:ril",
      "both": "1:m,p¦2:pa,or,uo¦3:cho¦4:colo¦5te:illot,avori¦5ne:aysan¦5e:ormon,onfus¦5se:dalou¦4e:atil,btil,idon¦4te:olet,pret,âlot,llet,eret,luet,quet,ulot,elet¦4sse:ître¦4le:ntil¦4ète:omplet¦3te:jet,net,det¦3ète:eplet¦3que:blic,rec¦3e:cis,pon,mis,dou,uis,ris,vil,leu¦3le:eil¦3he:anc¦3gne:énin¦2e:cu,çu,ûr,yr,pu,vu,fu,bu,mu,hu,su,du,an,nu,al,in,ru,lu,tu¦2se:os¦2sse:aux,ta¦2ète:suet,cret¦2ne:on,en¦2ë:gu¦2le:el¦1que:rc¦1ète:iet¦1e:ï,i,t,é¦1îche:ais¦1ève:ref¦ère:er¦ve:f",
      "rev": "1:o,tte,c¦2:me,nde,rde,ge,ze,ude,be,xe,pe,oue¦3:ble,lte,gre,ire,oce,gle,rre,rune,bre,mune,tre,nse,ôle,ace,nole,rne,ade,èle,ide,oide,rasse,tune,vre,ongue,oule,yare,nce,gole,cure,âle,phe,ice,olote,ose,eule,ple,dre¦4:iste,thée,bile,cile,ïste,lite,aste,gile,uture,sque,nête,paire,èque,aune,uste,âche,isse,uche,cule,este,ogue,oche,oque,vère,ague,irile¦5:surde,tique,mique,sique,fique,nique,vique,lasse,crate,ingue,xique,pique,ivole,hique,stile,ature,utile,énile,gique,dique,rique,ncère,uille¦ec:èche¦1x:uce¦1u:olle¦2c:aïque¦2n:ligne¦2au:velle,celle,gelle¦2x:euse",
      "ex": "3:bio¦4:chic,apte,hâte,rare,sale¦5:digne,fonde,jeune,riche,utile¦6:chauve,propre¦7:fertile,stérile¦8:chouette,commande,continue,enceinte,héroïque,patriote,prospère¦9:disparate,idyllique¦10:alcoolique,initiative,symbolique¦4te:blet,muet¦3ce:doux¦4e:flou,cool,laid,noir,pair¦2lle:fou,beau¦2e:lu,nu,tu,vu¦4gne:malin¦3e:mou,vil,dur,nul,pur,sur¦3te:net,sot,coi¦6te:rigolo¦1èche:sec¦7te:simplet¦5e:tabou,clair,impur¦3se:bas¦1ue:dû¦5se:jaloux¦6e:puéril"
    },
    "plural": {
      "fwd": "1:s,x¦s:¦us:û¦2x:au",
      "both": "5ux:énatal¦4ux:gétal,macal,arcal,rutal¦3ux:ocal,otal,ival,stal,éval,etal,scal,ital,ntal,ccal,ical¦2ux:bal,çal,xal,yal,éal,dal,pal,gal,sal,ial,mal,ral,nal",
      "rev": "3:eaux,oux,ras,ros,eux¦4:pris,quis,umis¦5:onfus¦:s¦2l:caux,haux",
      "ex": "3:bas¦4:faux,gris¦5:frais¦6:précis¦4ux:ducal,fécal¦2ux:mal¦8ux:triomphal¦1us:dû"
    },
    "femalePlural": {
      "fwd": "lles:au¦ues:û¦ses:x¦1s:e¦1es:d¦1ques:ïc¦1ues:g¦2ses:as¦2es:un,ir,ur,ul,ar,ol¦2tes:oi¦3es:ril",
      "both": "5tes:illot,avori¦5nes:aysan¦5es:ormon,onfus¦5ses:dalou¦4es:atil,btil,idon¦4tes:olet,pret,âlot,llet,eret,luet,quet,ulot,elet¦4sses:ître¦4les:ntil¦4s:colo¦4ètes:omplet¦3tes:jet,net,det¦3ètes:eplet¦3ques:blic,rec¦3es:cis,pon,mis,dou,uis,ris,vil,leu¦3les:eil¦3s:cho¦3hes:anc¦3gnes:énin¦2es:cu,çu,ûr,yr,pu,vu,fu,bu,mu,hu,su,du,an,nu,al,in,ru,lu,tu¦2s:pa,or,uo¦2ses:os¦2sses:aux,ta¦2ètes:suet,cret¦2nes:on,en¦2ës:gu¦2les:el¦1ques:rc¦1ètes:iet¦1es:ï,i,t,é¦1îches:ais¦1s:m,p¦1èves:ref¦ères:er¦ves:f",
      "rev": "1:os,ttes,cs¦2:mes,ndes,rdes,ges,zes,udes,bes,xes,pes,oues¦3:bles,ltes,gres,ires,oces,gles,rres,runes,bres,munes,tres,nses,ôles,aces,noles,rnes,ades,èles,ides,oides,rasses,tunes,vres,ongues,oules,yares,nces,goles,cures,âles,phes,ices,olotes,oses,eules,ples,dres¦4:istes,thées,biles,ciles,ïstes,lites,astes,giles,utures,sques,nêtes,paires,èques,aunes,ustes,âches,isses,uches,cules,estes,ogues,oches,oques,vères,agues,iriles¦5:surdes,tiques,miques,siques,fiques,niques,viques,lasses,crates,ingues,xiques,piques,ivoles,hiques,stiles,atures,utiles,éniles,giques,diques,riques,ncères,uilles¦ec:èches¦1x:uces¦1u:olles¦2c:aïques¦2n:lignes¦2au:velles,celles,gelles¦2x:euses",
      "ex": "3s:bio¦4tes:blet,muet¦4s:chic,apte,hâte,rare,sale¦3ces:doux¦4es:flou,cool,laid,noir,pair¦2lles:fou,beau¦2es:lu,nu,tu,vu¦4gnes:malin¦3es:mou,vil,dur,nul,pur,sur¦3tes:net,sot,coi¦6tes:rigolo¦1èches:sec¦7tes:simplet¦5es:tabou,clair,impur¦10s:alcoolique,initiative,symbolique¦3ses:bas¦6s:chauve,propre¦8s:chouette,commande,continue,enceinte,héroïque,patriote,prospère¦5s:digne,fonde,jeune,riche,utile¦9s:disparate,idyllique¦1ues:dû¦7s:fertile,stérile¦5ses:jaloux¦6es:puéril"
    }
  },
  "futureTense": {
    "je": {
      "fwd": "errai:érir¦ai:e¦épartirai:epartir¦îtrai:itre¦1udrai:aloir¦1drai:uloir¦2rai:erir¦3ai:dir,uir¦3lerai:peler¦4ai:ller,tter",
      "both": "5ai:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4ai:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4rai:mouvoir¦3ai:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3lerai:celer,veler¦3rai:cevoir¦2udrai:faillir¦2êterai:rreter¦2èlerai:rteler¦2èterai:aleter,ureter¦2trai:âtre¦2ai:ïr¦2rai:urir¦2errai:nvoyer¦1errai:hoir¦1égerai:ieger¦1èlerai:deler¦1erai:faire¦1ènerai:mener,sener¦1urai:avoir¦1ierai:uyer,oyer¦1èterai:heter¦échirai:echir¦éerai:eer¦écierai:ecier¦èverai:ever¦iendrai:enir¦èserai:eser¦ècerai:ecer",
      "rev": "3:lirai,yerai¦4:ogerai,ndirai,userai,anerai,hierai,enerai,rlerai,ouirai,guirai,dierai¦5:otterai,ocierai,urdirai,enierai,atterai,allerai,utterai,icierai¦eler:èlerai¦evrer:èvrerai¦ener:ènerai¦2oir:uvrai,evrai,everrai¦2loir:vaudrai¦2e:orai,prai,crai¦2itre:raîtrai¦3e:atrai,lurai,firai,utrai,airai,ivrai,rdrai¦3er:tellerai,letterai¦3loir:voudrai¦4ir:eillerai¦4e:oîtrai,udirai,indrai,andrai,roirai,ettrai,ondrai,duirai,ruirai,crirai,attrai¦4er:ppellerai¦5e:oncirai,naîtrai,soudrai,rendrai,cendrai,pendrai,tendrai",
      "ex": "irai:aller¦serai:être¦1èlerai:geler,peler¦3terai:jeter¦1èvrerai:sevrer¦1ierai:oyer¦4erai:montrer¦1urai:avoir¦8ai:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4rai:mouvoir¦6ai:partir,renier,hurler,mollir,verdir,sourire¦3rrai:pouvoir¦6erai:cueillir¦3rai:devoir¦9ai:assaillir¦1errai:voir¦1erai:faire¦7ai:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5lerai:atteler,bateler¦4ai:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5ai:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6terai:pelleter¦13ai:photographier¦3errai:revoir¦5terai:voleter¦10ai:interroger¦1ènerai:mener¦2udrai:faillir,valoir¦2errai:quérir¦3drai:vouloir¦3ai:dire,lire,rire,uire¦1épartirai:repartir¦11ai:interpeller¦6rai:acquerir"
    },
    "tu": {
      "fwd": "erras:érir¦as:e¦épartiras:epartir¦îtras:itre¦1udras:aloir¦1dras:uloir¦2ras:erir¦3as:dir,uir¦3leras:peler¦4as:ller,tter",
      "both": "5as:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4as:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ras:mouvoir¦3as:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3leras:celer,veler¦3ras:cevoir¦2udras:faillir¦2êteras:rreter¦2èleras:rteler¦2èteras:aleter,ureter¦2tras:âtre¦2as:ïr¦2ras:urir¦2erras:nvoyer¦1erras:hoir¦1égeras:ieger¦1èleras:deler¦1eras:faire¦1èneras:mener,sener¦1uras:avoir¦1ieras:uyer,oyer¦1èteras:heter¦échiras:echir¦éeras:eer¦écieras:ecier¦èveras:ever¦iendras:enir¦èseras:eser¦èceras:ecer",
      "rev": "3:liras,yeras¦4:ogeras,ndiras,useras,aneras,hieras,eneras,rleras,ouiras,guiras,dieras¦5:otteras,ocieras,urdiras,enieras,atteras,alleras,utteras,icieras¦eler:èleras¦evrer:èvreras¦ener:èneras¦2oir:uvras,evras,everras¦2loir:vaudras¦2e:oras,pras,cras¦2itre:raîtras¦3e:atras,luras,firas,utras,airas,ivras,rdras¦3er:telleras,letteras¦3loir:voudras¦4ir:eilleras¦4e:oîtras,udiras,indras,andras,roiras,ettras,ondras,duiras,ruiras,criras,attras¦4er:ppelleras¦5e:onciras,naîtras,soudras,rendras,cendras,pendras,tendras",
      "ex": "iras:aller¦seras:être¦1èleras:geler,peler¦3teras:jeter¦1èvreras:sevrer¦1ieras:oyer¦4eras:montrer¦1uras:avoir¦8as:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4ras:mouvoir¦6as:partir,renier,hurler,mollir,verdir,sourire¦3rras:pouvoir¦6eras:cueillir¦3ras:devoir¦9as:assaillir¦1erras:voir¦1eras:faire¦7as:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5leras:atteler,bateler¦4as:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5as:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6teras:pelleter¦13as:photographier¦3erras:revoir¦5teras:voleter¦10as:interroger¦1èneras:mener¦2udras:faillir,valoir¦2erras:quérir¦3dras:vouloir¦3as:dire,lire,rire,uire¦1épartiras:repartir¦11as:interpeller¦6ras:acquerir"
    },
    "il": {
      "fwd": "erra:érir¦a:e¦épartira:epartir¦îtra:itre¦1udra:aloir¦1dra:uloir¦2ra:erir¦3a:dir,uir¦3lera:peler¦4a:ller,tter",
      "both": "5a:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4a:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ra:mouvoir¦3a:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3lera:celer,veler¦3ra:cevoir¦2udra:faillir¦2êtera:rreter¦2èlera:rteler¦2ètera:aleter,ureter¦2tra:âtre¦2a:ïr¦2ra:urir¦2erra:nvoyer¦1erra:hoir¦1égera:ieger¦1èlera:deler¦1era:faire¦1ènera:mener,sener¦1ura:avoir¦1iera:uyer,oyer¦1ètera:heter¦échira:echir¦éera:eer¦éciera:ecier¦èvera:ever¦iendra:enir¦èsera:eser¦ècera:ecer",
      "rev": "3:lira,yera¦4:ogera,ndira,usera,anera,hiera,enera,rlera,ouira,guira,diera¦5:ottera,ociera,urdira,eniera,attera,allera,uttera,iciera¦eler:èlera¦evrer:èvrera¦ener:ènera¦2oir:uvra,evra,everra¦2loir:vaudra¦2e:ora,pra,cra¦2itre:raîtra¦3e:atra,lura,fira,utra,aira,ivra,rdra¦3er:tellera,lettera¦3loir:voudra¦4ir:eillera¦4e:oîtra,udira,indra,andra,roira,ettra,ondra,duira,ruira,crira,attra¦4er:ppellera¦5e:oncira,naîtra,soudra,rendra,cendra,pendra,tendra",
      "ex": "ira:aller¦sera:être¦1èlera:geler,peler¦3tera:jeter¦1èvrera:sevrer¦1iera:oyer¦4era:montrer¦1ura:avoir¦8a:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4ra:mouvoir¦6a:partir,renier,hurler,mollir,verdir,sourire¦3rra:pouvoir¦6era:cueillir¦3ra:devoir¦9a:assaillir¦1erra:voir¦1era:faire¦7a:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5lera:atteler,bateler¦4a:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5a:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6tera:pelleter¦13a:photographier¦3erra:revoir¦5tera:voleter¦10a:interroger¦1ènera:mener¦2udra:faillir,valoir¦2erra:quérir¦3dra:vouloir¦3a:dire,lire,rire,uire¦1épartira:repartir¦11a:interpeller¦6ra:acquerir"
    },
    "nous": {
      "fwd": "errons:érir¦ons:e¦épartirons:epartir¦îtrons:itre¦1drons:uloir¦2rons:erir¦3ons:dir,uir¦3lerons:peler¦4ons:ller,tter",
      "both": "5ons:ucier,ffrir,urrir,rtrir,ncier,auger,itier,urler,ifler,arnir,mater,eurir,ernir,nfler,arler,nchir,arrir,ertir,errir,arner,rvoir,ortir,évoir,erner,téger¦5terons:elleter¦4ons:vrir,iger,iver,dier,grir,acer,unir,stir,ager,ayer,aner,rier,oler,iter,nier,hier,aver,nser,fier,lier,pter,oter,gter,oser,cter,rcer,aser,nnir,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4rons:mouvoir¦3ons:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3lerons:celer,veler¦3rons:cevoir¦2êterons:rreter¦2èlerons:rteler¦2èterons:aleter,ureter¦2trons:âtre¦2ons:ïr¦2rons:urir¦2errons:nvoyer¦1errons:hoir¦1égerons:ieger¦1èlerons:deler¦1erons:faire¦1ènerons:mener,sener¦1urons:avoir¦1udrons:aloir¦1ierons:uyer,oyer¦1èterons:heter¦échirons:echir¦éerons:eer¦écierons:ecier¦èverons:ever¦iendrons:enir¦èserons:eser¦ècerons:ecer",
      "rev": "3:nirons,yerons¦4:ndirons,sierons,tierons,rgerons,rnerons,plerons,enerons,lserons,ouirons,guirons,aterons,rverons¦5:otterons,ocierons,urdirons,atterons,noverons,utterons,icierons¦eler:èlerons¦evrer:èvrerons¦ener:ènerons¦2oir:uvrons,evrons,everrons¦2e:orons,prons,crons¦2itre:raîtrons¦3e:atrons,lurons,firons,utrons,airons,ivrons,rdrons¦3er:tellerons,letterons¦3loir:voudrons¦4ir:eillerons¦4e:oîtrons,udirons,indrons,androns,roirons,ettrons,duirons,ondrons,crirons,attrons¦4er:ppellerons¦5e:oncirons,naîtrons,soudrons,rendrons,cendrons,pendrons,truirons,tendrons",
      "ex": "irons:aller¦serons:être¦1èlerons:geler,peler¦3terons:jeter¦1èvrerons:sevrer¦1ierons:oyer¦4erons:montrer¦1urons:avoir¦8ons:départir,associer,diverger,impulser,observer,officier,babiller,emballer,fouetter,habiller,interdire¦4rons:mouvoir¦6ons:partir,forger,verdir,sourire¦3rrons:pouvoir¦6erons:cueillir¦3rons:devoir¦1errons:voir¦1erons:faire¦5lerons:atteler,bateler¦9ons:autopsier,balbutier,retourner,grasseyer,installer¦5ons:orner,gener,juger,lover,mater,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦4ons:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦7ons:peupler,fournir,innover,repaître,bailler,revendre,guetter¦3errons:revoir¦5terons:voleter¦1ènerons:mener¦2errons:quérir¦3drons:vouloir¦3ons:dire,lire,rire,uire¦1épartirons:repartir¦11ons:interpeller¦6rons:acquerir"
    },
    "vous": {
      "fwd": "errez:érir¦épartirez:epartir¦îtrez:itre¦1drez:uloir¦2rez:erir¦3z:ure,dre,vre¦3ez:dir,uir¦3lerez:peler¦4z:rire,oire,uire,dire¦4ez:ller,tter¦5z:ncire",
      "both": "5ez:ucier,ffrir,liger,rtrir,ertir,itier,urler,ifler,arnir,mater,eurir,xiger,ernir,nfler,arler,erger,nchir,utier,psier,arner,uvrir,ortir,évoir,erner,téger¦5terez:elleter¦5z:laire¦4ez:unir,rrir,iver,dier,grir,acer,uger,ager,ayer,aner,rier,oler,iter,nier,hier,aver,nser,fier,lier,pter,oter,gter,oser,cter,rcer,aser,nnir,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4z:utre,ttre,fire,ître¦4rez:mouvoir¦3ez:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3lerez:celer,veler¦3rez:cevoir¦3z:cre,pre,ore¦2êterez:rreter¦2èlerez:rteler¦2èterez:aleter,ureter¦2trez:âtre¦2ez:ïr¦2rez:urir¦2errez:nvoyer¦1errez:hoir¦1égerez:ieger¦1èlerez:deler¦1erez:faire¦1ènerez:mener,sener¦1urez:avoir¦1udrez:aloir¦1ierez:uyer,oyer¦1èterez:heter¦échirez:echir¦éerez:eer¦écierez:ecier¦èverez:ever¦iendrez:enir¦èserez:eser¦ècerez:ecer",
      "rev": "3:nirez,yerez¦4:voirez,atrez,lurez,airez,ivrez,ndirez,igerez,rnerez,rdrez,rgerez,enerez,lserez,overez,stirez,guirez,aterez,rverez¦5:otterez,udirez,indrez,andrez,roirez,ocierez,allerez,urdirez,uplerez,duirez,atterez,crirez,ncierez,ondrez¦eler:èlerez¦evrer:èvrerez¦ener:ènerez¦2oir:uvrez,evrez,everrez¦2itre:raîtrez¦3er:tellerez,letterez¦3loir:voudrez¦4ir:eillerez¦4er:ppellerez¦5ir:cquerrez",
      "ex": "irez:aller¦serez:être¦1èlerez:geler,peler¦3terez:jeter¦1èvrerez:sevrer¦1ierez:oyer¦4erez:montrer¦1urez:avoir¦8ez:départir,pourvoir,associer,impulser,investir,observer,officier,babiller,fouetter,habiller¦4rez:mouvoir¦6ez:partir,forger,verdir,lutter¦3rrez:pouvoir¦6erez:cueillir¦3rez:devoir¦1errez:voir¦7z:embatre,prendre,sourire¦5z:taire,frire,boire,crire,luire,nuire,cuire¦4z:dire,lire,rire,uire¦1erez:faire¦6z:braire,iendre,coudre,moudre,soudre,pendre,rendre,vendre,fendre¦5lerez:atteler,bateler¦7ez:diriger,peupler,fournir,innover,bailler,guetter¦5ez:orner,figer,gener,lover,mater,jouir¦4ez:oser,user,fier,lier,nier,ayer,fuir¦9ez:retourner,grasseyer,licencier¦3errez:revoir¦5terez:voleter¦1ènerez:mener¦2errez:quérir¦3drez:vouloir¦10z:circoncire,comprendre¦8z:résoudre,absoudre,attendre,rependre,revendre,entendre¦9z:descendre,reprendre,instruire,interdire,apprendre¦1épartirez:repartir¦11ez:interpeller"
    },
    "ils": {
      "fwd": "erront:érir¦ont:e¦épartiront:epartir¦îtront:itre¦1dront:uloir¦2ront:erir¦3ont:dir,uir¦3leront:peler¦4ont:tter¦5ont:eller",
      "both": "5ont:icier,urrir,tiver,igrir,ncier,ulser,seyer,eurir,mpter,ioler,arler,aller,nchir,ertir,errir,ocier,epter,rvoir,ortir,évoir,coler,téger¦5teront:elleter¦5ent:iller¦4ont:rier,rver,unir,trir,nier,acer,uger,stir,over,nnir,fler,ager,ater,iger,iter,rnir,vrir,lier,aner,hier,aver,nser,fier,rner,oter,gter,oser,cter,rcer,aser,ayer,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ront:mouvoir¦3ont:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3leront:celer,veler¦3ront:cevoir¦2êteront:rreter¦2èleront:rteler¦2èteront:aleter,ureter¦2tront:âtre¦2ont:ïr¦2ront:urir¦2erront:nvoyer¦1erront:hoir¦1égeront:ieger¦1èleront:deler¦1eront:faire¦1èneront:mener,sener¦1uront:avoir¦1udront:aloir¦1ieront:uyer,oyer¦1èteront:heter¦échiront:echir¦éeront:eer¦écieront:ecier¦èveront:ever¦iendront:enir¦èseront:eser¦èceront:ecer",
      "rev": "3:yeront¦4:ndiront,sieront,rriront,rgeront,pleront,oleront,eneront,rleront,ouiront,guiront,dieront,friront¦5:otteront,riveront,utieront,urdiront,atteront,itieront,utteront,ucieront¦eler:èleront¦evrer:èvreront¦:ent¦ener:èneront¦2oir:uvront,evront,everront¦2e:oront,pront,cront¦2itre:raîtront¦3ir:illeront¦3e:atront,luront,firont,utront,airont,ivront,rdront¦3er:telleront,letteront¦3loir:voudront¦4e:oîtront,udiront,indront,andront,roiront,ettront,duiront,ondront,criront,attront¦4er:ppelleront¦5e:onciront,naîtront,soudront,rendront,pendront,tendront",
      "ex": "iront:aller¦seront:être¦1èleront:geler,peler¦3teront:jeter¦1èvreront:sevrer¦1ieront:oyer¦4eront:montrer¦1uront:avoir¦8ont:départir,diverger,descendre,fouetter,instruire,interdire¦4ront:mouvoir¦6ont:partir,barrir,forger,hurler,isoler,offrir,verdir,sourire¦3rront:pouvoir¦6eront:cueillir¦3ront:devoir¦1erront:voir¦1eront:faire¦7ont:arriver,peupler,rigoler,initier,mendier,soucier,repaître,revendre,guetter¦5leront:atteler,bateler¦9ont:autopsier,balbutier¦9ent:aventurer¦5ont:opter,voler,gener,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦4ont:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦3erront:revoir¦5teront:voleter¦8ent:facturer¦1èneront:mener¦2erront:quérir¦3dront:vouloir¦3ont:dire,lire,rire,uire¦1épartiront:repartir¦11ont:interpeller¦6ront:acquerir"
    }
  },
  "imperfect": {
    "je": {
      "fwd": "ais:er¦isais:ésir¦oyais:eoir¦issais:ître¦quais:cre¦éais:eer¦édais:eder¦érais:erir¦1ais:loir,ure,pre,vre¦1ssais:itre¦2ais:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yais:roire,raire¦3ais:éger,ondre¦3yais:rvoir",
      "both": "5ais:épartir,ssentir¦5ssais:aigrir,rantir,tentir,terrir,brutir¦4ais:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssais:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sais:oncire¦3ssais:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ais:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sais:rdire,faire,laire¦3vais:crire¦3yais:ssoir,évoir¦2ssais:bir,cir,hir,pir,gir,dir¦2érais:sferer¦2ais:frir¦2sais:uire,fire¦2lvais:soudre¦2tais:âtre¦1éférais:referer¦1égeais:ieger¦1gnais:indre¦1ssais:ïr¦éressais:eresser¦éciais:ecier¦épartissais:epartir¦çais:cer",
      "rev": "udre:lvais¦1er:bais,hais,uais,mais,pais,xais,zais,wais¦1ndre:egnais¦1eer:réais¦1eter:rêtais¦1eder:cédais¦2er:etais,ftais,esais,brais,glais,trais,rlais,inais,nnais,asais,itais,usais,arais,odais,stais,rnais,orais,osais,blais,elais,siais,ayais,adais,rrais,ctais,utais,rsais,gtais,otais,irais,fiais,liais,anais,nsais,plais,idais,niais,olais,flais,ptais,eyais,grais,lsais,tiais,ovais,diais,crais¦2eoir:rsoyais¦2ître:naissais,loissais¦2re:aisais¦2cre:inquais¦2r:missais,sissais,uissais¦2erir:quérais¦3er:turais,evrais,ardais,jurais,euvais,agnais,mulais,priais,senais,surais,risais,visais,tisais,eurais,ndrais,assais,loyais,untais,antais,dulais,vulais,durais,phiais,ussais,aurais,ariais,gurais,boyais,matais,ottais,revais,ravais,eulais,urtais,culais,ellais,gulais,nciais,uttais,aulais,tivais,murais,toyais,iciais,uciais¦3r:rvissais,llissais¦3ir:venais,ourais,artais,uvrais,vêtais,tenais¦3re:batais,uivais,endais,vivais,ompais,cluais¦3ître:croissais¦3tre:raissais¦4er:nvoyais,ppuyais,bondais,dentais,chevais,rrivais,mandais,ballais,portais,ientais,ointais,rouvais,alisais,droyais,landais,rattais,rondais,nondais,ventais,mentais,ipulais,troyais¦4r:tégeais,ortissais,arrissais¦4oir:évalais,mouvais¦4ir:dormais¦4re:mettais,fondais,battais¦5er:ttentais,bsentais,ssociais,essalais,caissais,seignais,ouettais,stallais,bservais¦5ir:ssortais¦5oir:evoulais¦5re:épondais",
      "ex": "étais:être¦7ssais:asservir,assortir¦2ais:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ais:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ais:ressortir,desservir,resservir,organiser,fourvoyer¦3ais:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yais:fuir,voir¦3sais:taire,coudre,faire¦2gnais:iendre¦1uvais:boire¦3vais:crire¦2sais:dire,lire,uire¦3lais:moudre¦2lvais:soudre¦5ssais:barrir,mollir¦4yais:revoir¦4ssais:vomir,jouir¦6ssais:grossir¦3êtais:arreter¦1isais:gésir¦6yais:pourvoir¦3issais:croître¦2issais:paître,naître¦4issais:repaître¦3yais:croire,braire¦5ais:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ais:accorder,froisser"
    },
    "tu": {
      "fwd": "ais:er¦isais:ésir¦oyais:eoir¦issais:ître¦quais:cre¦éais:eer¦édais:eder¦érais:erir¦1ais:loir,ure,pre,vre¦1ssais:itre¦2ais:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yais:roire,raire¦3ais:éger,ondre¦3yais:rvoir",
      "both": "5ais:épartir,ssentir¦5ssais:aigrir,rantir,tentir,terrir,brutir¦4ais:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssais:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sais:oncire¦3ssais:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ais:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sais:rdire,faire,laire¦3vais:crire¦3yais:ssoir,évoir¦2ssais:bir,cir,hir,pir,gir,dir¦2érais:sferer¦2ais:frir¦2sais:uire,fire¦2lvais:soudre¦2tais:âtre¦1éférais:referer¦1égeais:ieger¦1gnais:indre¦1ssais:ïr¦éressais:eresser¦éciais:ecier¦épartissais:epartir¦çais:cer",
      "rev": "udre:lvais¦1er:bais,hais,uais,mais,pais,xais,zais,wais¦1ndre:egnais¦1eer:réais¦1eter:rêtais¦1eder:cédais¦2er:etais,ftais,esais,brais,glais,trais,rlais,inais,nnais,asais,itais,usais,arais,odais,stais,rnais,orais,osais,blais,elais,siais,ayais,adais,rrais,ctais,utais,rsais,gtais,otais,irais,fiais,liais,anais,nsais,plais,idais,niais,olais,flais,ptais,eyais,grais,lsais,tiais,ovais,diais,crais¦2eoir:rsoyais¦2ître:naissais,loissais¦2re:aisais¦2cre:inquais¦2r:missais,sissais,uissais¦2erir:quérais¦3er:turais,evrais,ardais,jurais,euvais,agnais,mulais,priais,senais,surais,risais,visais,tisais,eurais,ndrais,assais,loyais,untais,antais,dulais,vulais,durais,phiais,ussais,aurais,ariais,gurais,boyais,matais,ottais,revais,ravais,eulais,urtais,culais,ellais,gulais,nciais,uttais,aulais,tivais,murais,toyais,iciais,uciais¦3r:rvissais,llissais¦3ir:venais,ourais,artais,uvrais,vêtais,tenais¦3re:batais,uivais,endais,vivais,ompais,cluais¦3ître:croissais¦3tre:raissais¦4er:nvoyais,ppuyais,bondais,dentais,chevais,rrivais,mandais,ballais,portais,ientais,ointais,rouvais,alisais,droyais,landais,rattais,rondais,nondais,ventais,mentais,ipulais,troyais¦4r:tégeais,ortissais,arrissais¦4oir:évalais,mouvais¦4ir:dormais¦4re:mettais,fondais,battais¦5er:ttentais,bsentais,ssociais,essalais,caissais,seignais,ouettais,stallais,bservais¦5ir:ssortais¦5oir:evoulais¦5re:épondais",
      "ex": "étais:être¦7ssais:asservir,assortir¦2ais:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ais:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ais:ressortir,desservir,resservir,organiser,fourvoyer¦3ais:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yais:fuir,voir¦3sais:taire,coudre,faire¦2gnais:iendre¦1uvais:boire¦3vais:crire¦2sais:dire,lire,uire¦3lais:moudre¦2lvais:soudre¦5ssais:barrir,mollir¦4yais:revoir¦4ssais:vomir,jouir¦6ssais:grossir¦3êtais:arreter¦1isais:gésir¦6yais:pourvoir¦3issais:croître¦2issais:paître,naître¦4issais:repaître¦3yais:croire,braire¦5ais:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ais:accorder,froisser"
    },
    "il": {
      "fwd": "ait:er¦isait:ésir¦oyait:eoir¦issait:ître¦quait:cre¦épartissait:epartir¦éait:eer¦édait:eder¦érait:erir¦1ait:loir,ure,pre,vre¦1ssait:itre¦2ait:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yait:roire,raire¦3ait:éger,ondre¦3yait:rvoir",
      "both": "5ssait:aigrir,rantir,tentir,terrir,brutir¦5ait:ssentir¦4ait:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssait:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sait:oncire¦3ssait:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ait:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sait:rdire,faire,laire¦3vait:crire¦3yait:ssoir,évoir¦2ssait:bir,cir,hir,pir,gir,dir¦2érait:sferer¦2ait:frir¦2sait:uire,fire¦2lvait:soudre¦2tait:âtre¦1éférait:referer¦1égeait:ieger¦1gnait:indre¦1ssait:ïr¦éressait:eresser¦éciait:ecier¦çait:cer",
      "rev": "udre:lvait¦1er:bait,hait,uait,mait,pait,xait,zait,wait¦1ndre:egnait¦1eer:réait¦1eter:rêtait¦1eder:cédait¦2er:etait,ftait,esait,brait,glait,trait,rlait,inait,nnait,asait,itait,usait,arait,odait,stait,rnait,orait,osait,blait,elait,siait,ayait,adait,rrait,ctait,utait,rsait,gtait,otait,irait,fiait,liait,anait,nsait,plait,idait,niait,olait,flait,ptait,eyait,grait,lsait,tiait,ovait,diait,crait¦2eoir:rsoyait¦2ître:naissait,loissait¦2re:aisait¦2cre:inquait¦2r:missait,sissait,uissait¦2erir:quérait¦3er:turait,evrait,ardait,jurait,euvait,agnait,mulait,priait,senait,surait,risait,visait,tisait,eurait,ndrait,assait,loyait,untait,antait,dulait,vulait,durait,phiait,ussait,aurait,ariait,gurait,boyait,matait,ottait,revait,ravait,eulait,urtait,culait,ellait,gulait,nciait,uttait,aulait,tivait,murait,toyait,iciait,uciait¦3r:rvissait,llissait¦3ir:venait,ourait,artait,uvrait,vêtait,tenait¦3re:batait,uivait,endait,vivait,ompait,cluait¦3ître:croissait¦3tre:raissait¦4er:nvoyait,ppuyait,bondait,dentait,chevait,rrivait,mandait,ballait,portait,ientait,ointait,rouvait,alisait,droyait,landait,rattait,rondait,nondait,ventait,mentait,ipulait,troyait¦4r:tégeait,ortissait,arrissait¦4oir:évalait,mouvait¦4ir:dormait¦4re:mettait,fondait,battait¦5er:ttentait,bsentait,ssociait,essalait,caissait,seignait,ouettait,stallait,bservait¦5ir:ssortait,sservait¦5re:épondait",
      "ex": "était:être¦7ssait:asservir,assortir,départir¦2ait:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ait:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ait:ressortir,desservir,resservir,organiser,fourvoyer¦3ait:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yait:fuir,voir¦3sait:taire,coudre,faire¦2gnait:iendre¦1uvait:boire¦3vait:crire¦2sait:dire,lire,uire¦3lait:moudre¦2lvait:soudre¦5ssait:barrir,mollir¦4yait:revoir¦4ssait:vomir,jouir¦6ssait:grossir¦3êtait:arreter¦1isait:gésir¦6yait:pourvoir¦3issait:croître¦2issait:paître,naître¦4issait:repaître¦3yait:croire,braire¦5ait:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ait:accorder,revouloir,froisser¦1épartissait:repartir"
    },
    "nous": {
      "fwd": "ions:er¦isions:ésir¦oyions:eoir¦issions:ître¦quions:cre¦éions:eer¦édions:eder¦érions:erir¦1ions:loir,ure,pre,vre¦1ssions:itre¦2ions:uvoir,avoir,atre,ttre,utre,rdre¦2yions:soir,roire,raire¦3ons:enir,urir,êtir,rmir,vrir,érir¦3ions:ondre¦4yions:urvoir¦5ons:sentir",
      "both": "5ssions:rantir,tentir,bellir¦5ions:scendre¦5ons:pentir¦4ions:tendre,vendre,pendre,pandre¦4ssions:ussir,urrir,rtrir,ossir,eurir,ertir,arrir,errir,ouvir,mbrir¦4sions:oncire¦4ons:illir¦3ions:urire,rendre,cevoir¦3érions:nsferer¦3ssions:unir,grir,ouir,stir,avir,blir,rnir,nnir,drir,plir,utir,olir,udire,inir,énir,isir¦3sions:rdire,faire,laire¦3vions:crire¦3yions:évoir¦2ssions:bir,gir,cir,hir,pir,dir¦2êtions:rreter¦2sions:uire,fire¦2lvions:soudre¦2tions:âtre¦1éférions:referer¦1égions:ieger¦1gnions:indre¦1ssions:ïr¦éressions:eresser¦éciions:ecier¦épartissions:epartir",
      "rev": "udre:lvions¦1er:bions,cions,hions,uions,mions,pions,xions,zions,wions¦1ndre:egnions¦1eer:réions¦1eder:cédions¦2er:etions,ftions,esions,brions,glions,ngions,rlions,inions,nnions,asions,itions,usions,arions,odions,stions,rnions,orions,osions,blions,elions,siions,ayions,adions,rrions,ctions,utions,rsions,gtions,otions,irions,fiions,liions,anions,agions,nsions,plions,idions,niions,trions,olions,flions,ptions,igions,rgions,eyions,grions,lsions,tiions,ogions,ugions,ovions,diions,crions¦2eoir:rsoyions¦2ître:naissions,loissions¦2re:aisions¦2cre:inquions¦2r:missions,uissions¦2erir:quérions¦3er:turions,evrions,tégions,ardions,jurions,euvions,agnions,mulions,priions,senions,surions,risions,visions,tisions,eurions,ndrions,assions,loyions,untions,antions,dulions,vulions,durions,phiions,ussions,aurions,ariions,gurions,boyions,mations,ottions,revions,ravions,eulions,urtions,culions,ellions,gulions,nciions,uttions,pulions,aulions,tivions,murions,toyions,uciions¦3r:rvissions,llissions,frions¦3ir:ssoyions¦3re:bations,uivions,endions,vivions,ompions,cluions¦3ître:croissions¦3tre:raissions¦4er:nvoyions,ppuyions,bondions,dentions,chevions,rrivions,mandions,ballions,portions,ientions,ointions,alisions,droyions,landions,rattions,rondions,nondions,ventions,mentions,troyions¦4r:venions,ourions,artions,vêtions,ortissions,tenions,uvrions¦4oir:évalions,mouvions,voulions¦4re:mettions,fondions,pondions¦5er:ttentions,bsentions,prouvions,essalions,caissions,seignions,trouvions,ouettions,stallions,bservions¦5r:sortions,dormions¦5re:abattions",
      "ex": "étions:être¦7ssions:asservir,assortir¦2ions:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦5ons:mentir,partir,sortir,servir,offrir,sentir,dormir,quérir¦8ons:ressortir,desservir,resservir,ressentir¦3ions:devoir,aller,céder,savoir,valoir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier¦2yions:fuir,voir¦3sions:taire,coudre,faire¦2gnions:iendre¦1uvions:boire¦3vions:crire¦2sions:dire,lire,uire¦3lions:moudre¦2lvions:soudre¦4ions:pendre,rendre,vendre,fendre,porter,mouvoir,pouvoir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦4yions:revoir¦4ssions:vomir¦6ssions:languir¦5ssions:mollir¦7ons:départir¦1isions:gésir¦4ons:vêtir,venir,tenir¦6yions:pourvoir¦3issions:croître¦2issions:paître,naître¦4issions:repaître¦3yions:croire,braire¦5ions:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ions:accorder,associer,froisser,officier¦7ions:organiser,fourvoyer"
    },
    "vous": {
      "fwd": "iez:er¦isiez:ésir¦oyiez:eoir¦issiez:ître¦quiez:cre¦éiez:eer¦édiez:eder¦ériez:erir¦1iez:loir,ure,pre,vre¦1ssiez:itre¦2iez:uvoir,avoir,atre,ttre,utre,rdre¦2yiez:soir,roire,raire¦3ez:enir,urir,êtir,rmir,vrir,érir¦3iez:ondre¦4yiez:urvoir¦5ez:sentir",
      "both": "5ssiez:rantir,tentir,bellir¦5iez:scendre¦5ez:pentir¦4iez:tendre,vendre,pendre,pandre¦4ssiez:ussir,urrir,rtrir,ossir,eurir,ertir,arrir,errir,ouvir,mbrir¦4siez:oncire¦4ez:illir¦3iez:urire,rendre,cevoir¦3ériez:nsferer¦3ssiez:unir,grir,ouir,stir,avir,blir,rnir,nnir,drir,plir,utir,olir,udire,inir,énir,isir¦3siez:rdire,faire,laire¦3viez:crire¦3yiez:évoir¦2ssiez:bir,gir,cir,hir,pir,dir¦2êtiez:rreter¦2siez:uire,fire¦2lviez:soudre¦2tiez:âtre¦1éfériez:referer¦1égiez:ieger¦1gniez:indre¦1ssiez:ïr¦éressiez:eresser¦éciiez:ecier¦épartissiez:epartir",
      "rev": "udre:lviez¦1er:biez,ciez,hiez,uiez,miez,piez,xiez,ziez,wiez¦1ndre:egniez¦1eer:réiez¦1eder:cédiez¦2er:etiez,ftiez,esiez,briez,gliez,ngiez,rliez,iniez,nniez,asiez,itiez,usiez,ariez,odiez,stiez,rniez,oriez,osiez,bliez,eliez,siiez,ayiez,adiez,rriez,ctiez,utiez,rsiez,gtiez,otiez,iriez,fiiez,liiez,aniez,agiez,nsiez,pliez,idiez,niiez,triez,oliez,fliez,ptiez,igiez,rgiez,eyiez,griez,lsiez,tiiez,ogiez,ugiez,oviez,diiez,criez¦2eoir:rsoyiez¦2ître:naissiez,loissiez¦2re:aisiez¦2cre:inquiez¦2r:missiez,uissiez¦2erir:quériez¦3er:turiez,evriez,tégiez,ardiez,juriez,euviez,agniez,muliez,priiez,seniez,suriez,risiez,visiez,tisiez,euriez,ndriez,assiez,loyiez,untiez,antiez,duliez,vuliez,duriez,phiiez,ussiez,auriez,ariiez,guriez,boyiez,matiez,ottiez,reviez,raviez,euliez,urtiez,culiez,elliez,guliez,nciiez,uttiez,puliez,auliez,tiviez,muriez,toyiez,uciiez¦3r:rvissiez,llissiez,friez¦3ir:ssoyiez¦3re:batiez,uiviez,endiez,viviez,ompiez,cluiez¦3ître:croissiez¦3tre:raissiez¦4er:nvoyiez,ppuyiez,bondiez,dentiez,cheviez,rriviez,mandiez,balliez,portiez,ientiez,ointiez,alisiez,droyiez,landiez,rattiez,rondiez,nondiez,ventiez,mentiez,troyiez¦4r:veniez,ouriez,artiez,vêtiez,ortissiez,teniez,uvriez¦4oir:évaliez,mouviez,vouliez¦4re:mettiez,fondiez,pondiez¦5er:ttentiez,bsentiez,prouviez,essaliez,caissiez,seigniez,trouviez,ouettiez,stalliez,bserviez¦5r:sortiez,dormiez¦5re:abattiez",
      "ex": "étiez:être¦7ssiez:asservir,assortir¦2iez:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦5ez:mentir,partir,sortir,servir,offrir,sentir,dormir,quérir¦8ez:ressortir,desservir,resservir,ressentir¦3iez:devoir,aller,céder,savoir,valoir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier¦2yiez:fuir,voir¦3siez:taire,coudre,faire¦2gniez:iendre¦1uviez:boire¦3viez:crire¦2siez:dire,lire,uire¦3liez:moudre¦2lviez:soudre¦4iez:pendre,rendre,vendre,fendre,porter,mouvoir,pouvoir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦4yiez:revoir¦4ssiez:vomir¦6ssiez:languir¦5ssiez:mollir¦7ez:départir¦1isiez:gésir¦4ez:vêtir,venir,tenir¦6yiez:pourvoir¦3issiez:croître¦2issiez:paître,naître¦4issiez:repaître¦3yiez:croire,braire¦5iez:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6iez:accorder,associer,froisser,officier¦7iez:organiser,fourvoyer"
    },
    "ils": {
      "fwd": "aient:er¦isaient:ésir¦oyaient:eoir¦issaient:ître¦quaient:cre¦éaient:eer¦édaient:eder¦éraient:erir¦1aient:loir,ure,pre,vre¦1ssaient:itre¦2aient:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yaient:roire,raire¦3aient:éger,ondre¦3yaient:rvoir",
      "both": "5aient:épartir,ssentir¦5ssaient:aigrir,rantir,tentir,terrir,brutir¦4aient:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssaient:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4saient:oncire¦3ssaient:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3aient:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3saient:rdire,faire,laire¦3vaient:crire¦3yaient:ssoir,évoir¦2ssaient:bir,cir,hir,pir,gir,dir¦2éraient:sferer¦2aient:frir¦2saient:uire,fire¦2lvaient:soudre¦2taient:âtre¦1éféraient:referer¦1égeaient:ieger¦1gnaient:indre¦1ssaient:ïr¦éressaient:eresser¦éciaient:ecier¦épartissaient:epartir¦çaient:cer",
      "rev": "udre:lvaient¦1er:baient,haient,uaient,maient,paient,xaient,zaient,waient¦1ndre:egnaient¦1eer:réaient¦1eter:rêtaient¦1eder:cédaient¦2er:etaient,ftaient,esaient,braient,glaient,traient,rlaient,inaient,nnaient,asaient,itaient,usaient,araient,odaient,staient,rnaient,oraient,osaient,blaient,elaient,siaient,ayaient,adaient,rraient,ctaient,utaient,rsaient,gtaient,otaient,iraient,fiaient,liaient,anaient,nsaient,plaient,idaient,niaient,olaient,flaient,ptaient,eyaient,graient,lsaient,tiaient,ovaient,diaient,craient¦2eoir:rsoyaient¦2ître:naissaient,loissaient¦2re:aisaient¦2cre:inquaient¦2r:missaient,sissaient,uissaient¦2erir:quéraient¦3er:turaient,evraient,ardaient,juraient,euvaient,agnaient,mulaient,priaient,senaient,suraient,risaient,visaient,tisaient,euraient,ndraient,assaient,loyaient,untaient,antaient,dulaient,vulaient,duraient,phiaient,ussaient,auraient,ariaient,guraient,boyaient,mataient,ottaient,revaient,ravaient,eulaient,urtaient,culaient,ellaient,gulaient,nciaient,uttaient,aulaient,tivaient,muraient,toyaient,iciaient,uciaient¦3r:rvissaient,llissaient¦3ir:venaient,ouraient,artaient,uvraient,vêtaient,tenaient¦3re:bataient,uivaient,endaient,vivaient,ompaient,cluaient¦3ître:croissaient¦3tre:raissaient¦4er:nvoyaient,ppuyaient,bondaient,dentaient,chevaient,rrivaient,mandaient,ballaient,portaient,ientaient,ointaient,rouvaient,alisaient,droyaient,landaient,rattaient,rondaient,nondaient,ventaient,mentaient,ipulaient,troyaient¦4r:tégeaient,ortissaient,arrissaient¦4oir:évalaient,mouvaient¦4ir:dormaient¦4re:mettaient,fondaient,battaient¦5er:ttentaient,bsentaient,ssociaient,essalaient,caissaient,seignaient,ouettaient,stallaient,bservaient¦5ir:ssortaient¦5oir:evoulaient¦5re:épondaient",
      "ex": "étaient:être¦7ssaient:asservir,assortir¦2aient:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4aient:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7aient:ressortir,desservir,resservir,organiser,fourvoyer¦3aient:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yaient:fuir,voir¦3saient:taire,coudre,faire¦2gnaient:iendre¦1uvaient:boire¦3vaient:crire¦2saient:dire,lire,uire¦3laient:moudre¦2lvaient:soudre¦5ssaient:barrir,mollir¦4yaient:revoir¦4ssaient:vomir,jouir¦6ssaient:grossir¦3êtaient:arreter¦1isaient:gésir¦6yaient:pourvoir¦3issaient:croître¦2issaient:paître,naître¦4issaient:repaître¦3yaient:croire,braire¦5aient:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6aient:accorder,froisser"
    }
  },
  "pastParticiple": {
    "prt": {
      "fwd": "1:cturer,rtuner¦2:uir,vir¦3:aturer¦u:ouvoir,euvoir,avoir,oire,aitre¦is:eoir,ettre,erir¦:jettir,iller,turber,iliser,iltrer,iliariser,illeter,iliter,ilier¦éparti:epartir¦1u:hoir,loir,paître,naître,pre,cre¦1is:uérir¦1su:stre¦2u:atre",
      "both": "1:nturer,ïr¦2:bir,cir,ieillir,gir,pir,dir,mir,lir,éer¦3:battre,rrir,trir,unir,stir,rnir,isir,nnir,drir,brir,utir,ffire,inir,ntir¦4:ourire,ussir,igrir,eurir,xclure,nchir,ortir¦5:onclure,rossir,vertir¦4t:truire,bsoudre¦4u:vendre,pendre,courir,tendre¦4s:eclure,assir¦3t:duire,nfire,énir¦3u:ondre,ccroître,andre¦3û:ecroître¦3i:uivre¦2égé:sieger¦2u:rdre,utre,êtir,évoir,rvoir,enir¦2t:rire,indre,dire,aire¦2s:cire¦2tu:âtre¦1éféré:referer¦1ert:frir,vrir¦1écu:vivre¦1is:rendre¦1s:ore¦ê:etir¦échi:echir¦éressé:eresser¦éé:eer¦écié:ecier¦çu:cevoir¦é:er",
      "rev": "ivre:écu¦eter:êté¦1urir:ort¦1ouvoir:mu¦1oître:rû¦1re:us,du¦1udre:olu¦1dre:nt,usu¦1ettre:mis¦1oir:vu¦1iltrer:f¦1iller:p¦2oir:llu,alu¦2ir:uru¦2aître:epu,nnu¦2tre:issu¦2re:mpu,ncu,uit¦2iller:sc,ou,qu,va¦2iliariser:am¦2iliser:ss¦2ilier:um¦3er:ichu¦3oir:échu¦3eoir:ursis¦3r:rvi,uvi,oui¦3re:rui,attu¦3turer:rac¦3tuner:por¦3erir:cquis¦4re:mbatu¦4oir:voulu¦4r:ravi,ngui¦5rer:rbatu",
      "ex": "2:rire,jaillir,bailler,utiliser,veiller¦3:clure,luire,huir,fuir,babiller,perturber,faciliter,feuilleter,habiliter¦4:bruire,assujettir¦5:partir¦7:départir,impartir¦eu:avoir¦été:être¦4u:ficher,courir,battre,pendre,rendre,vendre,fendre,vouloir¦3u:férir,issir,revoir,échoir,paraitre¦2rt:mourir¦1û:devoir¦1u:voir,taire,lire,mouvoir,pouvoir,savoir,boire¦2û:croître¦5s:inclure¦4lu:résoudre¦3t:iendre,nuire,cuire¦3su:coudre¦2t:dire,uire¦3lu:moudre¦1é:naître¦2lu:soudre¦1écu:vivre¦7u:descendre¦3êté:arreter¦1éré:gerer¦2u:choir,pleuvoir,croire¦3is:asseoir¦2is:quérir¦1is:seoir,mettre¦1éparti:repartir"
    }
  },
  "presentTense": {
    "je": {
      "fwd": "2:ier¦3:tter,ller¦4:fèrer¦èce:ecer,écer¦ège:éger¦ère:érer¦is:uïr,ître¦ois:eoir¦iers:érir,erir¦eux:ouloir¦s:vre¦1ux:aloir¦1s:uillir,rmir,ire,ttre,ure,itre¦1is:aïr,avoir¦1ère:ferer¦2s:uir,outre,dir¦2e:vrir¦3s:soir¦3le:peler",
      "both": "2:éer,wer,zer,xer,per,mer,ber¦3:nuer,rver,uter,ouer,uger,over,orer,fler,oser,iger,iter,ider,oder,bler,rler,luer,nser,ager,aner,aser,sser,oter,gter,rger,rser,iner,guer,rcer,rrer,ader,iser,aler,buer,ster,irer,iver,nner,uler,nter,arer,user,oger,uver,nder,ncer,gner,rder,cter,ayer,oler,rner,rter,nger,acer,urer¦4:ièger,acrer,rquer,ivrer,igrer,seyer,mpter,aquer,squer,iquer,acher,ocher,ucher,epter,ncher,rcher,icher¦5:anquer,pulser,rmater,iltrer,entrer¦5s:tablir,urtrir,tentir,esservir,ombrir,essortir¦5te:elleter¦5e:saillir,ueillir¦4s:vahir,ollir,igrir,estir,ennir,antir,eurir,iblir,ssentir,courir,ellir,ertir,nchir,annir,ouvir,pandre,rvoir,évoir¦3s:ôtir,hoir,unir,avir,rnir,ondre,rrir,drir,plir,utir,olir,endre,soudre,inir,pentir,énir¦3le:celer,veler¦2us:faillir¦2s:bir,rdre,cir,pir,gir,indre,âtre,êtir,sir¦2ête:rreter¦2e:frir¦2èle:rteler¦2ète:aleter,ureter¦2eus:omouvoir¦1èle:deler¦1ène:mener,sener¦1s:cre,pre,ore¦1ie:uyer,oyer¦1èque:héquer¦1ète:heter¦échis:echir¦ède:éder¦ève:ever¦çois:cevoir¦iens:enir¦èche:écher¦èbre:ébrer¦èse:eser",
      "rev": "voir:i¦evrer:èvre¦égler:ègle¦ourir:eurs¦eler:èle¦ener:ène¦1ecer:mèce¦1écer:ièce¦1éger:tège¦1érer:dère¦1tre:îs¦1re:ds¦1ouloir:veux¦2ecer:épèce¦2r:tis,lis,mis,nis,ye¦2tir:ars¦2loir:vaux¦2eoir:rsois¦2re:lus,fis¦2ître:nais,lois¦2tre:ats,ets¦2erer:sfère¦2erir:quiers¦3r:rvis,ndis,cie,sie,fie,lie,rie,hie,tre,vois,ene,ave,tie,guis,nie¦3ir:ours,uvre¦3mir:dors¦3re:udis,cris,duis,lais¦3ître:crois¦3er:telle,lette¦4r:otte,ssois,ndre,urdis,atte,alle,ngle,utte,ndie¦4re:oncis¦4er:ppelle¦4tre:arais¦5re:arfais,struis¦5r:euple,uette,éfère",
      "ex": "3:oser,user,huer,muer,nuer,ayer,fier,lier,nier¦4:baver,opter,paver,gener,laver,mater¦5:graver,moquer,entrer¦6:peupler,jongler¦8:effondrer¦9:rencontrer¦10:interpeller¦suis:être¦vais:aller¦1i:avoir¦1èle:geler,peler¦3te:jeter¦1èvre:sevrer¦1ie:oyer¦1ègle:régler¦4e:montrer¦7s:asservir,impartir,assortir,répartir,vieillir,interdire¦1is:gésir,ouïr¦3s:mentir,partir,sortir,servir,voir,iendre,soudre,sentir,huir,bouillir,dormir,fuir,taire,boire,crire,faire,foutre,luire,nuire,cuire¦1eurs:mourir¦1eus:mouvoir¦1eux:pouvoir,vouloir¦4s:courir,croître,coudre,moudre,vomir,croire,braire,revivre,jouir¦1ois:devoir¦5le:atteler,bateler¦5s:revoir,honnir,départir,verdir,sourire¦5te:voleter¦8te:feuilleter¦1ène:mener¦2ux:faillir,valoir¦2is:haïr,savoir,paître,naître¦2iers:quérir¦4is:repaître¦2s:dire,lire,rire,uire,vivre¦1ère:gérer"
    },
    "tu": {
      "fwd": "s:r,vre¦èces:ecer¦èges:éger¦ères:érer¦is:uïr,ître¦ois:eoir¦iers:érir,erir¦eux:ouloir¦1ux:aloir¦1s:uillir,rmir,ire,ttre,ure,itre¦1is:avoir¦1ères:ferer¦2es:vrir¦2s:outre",
      "both": "5s:esservir,essortir¦5es:saillir,ueillir¦4les:ppeler,ateler¦4tes:oleter,lleter¦4s:courir,pandre¦3les:veler,celer¦3s:sentir,ondre,endre,soudre,pentir¦2us:faillir¦2échis:flechir¦2êtes:rreter¦2es:frir¦2èles:rteler¦2ètes:ureter¦2s:rdre,indre,âtre,êtir¦2èces:piécer¦1èles:deler¦1ènes:mener,sener¦1s:cre,pre,ore¦1eus:mouvoir¦1ies:uyer,oyer¦1èques:héquer¦1ètes:heter¦èdes:éder¦èves:ever¦çois:cevoir¦iens:enir¦èches:écher¦èbres:ébrer¦èses:eser",
      "rev": "eler:èles¦evrer:èvres¦égler:ègles¦ourir:eurs¦eter:ètes¦ener:ènes¦1ecer:mèces,pèces¦1éger:tèges¦1érer:dères¦1tre:îs¦1re:ds¦1ouloir:veux¦2r:bes,sis,yes,nis,tis,lis,mes,gis,pis,pes,xes,cis,mis,zes,wes,ées,bis¦2tir:ars¦2loir:vaux¦2eoir:rsois¦2re:lus,fis¦2ître:nais,lois¦2tre:ats,ets¦2erer:sfères¦3r:ures,aces,nges,rtes,rnes,oles,rses,ntes,rdes,gnes,nces,rvis,vois,ines,nnes,uves,oges,bles,ptes,stes,ules,ndis,ores,ives,ires,uvis,dris,rris,bues,ises,otes,ties,rres,gues,ales,uses,nses,utes,sses,ases,lies,fies,ries,rces,ides,lues,tres,rles,ites,odes,iges,oses,rges,ages,fles,aves,gres,lses,oves,uges,oues,guis,gris,ndes,cres,rves,cies,hois,ahis¦3ir:ours,uvres¦3mir:dors¦3re:udis,duis,cris,ruis¦3ître:crois¦3erir:cquiers¦4r:iches,rches,ottes,nches,ssois,pares,oches,mbris,aches,lades,iques,inues,uches,rques,urdis,uades,phies,enies,sques,aques,attes,mates,nchis,ravis,actes,ngles,ivres,anies,ndies,oques,ièges¦4re:oncis¦4tre:arais¦5r:nectes,opsies,oigtes,balles,euples,pectes,leuris,uettes,anques,urtris,éfères¦5re:arfais,terdis",
      "ex": "es:être¦vas:aller¦1s:avoir¦1èles:geler,peler¦3tes:jeter¦1èvres:sevrer¦1ies:oyer¦1ègles:régler¦4es:montrer¦1is:gésir,ouïr¦3s:mentir,partir,sortir,servir,iendre,soudre,sentir,huir,bouillir,dormir,fuir,voir,taire,boire,crire,faire,foutre,luire,suivre,oser,user,fier,huer,lier,muer,nier,nuire,nuer,cuire¦1eurs:mourir¦1eus:mouvoir¦1eux:pouvoir,vouloir¦4s:courir,croître,coudre,moudre,croire,braire,paner,parer,revivre,faner,garer,gener,jouir,mater,plaire¦1ois:devoir¦2is:haïr,savoir,paître,naître¦5les:atteler¦3ètes:haleter¦1ènes:mener¦5s:départir,dicter,planer,verdir,lutter,sourire¦2ux:faillir,valoir¦2iers:quérir¦4is:repaître¦2s:dire,lire,rire,uire,vivre¦8s:effondrer,installer¦10s:interpeller¦1ères:gérer"
    },
    "il": {
      "fwd": "1:ttre¦2:ître,utre,ier¦3:tter,ller¦4:fèrer¦èce:ecer,écer¦ège:éger¦ère:érer¦eut:ouvoir,ouloir¦oit:eoir¦iert:érir,erir¦t:vre¦ît:itre¦1ut:aloir¦1t:uillir,rmir,ire,ure¦1it:aïr,avoir¦1ère:ferer¦2t:uir,dir¦2e:vrir¦3t:soir¦3le:peler",
      "both": "1:cre¦2:éer,wer,zer,rdre,xer,per,mer,âtre,êtir,ber¦3:buer,rver,ster,aser,luer,rler,user,ater,iger,orer,pter,oder,iter,rser,ondre,ider,nser,aver,ager,aner,sser,drer,oter,gter,oser,uter,nuer,bler,rcer,rrer,nner,ouer,aler,iser,irer,iver,guer,iner,uler,nter,arer,oger,uver,nder,endre,ncer,gner,rder,cter,ayer,oler,rner,rter,nger,acer,urer¦4:ièger,acrer,oquer,rquer,ivrer,auger,nover,igrer,seyer,ifler,ltrer,aquer,squer,sentir,upler,ucher,iquer,lader,acher,ocher,pandre,ncher,rcher,icher¦5:anquer,ongler,pulser,onfler,entrer,suader,epentir¦5t:tablir,rantir,aiblir,bellir,esservir,partir¦5e:saillir,ueillir¦4t:vahir,igrir,ennir,nchir,eurir,ertir,ouvir,courir,rvoir,évoir¦4te:lleter¦4le:ateler¦4it:ccroître¦3t:ôtir,unir,omir,rnir,rrir,drir,plir,brir,soudre,utir,olir,inir,énir¦3ut:éfaillir¦3le:celer,veler¦2ît|plait:laire¦2et:choir¦2t:bir,cir,pir,gir,indre,sir¦2ête:rreter¦2e:frir¦2èle:rteler¦2ète:aleter,ureter¦1èle:deler¦1ène:mener,sener¦1t:pre,ore¦1ie:uyer,oyer¦1èque:héquer¦1ète:heter¦échit:echir¦ède:éder¦ève:ever¦çoit:cevoir¦ient:enir¦èche:écher¦èbre:ébrer¦èse:eser",
      "rev": "eler:èle¦evrer:èvre¦égler:ègle¦ourir:eurt¦ener:ène¦1ecer:mèce¦1écer:ièce¦1éger:tège¦1érer:dère¦1ouvoir:meut¦1re:d¦1ouloir:veut¦2ecer:épèce¦2loir:vaut¦2eoir:rsoit¦2re:lut,fit¦2tre:at¦2r:tit,nit,lit,ye¦2erer:sfère¦2erir:quiert¦2itre:raît¦3r:rvit,ndit,cie,sie,rge,lie,fie,nie,rie,ene,avit,tie,ouit,guit,die,tre¦3ir:art,ourt,uvre¦3mir:dort¦3re:oît,fait,rait,duit,ruit,crit¦3tre:met¦3vre:evit¦4r:otte,ssoit,urdit,evoit,atte,alle,utte¦4ir:sort¦4re:oncit,naît,ourit¦4er:ttelle,olette,ppelle¦5re:epaît,terdit¦5r:aphie,uette,urtrit,éfère",
      "ex": "1:avoir¦3:oser,user,huer,muer,nuer,ayer,mettre,fier,lier,nier¦4:mentir,partir,sortir,coudre,moudre,gener,juger,lover,sentir,paître,foutre,naître¦5:forger,entrer¦7:ressortir,diverger¦9:rencontrer¦10:interpeller¦est:être¦va:aller¦1èle:geler,peler¦3te:jeter¦1èvre:sevrer¦1ie:oyer¦1ègle:régler¦4e:montrer¦7t:asservir,assortir,retentir,vieillir,investir,meurtrir¦4t:choir,courir,croire¦1ît:gésir¦1eurt:mourir¦1it:ouïr¦1oit:devoir¦3t:servir,voir,iendre,soudre,huir,bouillir,dormir,fuir,taire,boire,crire,faire,luire,suivre,nuire,cuire¦5le:atteler¦5t:bannir,revoir,gravir,honnir,mollir,maudire,verdir¦5te:voleter¦1ène:mener¦2ut:faillir,valoir¦1eut:mouvoir,pouvoir,vouloir¦2it:haïr,savoir¦2iert:quérir¦2t:dire,lire,rire,uire,vivre¦1ère:gérer"
    },
    "nous": {
      "fwd": "ons:er¦isons:ésir¦oyons:eoir¦issons:ître¦quons:cre¦égeons:èger¦érons:èrer,erir¦1sons:ore¦1ons:ure,pre,vre¦1érons:ferer¦1ssons:itre¦2ons:enir,urir,êtir,rmir,vrir,érir,utre,ttre,rdre¦2ns:loir¦2yons:roire¦3ons:éger,ondre¦3ns:uvoir¦3yons:rvoir",
      "both": "5ssons:aigrir,rantir,tentir,terrir,brutir¦5ons:ssentir,scendre¦4ssons:vahir,ussir,ollir,nguir,ossir,eurir,ellir,nchir,ertir,outir¦4yons:échoir¦4ons:vendre,pendre,tendre,pandre,pentir¦4sons:oncire¦4ns:cevoir¦3ssons:ôtir,blir,trir,unir,stir,avir,omir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ons:urire,uger,rger,nger,ager,iger,oger,rendre,illir¦3sons:rdire¦3vons:crire¦3yons:ssoir,évoir¦2ssons:bir,gir,cir,pir,dir¦2ons:frir¦2lvons:soudre¦2sons:uire,fire,aire¦2tons:âtre¦1gnons:indre¦1ssons:ïr¦échissons:echir¦çons:cer",
      "rev": "udre:lvons¦1er:bons,hons,uons,pons,mons,xons,zons,wons,éons¦1ndre:egnons¦1èger:iégeons¦1eter:rêtons¦2er:etons,esons,brons,glons,rnons,olons,ayons,ctons,irons,rrons,inons,nnons,asons,itons,usons,arons,odons,stons,orons,osons,blons,elons,sions,otons,adons,utons,gtons,drons,fions,lions,anons,nsons,plons,idons,nions,trons,flons,rsons,ptons,atons,eyons,rlons,lsons,tions,cions,dions,grons,crons¦2r:vissons,uissons,rissons,tissons¦2eoir:rsoyons¦2ître:naissons,loissons¦2cre:inquons¦2èrer:éférons¦2erer:sférons¦3er:turons,evrons,ardons,ottons,dérons,mulons,jurons,euvons,agnons,hevons,senons,tisons,risons,visons,culons,eurons,essons,assons,loyons,untons,antons,dulons,vulons,durons,phions,ussons,aurons,lisons,gurons,revons,ravons,eulons,urtons,novons,allons,gulons,ivrons,uttons,arions,tivons,murons,toyons,cédons¦3ir:venons,ourons,artons,uvrons,vêtons,tenons¦3re:closons,uivons,endons,vivons,ompons,cluons¦3ître:croissons¦3r:llissons¦3tre:raissons¦4er:nvoyons,ppuyons,rontons,bondons,dentons,oprions,rrivons,mentons,mandons,mmenons,ientons,ointons,portons,mboyons,droyons,landons,rattons,rondons,nondons,ventons,ipulons,iaulons,troyons¦4r:tégeons¦4ir:sortons,dormons¦4re:mettons,fondons,battons¦5er:ttentons,bsentons,prouvons,essalons,caissons,seignons,trouvons,ouettons,rpellons,bservons¦5ir:évalons,mouvons,voulons¦5re:épondons",
      "ex": "sommes:être¦3ns:avoir,choir¦4ons:montrer,mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,choyer,dormir,quérir,battre,foutre,mettre,aboyer,avaler,bander,perdre,pondre,visser,fonder,mander,mordre,broyer¦7ssons:asservir,impartir,assortir,répartir,vieillir¦3ssons:huir¦7ons:ressortir,desservir,resservir,organiser,fourvoyer¦4ns:devoir,savoir,valoir¦2yons:fuir,voir¦2gnons:iendre¦1uvons:boire¦3sons:coudre¦3vons:crire¦2sons:dire,lire,uire¦3lons:moudre¦2ons:rire,oyer,oser,user,fier,lier,nier,ayer¦2lvons:soudre¦5ssons:barrir¦4yons:revoir¦4ssons:jouir¦6ssons:nourrir¦3êtons:arreter¦6ons:départir,déborder,accorder,froisser¦3ons:aller,céder,vêtir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,lover,mener,miser,murer,noyer,gérer,prier,tenir¦5ons:daigner,aborder,assurer,baigner,baisser,flatter,glisser,grogner,guetter,laisser,mesurer¦1isons:gésir¦5ns:mouvoir,pouvoir,vouloir¦6yons:pourvoir¦3issons:croître¦2issons:paître,naître¦4issons:repaître¦3yons:croire¦4érons:acquerir"
    },
    "vous": {
      "fwd": "isez:ésir¦oyez:eoir¦issez:ître¦quez:cre¦égez:èger¦érez:èrer,erer,erir¦1ez:loir,ure,pre,vre¦1sez:ore¦1ssez:itre¦2z:ser,yer,der,ner,ver¦2ez:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,ttre,utre,rdre¦2yez:roire,hoir¦3z:urer,érer¦3yez:rvoir¦3ez:ondre",
      "both": "5ssez:rossir,tentir,anchir,brutir¦5ez:ssentir¦5z:entrer,otéger¦5tes:arfaire¦4ssez:vahir,ussir,rtrir,nguir,antir,eurir,ellir,ertir,ouvir,mbrir,outir¦4ez:tendre,vendre,pendre,cendre,pandre,pentir¦4z:ltrer,evrer¦4vez:scrire¦4sez:oncire¦3ez:illir,urire,rendre,cevoir¦3z:crer,uger,grer,rger,rrer,ager,drer,iger,orer,arer,oger,irer,nger,brer¦3ssez:grir,unir,stir,avir,blir,omir,rnir,nnir,rrir,drir,plir,olir,udire,inir,énir,isir¦3tes:rdire¦3yez:ssoir,évoir¦2ssez:bir,cir,pir,gir,dir¦2êtez:rreter¦2ez:frir¦2z:wer,zer,xer,mer,ier,uer,ber,per,her,cer,ler,ter¦2sez:uire,fire¦2lvez:soudre¦2tez:âtre¦1gnez:indre¦1ssez:ïr¦échissez:echir",
      "rev": "udre:lvez¦1ndre:egnez¦1re:ites¦1èger:iégez¦2r:vissez,uissez,tissez,éez¦2eoir:rsoyez¦2ître:naissez,loissez¦2re:aisez¦2cre:inquez¦2èrer:éférez¦2erer:sférez¦3r:esez,édez,rnez,ayez,inez,nnez,asez,usez,adez,nsez,anez,idez,trez,rsez,odez,llissez,eyez,lsez,ovez¦3ir:venez,ourez,artez,uvrez,vêtez,tenez,choyez¦3re:closez,uivez,endez,vivez,cluez,ompez¦3ître:croissez¦3erir:cquérez¦3tre:raissez¦4r:turez,ardez,puyez,jurez,euvez,hevez,rosez,surez,risez,tisez,eurez,posez,essez,assez,durez,ussez,aurez,lisez,toyez,boyez,agnez,revez,ognez,gurez,ivrez,murez¦4oir:évalez,mouvez,voulez¦4ir:dormez¦4re:mettez,fondez,battez¦5r:nvoyez,idérez,bondez,cordez,rrivez,mandez,ivisez,mmenez,anisez,plosez,droyez,landez,rondez,otivez,troyez¦5ir:ssortez,sservez¦5re:épondez",
      "ex": "2es:être¦2ez:avoir,rire¦4ez:montrer,mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,perdre,pondre,mordre¦7ssez:asservir,impartir,assortir,répartir,vieillir¦3ssez:huir¦7ez:ressortir,desservir,resservir¦3ez:devoir,vêtir,savoir,valoir,venir,clure,ompre,vivre,tenir¦2yez:fuir,voir¦3sez:taire,coudre¦2gnez:iendre¦1uvez:boire¦3vez:crire¦2tes:dire¦3tes:faire¦2sez:lire,uire¦3lez:moudre¦2lvez:soudre¦9z:rencontrer,renseigner¦4yez:revoir¦4ssez:jouir,rôtir¦5z:livrer,entrer,choyer,aviser,bander,ployer,visser,fonder,graver,mander,broyer¦5ssez:mollir¦4z:créer,baver,biser,durer,paver,roser,viser,gener,jurer,lever,laver,mener,miser,murer,noyer,gérer¦4vez:écrire¦6ez:départir¦4sez:plaire¦3z:oyer,oser,user,ayer¦7z:déborder,employer,froisser,observer¦6z:daigner,aborder,assener,baigner,baisser,glisser,inonder,laisser¦1isez:gésir¦6yez:pourvoir¦3issez:croître¦2issez:paître,naître¦4issez:repaître¦3yez:croire¦8z:approuver,encaisser,retrouver,fourvoyer"
    },
    "ils": {
      "fwd": "ècent:ecer,écer¦ègent:éger¦èrent:érer¦euvent:ouvoir¦oient:eoir¦ièrent:érir,erir¦eulent:ouloir¦issent:ître¦quent:cre¦1ient:oyer,uyer¦1sent:ore¦1ent:ure,pre,vre¦1èrent:ferer¦1ssent:itre¦2ent:aloir,êtir,rmir,vrir,avoir,ttre,utre,rdre¦2nt:ier¦3nt:urer,rter,tter,rder,gner,nder,uver,nter,uler,nner,iver,aler,iser,sser,luer,ller,rver¦3ent:soir,roire,ondre¦3lent:peler¦4ent:rvoir¦4nt:nquer,fèrer",
      "both": "5nt:arquer,pulser,isquer,entrer,verger¦5ssent:tentir,bellir¦5ent:ssentir,scendre,epentir¦4ent:choir,tendre,vendre,pendre,courir,pandre,évoir¦4nt:ièger,acrer,ivrer,ngler,igrer,seyer,ltrer,aquer,upler,ucher,ndrer,igter,iquer,acher,ocher,ncher,rcher,icher¦4ssent:ollir,ennir,antir,eurir,nchir,ertir,ouvir,mbrir¦4sent:erdire,oncire¦4tent:oleter,lleter¦4lent:ateler¦3ssent:ahir,trir,grir,guir,unir,stir,avir,blir,rnir,rrir,drir,plir,utir,olir,udire,inir,énir¦3sent:laire¦3nt:nuer,oter,ouer,over,rler,fler,ater,iger,pter,iter,ider,oder,oser,rser,nser,ager,aner,aser,orer,uter,iner,bler,guer,rcer,rrer,ader,buer,ster,irer,arer,user,oger,ncer,cter,ayer,oler,rner,nger,acer¦3lent:celer,veler¦3vent:crire¦3ent:raire,illir¦3nent:rendre¦2ssent:bir,cir,pir,gir,dir,sir¦2êtent:rreter¦2nt:éer,wer,zer,xer,per,mer,ber¦2ent:frir¦2èlent:rteler¦2ètent:aleter,ureter¦2sent:uire,fire¦2lvent:soudre¦2tent:âtre¦1èlent:deler¦1ènent:mener,sener¦1gnent:indre¦1ont:faire¦1ssent:ïr¦1èquent:héquer¦1ètent:heter¦échissent:echir¦èdent:éder¦èvent:ever¦çoivent:cevoir¦iennent:enir¦èchent:écher¦èbrent:ébrer¦èsent:eser",
      "rev": "eler:èlent¦evrer:èvrent¦égler:èglent¦aire:ont¦udre:lvent¦ener:ènent¦1ecer:mècent,pècent¦1écer:iècent¦1éger:tègent¦1érer:dèrent¦1ouvoir:meuvent¦1ndre:egnent¦1ouloir:veulent¦2yer:puient,boient,loient,toient¦2r:vissent,uissent,tissent,nissent,missent,yent¦2eoir:rsoient¦2ître:naissent,loissent¦2re:aisent¦2dre:oulent¦2cre:inquent¦2erer:sfèrent¦3yer:nvoient,droient,troient¦3ir:artent,ourent,uvrent,vêtent¦3re:closent,uivent,endent,vivent,ompent,cluent,urient¦3ître:croissent¦3r:rient,cient,sient,tient,fient,lient,hient,nient,llissent,rgent,enent,ugent,dient,trent¦3er:tellent¦3erir:cquièrent¦3tre:raissent¦4r:turent,ardent,ottent,mulent,ssoient,jurent,onnent,agnent,ouvent,surent,risent,visent,tisent,salent,essent,allent,assent,antent,dulent,vulent,durent,intent,ussent,aurent,evoient,lisent,gurent,ravent,urtent,fluent,gulent,uttent,pulent,aulent,oquent,murent¦4oir:évalent¦4ir:dorment¦4re:fondent,battent,pondent¦4er:ppellent¦5r:tentent,bordent,bondent,dentent,rrivent,sculent,mandent,leurent,runtent,anisent,ientent,portent,lattent,uettent,landent,rattent,rondent,oculent,ventent,mentent,anquent,otivent,éfèrent¦5ir:ssortent,sservent¦5re:rmettent,emettent",
      "ex": "sont:être¦ont:avoir¦vont:aller¦1èlent:geler,peler¦3tent:jeter¦1èvrent:sevrer¦1ient:oyer¦1èglent:régler¦4ent:montrer,mentir,partir,sortir,courir,servir,pendre,rendre,vendre,fendre,sentir,dormir,battre,croire,foutre,mettre,perdre,pondre,mordre¦7ssent:asservir,impartir,assortir,répartir,vieillir¦1isent:gésir¦3ssent:huir¦1eurent:mourir¦7ent:ressortir,desservir,resservir,pourvoir¦1oivent:devoir¦3ent:fuir,voir,vêtir,savoir,valoir,clure,ompre,vivre¦3sent:taire,coudre¦2gnent:iendre¦3vent:boire,crire¦2sent:dire,lire,uire¦1ont:faire¦3lent:moudre¦2ent:rire¦2lvent:soudre¦5lent:atteler¦5ssent:bannir,honnir¦4nt:baver,paver,gener,juger,laver,biser,durer,viser,haler,jurer,miser,murer¦3nt:oser,user,huer,muer,nuer,ayer,fier,lier,nier¦9nt:rencontrer,confronter,renseigner¦5ent:revoir,sourire,omettre¦4ssent:vomir,jouir,rôtir¦5nt:forger,graver,jauger,moquer,entrer,porter,avaler,bander,panner,vanner,visser,fonder,mander,meuler¦1ènent:mener¦6ent:départir¦3ient:choyer,broyer¦6nt:daigner,baigner,baisser,polluer,glisser,grogner,gueuler,inonder,laisser¦1euvent:mouvoir,pouvoir¦2ièrent:quérir¦1eulent:vouloir¦3issent:croître¦2issent:paître,naître¦4issent:repaître¦7nt:abreuver,absenter,accorder,demeurer,froisser,observer¦8nt:encaisser¦11ent:retransmettre¦6ient:fourvoyer¦10nt:interpeller¦2ient:noyer¦1èrent:gérer"
    }
  }
}