// generated in ./lib/models
export default {
  "noun": {
    "plural": {
      "fwd": "s:¦oeurs:œur,œurs¦ses:x¦2x:au¦2ux:ial,éal,vail¦2es:is¦5es:ustin",
      "both": "5ses:yageur,ordeur,celeur¦5rices:lisateur,locuteur,ommateur¦5ères:apetier¦4rices:dacteur,venteur,ucateur,nnateur¦4es:féré,rmal,dian¦4nes:bien¦4ux:pital¦4ses:ileur,aneur¦4x:eveu,ijou¦4ves:aptif¦3ux:otal,étal,oral,éral,eval,imal¦3es:tué,han¦3x:jeu,ieu,hou,lou¦3rices:éateur¦2ux:pal,cal,nal¦oeux:œu¦oeuds:œud¦oeuvres:œuvre¦oeufs:œuf",
      "rev": "1:ns,ts,és,rs,us,is,as,ms,ls,cs,ks,os,gs,ys,ps,bs,ws,hs¦2:ges,tes,ies,des,hes,mes,ifs,efs,ues,xes,pes,bes,rds,nds,rfs,ids,oux,fes,yes,eds,afs,ïds,ees¦3:lles,nces,hées,ires,ares,gles,ines,lées,ones,rres,ules,tres,nées,ènes,ures,iles,cles,ores,lnes,mnes,rses,ises,eaux,oles,oses,lves,rnes,yaux,sses,bles,bres,pres,aces,ases,dres,înes,cres,sées,fres,èles,rces,unes,rves,ôles,dées,uves,nses,vées,ples,pses,èves,gnes,aves,bées,ênes,nres,uaux,èses,tées,âles,rles,ûres,oces,cées,èces,rofs,uces,ônes,êves,yles,sces¦4:lyses,dices,rmées,tères,hères,pices,nanes,canes,riaux,onnes,ouses,tanes,lices,tales,auses,éales,èvres,fères,muses,dales,rives,uanes,cales,mères,nantes,gères,cices,iales,ranes,léaux,yères,gales,cives,tices,ivres,annes,vaises,manes,sères,quées,vices,fices,sanes,fanes,rales,pères,pales,irées,sales,cères¦5:ulantes,rières,avanes,nières,uffles,abanes,dières,frères,atives,imales,onales,ctives,ndives,lières,inales,sières,meuses,onaises,ivrées,mières,éduses,yennes,rganes,auvres,oupées,écoises,idives,vières,olives¦1œur:hoeurs¦2eur:utrices,itrices,ctrices¦3r:heuses,ueuses,deuses,seuses¦3l:déaux,ivaux¦3eur:matrices¦3il:avaux¦4eur:tratrices¦4l:rciaux¦4r:lleuses,rteuses¦4x:gieuses¦5x:gineuses¦5eur:dicatrices",
      "ex": "yeux:œil¦oeillets:œillet¦oeilletons:œilleton¦oestrogènes:œstrogène¦oeufs:œuf¦oeuvres:œuvre¦11rices:administrateur¦8es:ambulant,augustin¦8ses:chercheur,cueilleur,demandeur¦9rices:distributeur¦10es:enseignant¦7ses:faucheur¦3x:feu,jeu,pou,eau¦5x:genou,hibou¦8rices:informateur¦5ses:joueur¦2ux:mal¦5rices:moniteur¦6ses:pondeur,porteur,tisseur¦7rices:producteur¦10rices:revendicateur¦4ux:rival¦2es:un¦3s:ale,île,ive¦7s:antenne,convive,litière,matière,matrice,pieuvre,rentrée,rizière¦10s:arpenteuse,bleuetière,locomotive,obsidienne¦5s:bière,bouée,durée,frère,marée,olive,purée¦4s:buse,cale,cane,fane,mère,pale,père,rive,ruse,veuf,vice¦9s:chargeuse,cicatrice,cimetière,frontière,gouttière,nébuleuse,sénatrice¦12s:charpentière¦1oeurs:cœur,mœurs,sœur¦6s:denrée,entrée,excuse,rangée¦11s:diapositive,visionneuse¦8s:éolienne¦2s:if¦13s:photocopieuse"
    }
  },
  "adjective": {
    "female": {
      "fwd": "1:e¦lle:au¦ue:û¦se:x¦1e:d¦1que:ïc¦1ue:g¦2se:as¦2e:un,ir,ur,ul,ar,ol¦2te:oi¦3e:ril",
      "both": "1:m,p¦2:pa,or,uo¦3:cho¦4:colo¦5te:illot,avori¦5ne:aysan¦5e:ormon,onfus¦5se:dalou¦4e:atil,btil,idon¦4te:olet,pret,âlot,llet,eret,luet,quet,ulot,elet¦4sse:ître¦4le:ntil¦4ète:omplet¦3te:jet,net,det¦3ète:eplet¦3que:blic,rec¦3e:cis,pon,mis,dou,uis,ris,vil,leu¦3le:eil¦3he:anc¦3gne:énin¦2e:cu,çu,ûr,yr,pu,vu,fu,bu,mu,hu,su,du,an,nu,al,in,ru,lu,tu¦2se:os¦2sse:aux,ta¦2ète:suet,cret¦2ne:on,en¦2ë:gu¦2le:el¦1que:rc¦1ète:iet¦1e:ï,i,t,é¦1îche:ais¦1ève:ref¦ère:er¦ve:f",
      "rev": "1:o,tte,c¦2:me,nde,rde,ge,ze,ude,be,xe,pe,oue¦3:ble,lte,gre,ire,oce,gle,rre,rune,bre,mune,tre,nse,ôle,ace,nole,rne,ade,èle,ide,oide,rasse,tune,vre,ongue,oule,yare,nce,gole,cure,âle,phe,ice,olote,ose,eule,ple,dre¦4:iste,thée,bile,cile,ïste,lite,aste,gile,uture,sque,nête,paire,èque,aune,uste,âche,isse,uche,cule,este,ogue,oche,oque,vère,ague,irile¦5:surde,tique,mique,sique,fique,nique,vique,lasse,crate,ingue,xique,pique,ivole,hique,stile,ature,utile,énile,gique,dique,rique,ncère,uille¦ec:èche¦1x:uce¦1u:olle¦2c:aïque¦2n:ligne¦2au:velle,celle,gelle¦2x:euse",
      "ex": "3:bio¦4:chic,apte,hâte,rare,sale¦5:digne,fonde,jeune,riche,utile¦6:chauve,propre¦7:fertile,stérile¦8:chouette,commande,continue,enceinte,héroïque,patriote,prospère¦9:disparate,idyllique¦10:alcoolique,initiative,symbolique¦4te:blet,muet¦3ce:doux¦4e:flou,cool,laid,noir,pair¦2lle:fou,beau¦2e:lu,nu,tu,vu¦4gne:malin¦3e:mou,vil,dur,nul,pur,sur¦3te:net,sot,coi¦6te:rigolo¦1èche:sec¦7te:simplet¦5e:tabou,clair,impur¦3se:bas¦1ue:dû¦5se:jaloux¦6e:puéril"
    },
    "plural": {
      "fwd": "1:s,x¦s:¦us:û¦2x:au",
      "both": "5ux:énatal¦4ux:gétal,macal,arcal,rutal¦3ux:ocal,otal,ival,stal,éval,etal,scal,ital,ntal,ccal,ical¦2ux:bal,çal,xal,yal,éal,dal,pal,gal,sal,ial,mal,ral,nal",
      "rev": "3:eaux,oux,ras,ros,eux¦4:pris,quis,umis¦5:onfus¦:s¦2l:caux,haux",
      "ex": "3:bas¦4:faux,gris¦5:frais¦6:précis¦4ux:ducal,fécal¦2ux:mal¦8ux:triomphal¦1us:dû"
    },
    "femalePlural": {
      "fwd": "lles:au¦ues:û¦ses:x¦1s:e¦1es:d¦1ques:ïc¦1ues:g¦2ses:as¦2es:un,ir,ur,ul,ar,ol¦2tes:oi¦3es:ril",
      "both": "5tes:illot,avori¦5nes:aysan¦5es:ormon,onfus¦5ses:dalou¦4es:atil,btil,idon¦4tes:olet,pret,âlot,llet,eret,luet,quet,ulot,elet¦4sses:ître¦4les:ntil¦4s:colo¦4ètes:omplet¦3tes:jet,net,det¦3ètes:eplet¦3ques:blic,rec¦3es:cis,pon,mis,dou,uis,ris,vil,leu¦3les:eil¦3s:cho¦3hes:anc¦3gnes:énin¦2es:cu,çu,ûr,yr,pu,vu,fu,bu,mu,hu,su,du,an,nu,al,in,ru,lu,tu¦2s:pa,or,uo¦2ses:os¦2sses:aux,ta¦2ètes:suet,cret¦2nes:on,en¦2ës:gu¦2les:el¦1ques:rc¦1ètes:iet¦1es:ï,i,t,é¦1îches:ais¦1s:m,p¦1èves:ref¦ères:er¦ves:f",
      "rev": "1:os,ttes,cs¦2:mes,ndes,rdes,ges,zes,udes,bes,xes,pes,oues¦3:bles,ltes,gres,ires,oces,gles,rres,runes,bres,munes,tres,nses,ôles,aces,noles,rnes,ades,èles,ides,oides,rasses,tunes,vres,ongues,oules,yares,nces,goles,cures,âles,phes,ices,olotes,oses,eules,ples,dres¦4:istes,thées,biles,ciles,ïstes,lites,astes,giles,utures,sques,nêtes,paires,èques,aunes,ustes,âches,isses,uches,cules,estes,ogues,oches,oques,vères,agues,iriles¦5:surdes,tiques,miques,siques,fiques,niques,viques,lasses,crates,ingues,xiques,piques,ivoles,hiques,stiles,atures,utiles,éniles,giques,diques,riques,ncères,uilles¦ec:èches¦1x:uces¦1u:olles¦2c:aïques¦2n:lignes¦2au:velles,celles,gelles¦2x:euses",
      "ex": "3s:bio¦4tes:blet,muet¦4s:chic,apte,hâte,rare,sale¦3ces:doux¦4es:flou,cool,laid,noir,pair¦2lles:fou,beau¦2es:lu,nu,tu,vu¦4gnes:malin¦3es:mou,vil,dur,nul,pur,sur¦3tes:net,sot,coi¦6tes:rigolo¦1èches:sec¦7tes:simplet¦5es:tabou,clair,impur¦10s:alcoolique,initiative,symbolique¦3ses:bas¦6s:chauve,propre¦8s:chouette,commande,continue,enceinte,héroïque,patriote,prospère¦5s:digne,fonde,jeune,riche,utile¦9s:disparate,idyllique¦1ues:dû¦7s:fertile,stérile¦5ses:jaloux¦6es:puéril"
    }
  },
  "futureTense": {
    "je": {
      "fwd": "errai:érir¦ai:e¦épartirai:epartir¦îtrai:itre¦1udrai:aloir¦1drai:uloir¦2rai:erir¦3ai:dir,uir¦3lerai:peler¦4ai:ller,tter",
      "both": "5ai:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4ai:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4rai:mouvoir¦3ai:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3lerai:celer,veler¦3rai:cevoir¦2udrai:faillir¦2êterai:rreter¦2èlerai:rteler¦2èterai:aleter,ureter¦2trai:âtre¦2ai:ïr¦2rai:urir¦2errai:nvoyer¦1errai:hoir¦1égerai:ieger¦1èlerai:deler¦1erai:faire¦1ènerai:mener,sener¦1urai:avoir¦1ierai:uyer,oyer¦1èterai:heter¦échirai:echir¦éerai:eer¦écierai:ecier¦èverai:ever¦iendrai:enir¦èserai:eser¦ècerai:ecer",
      "rev": "3:lirai,yerai¦4:ogerai,ndirai,userai,anerai,hierai,enerai,rlerai,ouirai,guirai,dierai¦5:otterai,ocierai,urdirai,enierai,atterai,allerai,utterai,icierai¦eler:èlerai¦evrer:èvrerai¦ener:ènerai¦2oir:uvrai,evrai,everrai¦2loir:vaudrai¦2e:orai,prai,crai¦2itre:raîtrai¦3e:atrai,lurai,firai,utrai,airai,ivrai,rdrai¦3er:tellerai,letterai¦3loir:voudrai¦4ir:eillerai¦4e:oîtrai,udirai,indrai,andrai,roirai,ettrai,ondrai,duirai,ruirai,crirai,attrai¦4er:ppellerai¦5e:oncirai,naîtrai,soudrai,rendrai,cendrai,pendrai,tendrai",
      "ex": "irai:aller¦serai:être¦1èlerai:geler,peler¦3terai:jeter¦1èvrerai:sevrer¦1ierai:oyer¦4erai:montrer¦1urai:avoir¦8ai:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4rai:mouvoir¦6ai:partir,renier,hurler,mollir,verdir,sourire¦3rrai:pouvoir¦6erai:cueillir¦3rai:devoir¦9ai:assaillir¦1errai:voir¦1erai:faire¦7ai:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5lerai:atteler,bateler¦4ai:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5ai:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6terai:pelleter¦13ai:photographier¦3errai:revoir¦5terai:voleter¦10ai:interroger¦1ènerai:mener¦2udrai:faillir,valoir¦2errai:quérir¦3drai:vouloir¦3ai:dire,lire,rire,uire¦1épartirai:repartir¦11ai:interpeller¦6rai:acquerir"
    },
    "tu": {
      "fwd": "erras:érir¦as:e¦épartiras:epartir¦îtras:itre¦1udras:aloir¦1dras:uloir¦2ras:erir¦3as:dir,uir¦3leras:peler¦4as:ller,tter",
      "both": "5as:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4as:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ras:mouvoir¦3as:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3leras:celer,veler¦3ras:cevoir¦2udras:faillir¦2êteras:rreter¦2èleras:rteler¦2èteras:aleter,ureter¦2tras:âtre¦2as:ïr¦2ras:urir¦2erras:nvoyer¦1erras:hoir¦1égeras:ieger¦1èleras:deler¦1eras:faire¦1èneras:mener,sener¦1uras:avoir¦1ieras:uyer,oyer¦1èteras:heter¦échiras:echir¦éeras:eer¦écieras:ecier¦èveras:ever¦iendras:enir¦èseras:eser¦èceras:ecer",
      "rev": "3:liras,yeras¦4:ogeras,ndiras,useras,aneras,hieras,eneras,rleras,ouiras,guiras,dieras¦5:otteras,ocieras,urdiras,enieras,atteras,alleras,utteras,icieras¦eler:èleras¦evrer:èvreras¦ener:èneras¦2oir:uvras,evras,everras¦2loir:vaudras¦2e:oras,pras,cras¦2itre:raîtras¦3e:atras,luras,firas,utras,airas,ivras,rdras¦3er:telleras,letteras¦3loir:voudras¦4ir:eilleras¦4e:oîtras,udiras,indras,andras,roiras,ettras,ondras,duiras,ruiras,criras,attras¦4er:ppelleras¦5e:onciras,naîtras,soudras,rendras,cendras,pendras,tendras",
      "ex": "iras:aller¦seras:être¦1èleras:geler,peler¦3teras:jeter¦1èvreras:sevrer¦1ieras:oyer¦4eras:montrer¦1uras:avoir¦8as:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4ras:mouvoir¦6as:partir,renier,hurler,mollir,verdir,sourire¦3rras:pouvoir¦6eras:cueillir¦3ras:devoir¦9as:assaillir¦1erras:voir¦1eras:faire¦7as:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5leras:atteler,bateler¦4as:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5as:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6teras:pelleter¦13as:photographier¦3erras:revoir¦5teras:voleter¦10as:interroger¦1èneras:mener¦2udras:faillir,valoir¦2erras:quérir¦3dras:vouloir¦3as:dire,lire,rire,uire¦1épartiras:repartir¦11as:interpeller¦6ras:acquerir"
    },
    "il": {
      "fwd": "erra:érir¦a:e¦épartira:epartir¦îtra:itre¦1udra:aloir¦1dra:uloir¦2ra:erir¦3a:dir,uir¦3lera:peler¦4a:ller,tter",
      "both": "5a:ucier,erver,rtrir,anier,ncier,ouser,itier,seyer,eurir,cuser,plier,laner,upler,auser,llier,blier,ertir,nchir,utier,psier,mbrir,ouver,buser,euver,rvoir,ortir,évoir,arler,téger¦4a:vrir,frir,unir,ager,grir,aver,uger,stir,over,lser,nnir,ater,iger,blir,oler,rnir,fler,gner,iner,fier,oser,acer,gter,rger,nser,cter,bler,rcer,rrir,ayer,aler,iser,drir,ttir,ster,inir,iver,rier,rner,oter,plir,pter,utir,iter,aser,nner,olir,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ra:mouvoir¦3a:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,vir,sir,der,uer,rer,her,ber¦3lera:celer,veler¦3ra:cevoir¦2udra:faillir¦2êtera:rreter¦2èlera:rteler¦2ètera:aleter,ureter¦2tra:âtre¦2a:ïr¦2ra:urir¦2erra:nvoyer¦1erra:hoir¦1égera:ieger¦1èlera:deler¦1era:faire¦1ènera:mener,sener¦1ura:avoir¦1iera:uyer,oyer¦1ètera:heter¦échira:echir¦éera:eer¦éciera:ecier¦èvera:ever¦iendra:enir¦èsera:eser¦ècera:ecer",
      "rev": "3:lira,yera¦4:ogera,ndira,usera,anera,hiera,enera,rlera,ouira,guira,diera¦5:ottera,ociera,urdira,eniera,attera,allera,uttera,iciera¦eler:èlera¦evrer:èvrera¦ener:ènera¦2oir:uvra,evra,everra¦2loir:vaudra¦2e:ora,pra,cra¦2itre:raîtra¦3e:atra,lura,fira,utra,aira,ivra,rdra¦3er:tellera,lettera¦3loir:voudra¦4ir:eillera¦4e:oîtra,udira,indra,andra,roira,ettra,ondra,duira,ruira,crira,attra¦4er:ppellera¦5e:oncira,naîtra,soudra,rendra,cendra,pendra,tendra",
      "ex": "ira:aller¦sera:être¦1èlera:geler,peler¦3tera:jeter¦1èvrera:sevrer¦1iera:oyer¦4era:montrer¦1ura:avoir¦8a:départir,bouillir,associer,diffuser,embellir,vieillir,officier,babiller,fouetter,habiller,interdire¦4ra:mouvoir¦6a:partir,renier,hurler,mollir,verdir,sourire¦3rra:pouvoir¦6era:cueillir¦3ra:devoir¦9a:assaillir¦1erra:voir¦1era:faire¦7a:abroger,limoger,mendier,repaître,bailler,revendre,guetter¦5lera:atteler,bateler¦4a:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦5a:paner,plier,faner,fuser,gener,loger,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦6tera:pelleter¦13a:photographier¦3erra:revoir¦5tera:voleter¦10a:interroger¦1ènera:mener¦2udra:faillir,valoir¦2erra:quérir¦3dra:vouloir¦3a:dire,lire,rire,uire¦1épartira:repartir¦11a:interpeller¦6ra:acquerir"
    },
    "nous": {
      "fwd": "errons:érir¦ons:e¦épartirons:epartir¦îtrons:itre¦1drons:uloir¦2rons:erir¦3ons:dir,uir¦3lerons:peler¦4ons:ller,tter",
      "both": "5ons:ucier,ffrir,urrir,rtrir,ncier,auger,itier,urler,ifler,arnir,mater,eurir,ernir,nfler,arler,nchir,arrir,ertir,errir,arner,rvoir,ortir,évoir,erner,téger¦5terons:elleter¦4ons:vrir,iger,iver,dier,grir,acer,unir,stir,ager,ayer,aner,rier,oler,iter,nier,hier,aver,nser,fier,lier,pter,oter,gter,oser,cter,rcer,aser,nnir,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4rons:mouvoir¦3ons:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3lerons:celer,veler¦3rons:cevoir¦2êterons:rreter¦2èlerons:rteler¦2èterons:aleter,ureter¦2trons:âtre¦2ons:ïr¦2rons:urir¦2errons:nvoyer¦1errons:hoir¦1égerons:ieger¦1èlerons:deler¦1erons:faire¦1ènerons:mener,sener¦1urons:avoir¦1udrons:aloir¦1ierons:uyer,oyer¦1èterons:heter¦échirons:echir¦éerons:eer¦écierons:ecier¦èverons:ever¦iendrons:enir¦èserons:eser¦ècerons:ecer",
      "rev": "3:nirons,yerons¦4:ndirons,sierons,tierons,rgerons,rnerons,plerons,enerons,lserons,ouirons,guirons,aterons,rverons¦5:otterons,ocierons,urdirons,atterons,noverons,utterons,icierons¦eler:èlerons¦evrer:èvrerons¦ener:ènerons¦2oir:uvrons,evrons,everrons¦2e:orons,prons,crons¦2itre:raîtrons¦3e:atrons,lurons,firons,utrons,airons,ivrons,rdrons¦3er:tellerons,letterons¦3loir:voudrons¦4ir:eillerons¦4e:oîtrons,udirons,indrons,androns,roirons,ettrons,duirons,ondrons,crirons,attrons¦4er:ppellerons¦5e:oncirons,naîtrons,soudrons,rendrons,cendrons,pendrons,truirons,tendrons",
      "ex": "irons:aller¦serons:être¦1èlerons:geler,peler¦3terons:jeter¦1èvrerons:sevrer¦1ierons:oyer¦4erons:montrer¦1urons:avoir¦8ons:départir,associer,diverger,impulser,observer,officier,babiller,emballer,fouetter,habiller,interdire¦4rons:mouvoir¦6ons:partir,forger,verdir,sourire¦3rrons:pouvoir¦6erons:cueillir¦3rons:devoir¦1errons:voir¦1erons:faire¦5lerons:atteler,bateler¦9ons:autopsier,balbutier,retourner,grasseyer,installer¦5ons:orner,gener,juger,lover,mater,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦4ons:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦7ons:peupler,fournir,innover,repaître,bailler,revendre,guetter¦3errons:revoir¦5terons:voleter¦1ènerons:mener¦2errons:quérir¦3drons:vouloir¦3ons:dire,lire,rire,uire¦1épartirons:repartir¦11ons:interpeller¦6rons:acquerir"
    },
    "vous": {
      "fwd": "errez:érir¦épartirez:epartir¦îtrez:itre¦1drez:uloir¦2rez:erir¦3z:ure,dre,vre¦3ez:dir,uir¦3lerez:peler¦4z:rire,oire,uire,dire¦4ez:ller,tter¦5z:ncire",
      "both": "5ez:ucier,ffrir,liger,rtrir,ertir,itier,urler,ifler,arnir,mater,eurir,xiger,ernir,nfler,arler,erger,nchir,utier,psier,arner,uvrir,ortir,évoir,erner,téger¦5terez:elleter¦5z:laire¦4ez:unir,rrir,iver,dier,grir,acer,uger,ager,ayer,aner,rier,oler,iter,nier,hier,aver,nser,fier,lier,pter,oter,gter,oser,cter,rcer,aser,nnir,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4z:utre,ttre,fire,ître¦4rez:mouvoir¦3ez:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3lerez:celer,veler¦3rez:cevoir¦3z:cre,pre,ore¦2êterez:rreter¦2èlerez:rteler¦2èterez:aleter,ureter¦2trez:âtre¦2ez:ïr¦2rez:urir¦2errez:nvoyer¦1errez:hoir¦1égerez:ieger¦1èlerez:deler¦1erez:faire¦1ènerez:mener,sener¦1urez:avoir¦1udrez:aloir¦1ierez:uyer,oyer¦1èterez:heter¦échirez:echir¦éerez:eer¦écierez:ecier¦èverez:ever¦iendrez:enir¦èserez:eser¦ècerez:ecer",
      "rev": "3:nirez,yerez¦4:voirez,atrez,lurez,airez,ivrez,ndirez,igerez,rnerez,rdrez,rgerez,enerez,lserez,overez,stirez,guirez,aterez,rverez¦5:otterez,udirez,indrez,andrez,roirez,ocierez,allerez,urdirez,uplerez,duirez,atterez,crirez,ncierez,ondrez¦eler:èlerez¦evrer:èvrerez¦ener:ènerez¦2oir:uvrez,evrez,everrez¦2itre:raîtrez¦3er:tellerez,letterez¦3loir:voudrez¦4ir:eillerez¦4er:ppellerez¦5ir:cquerrez",
      "ex": "irez:aller¦serez:être¦1èlerez:geler,peler¦3terez:jeter¦1èvrerez:sevrer¦1ierez:oyer¦4erez:montrer¦1urez:avoir¦8ez:départir,pourvoir,associer,impulser,investir,observer,officier,babiller,fouetter,habiller¦4rez:mouvoir¦6ez:partir,forger,verdir,lutter¦3rrez:pouvoir¦6erez:cueillir¦3rez:devoir¦1errez:voir¦7z:embatre,prendre,sourire¦5z:taire,frire,boire,crire,luire,nuire,cuire¦4z:dire,lire,rire,uire¦1erez:faire¦6z:braire,iendre,coudre,moudre,soudre,pendre,rendre,vendre,fendre¦5lerez:atteler,bateler¦7ez:diriger,peupler,fournir,innover,bailler,guetter¦5ez:orner,figer,gener,lover,mater,jouir¦4ez:oser,user,fier,lier,nier,ayer,fuir¦9ez:retourner,grasseyer,licencier¦3errez:revoir¦5terez:voleter¦1ènerez:mener¦2errez:quérir¦3drez:vouloir¦10z:circoncire,comprendre¦8z:résoudre,absoudre,attendre,rependre,revendre,entendre¦9z:descendre,reprendre,instruire,interdire,apprendre¦1épartirez:repartir¦11ez:interpeller"
    },
    "ils": {
      "fwd": "erront:érir¦ont:e¦épartiront:epartir¦îtront:itre¦1dront:uloir¦2ront:erir¦3ont:dir,uir¦3leront:peler¦4ont:tter¦5ont:eller",
      "both": "5ont:icier,urrir,tiver,igrir,ncier,ulser,seyer,eurir,mpter,ioler,arler,aller,nchir,ertir,errir,ocier,epter,rvoir,ortir,évoir,coler,téger¦5teront:elleter¦5ent:iller¦4ont:rier,rver,unir,trir,nier,acer,uger,stir,over,nnir,fler,ager,ater,iger,iter,rnir,vrir,lier,aner,hier,aver,nser,fier,rner,oter,gter,oser,cter,rcer,aser,ayer,iser,aler,ster,drir,ttir,brir,inir,nner,user,gner,bler,oger,uver,utir,iner,êtir,soir,eoir,ntir,énir,ncer,uler,nter,rser,uter,sser,rter,nger,gler,écer¦4ront:mouvoir¦3ont:bir,wer,zer,cir,xer,per,pir,gir,mer,mir,lir,vir,sir,der,uer,rer,her,ber¦3leront:celer,veler¦3ront:cevoir¦2êteront:rreter¦2èleront:rteler¦2èteront:aleter,ureter¦2tront:âtre¦2ont:ïr¦2ront:urir¦2erront:nvoyer¦1erront:hoir¦1égeront:ieger¦1èleront:deler¦1eront:faire¦1èneront:mener,sener¦1uront:avoir¦1udront:aloir¦1ieront:uyer,oyer¦1èteront:heter¦échiront:echir¦éeront:eer¦écieront:ecier¦èveront:ever¦iendront:enir¦èseront:eser¦èceront:ecer",
      "rev": "3:yeront¦4:ndiront,sieront,rriront,rgeront,pleront,oleront,eneront,rleront,ouiront,guiront,dieront,friront¦5:otteront,riveront,utieront,urdiront,atteront,itieront,utteront,ucieront¦eler:èleront¦evrer:èvreront¦:ent¦ener:èneront¦2oir:uvront,evront,everront¦2e:oront,pront,cront¦2itre:raîtront¦3ir:illeront¦3e:atront,luront,firont,utront,airont,ivront,rdront¦3er:telleront,letteront¦3loir:voudront¦4e:oîtront,udiront,indront,andront,roiront,ettront,duiront,ondront,criront,attront¦4er:ppelleront¦5e:onciront,naîtront,soudront,rendront,pendront,tendront",
      "ex": "iront:aller¦seront:être¦1èleront:geler,peler¦3teront:jeter¦1èvreront:sevrer¦1ieront:oyer¦4eront:montrer¦1uront:avoir¦8ont:départir,diverger,descendre,fouetter,instruire,interdire¦4ront:mouvoir¦6ont:partir,barrir,forger,hurler,isoler,offrir,verdir,sourire¦3rront:pouvoir¦6eront:cueillir¦3ront:devoir¦1erront:voir¦1eront:faire¦7ont:arriver,peupler,rigoler,initier,mendier,soucier,repaître,revendre,guetter¦5leront:atteler,bateler¦9ont:autopsier,balbutier¦9ent:aventurer¦5ont:opter,voler,gener,paître,iendre,coudre,moudre,naître,soudre,pendre,rendre,vendre,fendre¦4ont:oser,user,fier,lier,nier,ayer,fuir,frire,boire,crire,luire,nuire,cuire¦3erront:revoir¦5teront:voleter¦8ent:facturer¦1èneront:mener¦2erront:quérir¦3dront:vouloir¦3ont:dire,lire,rire,uire¦1épartiront:repartir¦11ont:interpeller¦6ront:acquerir"
    }
  },
  "imperfect": {
    "je": {
      "fwd": "ais:er¦isais:ésir¦oyais:eoir¦issais:ître¦quais:cre¦éais:eer¦édais:eder¦érais:erir¦1ais:loir,ure,pre,vre¦1ssais:itre¦2ais:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yais:roire,raire¦3ais:éger,ondre¦3yais:rvoir",
      "both": "5ais:épartir,ssentir¦5ssais:aigrir,rantir,tentir,terrir,brutir¦4ais:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssais:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sais:oncire¦3ssais:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ais:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sais:rdire,faire,laire¦3vais:crire¦3yais:ssoir,évoir¦2ssais:bir,cir,hir,pir,gir,dir¦2érais:sferer¦2ais:frir¦2sais:uire,fire¦2lvais:soudre¦2tais:âtre¦1éférais:referer¦1égeais:ieger¦1gnais:indre¦1ssais:ïr¦éressais:eresser¦éciais:ecier¦épartissais:epartir¦çais:cer",
      "rev": "udre:lvais¦1er:bais,hais,uais,mais,pais,xais,zais,wais¦1ndre:egnais¦1eer:réais¦1eter:rêtais¦1eder:cédais¦2er:etais,ftais,esais,brais,glais,trais,rlais,inais,nnais,asais,itais,usais,arais,odais,stais,rnais,orais,osais,blais,elais,siais,ayais,adais,rrais,ctais,utais,rsais,gtais,otais,irais,fiais,liais,anais,nsais,plais,idais,niais,olais,flais,ptais,eyais,grais,lsais,tiais,ovais,diais,crais¦2eoir:rsoyais¦2ître:naissais,loissais¦2re:aisais¦2cre:inquais¦2r:missais,sissais,uissais¦2erir:quérais¦3er:turais,evrais,ardais,jurais,euvais,agnais,mulais,priais,senais,surais,risais,visais,tisais,eurais,ndrais,assais,loyais,untais,antais,dulais,vulais,durais,phiais,ussais,aurais,ariais,gurais,boyais,matais,ottais,revais,ravais,eulais,urtais,culais,ellais,gulais,nciais,uttais,aulais,tivais,murais,toyais,iciais,uciais¦3r:rvissais,llissais¦3ir:venais,ourais,artais,uvrais,vêtais,tenais¦3re:batais,uivais,endais,vivais,ompais,cluais¦3ître:croissais¦3tre:raissais¦4er:nvoyais,ppuyais,bondais,dentais,chevais,rrivais,mandais,ballais,portais,ientais,ointais,rouvais,alisais,droyais,landais,rattais,rondais,nondais,ventais,mentais,ipulais,troyais¦4r:tégeais,ortissais,arrissais¦4oir:évalais,mouvais¦4ir:dormais¦4re:mettais,fondais,battais¦5er:ttentais,bsentais,ssociais,essalais,caissais,seignais,ouettais,stallais,bservais¦5ir:ssortais¦5oir:evoulais¦5re:épondais",
      "ex": "étais:être¦7ssais:asservir,assortir¦2ais:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ais:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ais:ressortir,desservir,resservir,organiser,fourvoyer¦3ais:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yais:fuir,voir¦3sais:taire,coudre,faire¦2gnais:iendre¦1uvais:boire¦3vais:crire¦2sais:dire,lire,uire¦3lais:moudre¦2lvais:soudre¦5ssais:barrir,mollir¦4yais:revoir¦4ssais:vomir,jouir¦6ssais:grossir¦3êtais:arreter¦1isais:gésir¦6yais:pourvoir¦3issais:croître¦2issais:paître,naître¦4issais:repaître¦3yais:croire,braire¦5ais:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ais:accorder,froisser"
    },
    "tu": {
      "fwd": "ais:er¦isais:ésir¦oyais:eoir¦issais:ître¦quais:cre¦éais:eer¦édais:eder¦érais:erir¦1ais:loir,ure,pre,vre¦1ssais:itre¦2ais:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yais:roire,raire¦3ais:éger,ondre¦3yais:rvoir",
      "both": "5ais:épartir,ssentir¦5ssais:aigrir,rantir,tentir,terrir,brutir¦4ais:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssais:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sais:oncire¦3ssais:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ais:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sais:rdire,faire,laire¦3vais:crire¦3yais:ssoir,évoir¦2ssais:bir,cir,hir,pir,gir,dir¦2érais:sferer¦2ais:frir¦2sais:uire,fire¦2lvais:soudre¦2tais:âtre¦1éférais:referer¦1égeais:ieger¦1gnais:indre¦1ssais:ïr¦éressais:eresser¦éciais:ecier¦épartissais:epartir¦çais:cer",
      "rev": "udre:lvais¦1er:bais,hais,uais,mais,pais,xais,zais,wais¦1ndre:egnais¦1eer:réais¦1eter:rêtais¦1eder:cédais¦2er:etais,ftais,esais,brais,glais,trais,rlais,inais,nnais,asais,itais,usais,arais,odais,stais,rnais,orais,osais,blais,elais,siais,ayais,adais,rrais,ctais,utais,rsais,gtais,otais,irais,fiais,liais,anais,nsais,plais,idais,niais,olais,flais,ptais,eyais,grais,lsais,tiais,ovais,diais,crais¦2eoir:rsoyais¦2ître:naissais,loissais¦2re:aisais¦2cre:inquais¦2r:missais,sissais,uissais¦2erir:quérais¦3er:turais,evrais,ardais,jurais,euvais,agnais,mulais,priais,senais,surais,risais,visais,tisais,eurais,ndrais,assais,loyais,untais,antais,dulais,vulais,durais,phiais,ussais,aurais,ariais,gurais,boyais,matais,ottais,revais,ravais,eulais,urtais,culais,ellais,gulais,nciais,uttais,aulais,tivais,murais,toyais,iciais,uciais¦3r:rvissais,llissais¦3ir:venais,ourais,artais,uvrais,vêtais,tenais¦3re:batais,uivais,endais,vivais,ompais,cluais¦3ître:croissais¦3tre:raissais¦4er:nvoyais,ppuyais,bondais,dentais,chevais,rrivais,mandais,ballais,portais,ientais,ointais,rouvais,alisais,droyais,landais,rattais,rondais,nondais,ventais,mentais,ipulais,troyais¦4r:tégeais,ortissais,arrissais¦4oir:évalais,mouvais¦4ir:dormais¦4re:mettais,fondais,battais¦5er:ttentais,bsentais,ssociais,essalais,caissais,seignais,ouettais,stallais,bservais¦5ir:ssortais¦5oir:evoulais¦5re:épondais",
      "ex": "étais:être¦7ssais:asservir,assortir¦2ais:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ais:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ais:ressortir,desservir,resservir,organiser,fourvoyer¦3ais:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yais:fuir,voir¦3sais:taire,coudre,faire¦2gnais:iendre¦1uvais:boire¦3vais:crire¦2sais:dire,lire,uire¦3lais:moudre¦2lvais:soudre¦5ssais:barrir,mollir¦4yais:revoir¦4ssais:vomir,jouir¦6ssais:grossir¦3êtais:arreter¦1isais:gésir¦6yais:pourvoir¦3issais:croître¦2issais:paître,naître¦4issais:repaître¦3yais:croire,braire¦5ais:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ais:accorder,froisser"
    },
    "il": {
      "fwd": "ait:er¦isait:ésir¦oyait:eoir¦issait:ître¦quait:cre¦épartissait:epartir¦éait:eer¦édait:eder¦érait:erir¦1ait:loir,ure,pre,vre¦1ssait:itre¦2ait:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yait:roire,raire¦3ait:éger,ondre¦3yait:rvoir",
      "both": "5ssait:aigrir,rantir,tentir,terrir,brutir¦5ait:ssentir¦4ait:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssait:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4sait:oncire¦3ssait:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3ait:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3sait:rdire,faire,laire¦3vait:crire¦3yait:ssoir,évoir¦2ssait:bir,cir,hir,pir,gir,dir¦2érait:sferer¦2ait:frir¦2sait:uire,fire¦2lvait:soudre¦2tait:âtre¦1éférait:referer¦1égeait:ieger¦1gnait:indre¦1ssait:ïr¦éressait:eresser¦éciait:ecier¦çait:cer",
      "rev": "udre:lvait¦1er:bait,hait,uait,mait,pait,xait,zait,wait¦1ndre:egnait¦1eer:réait¦1eter:rêtait¦1eder:cédait¦2er:etait,ftait,esait,brait,glait,trait,rlait,inait,nnait,asait,itait,usait,arait,odait,stait,rnait,orait,osait,blait,elait,siait,ayait,adait,rrait,ctait,utait,rsait,gtait,otait,irait,fiait,liait,anait,nsait,plait,idait,niait,olait,flait,ptait,eyait,grait,lsait,tiait,ovait,diait,crait¦2eoir:rsoyait¦2ître:naissait,loissait¦2re:aisait¦2cre:inquait¦2r:missait,sissait,uissait¦2erir:quérait¦3er:turait,evrait,ardait,jurait,euvait,agnait,mulait,priait,senait,surait,risait,visait,tisait,eurait,ndrait,assait,loyait,untait,antait,dulait,vulait,durait,phiait,ussait,aurait,ariait,gurait,boyait,matait,ottait,revait,ravait,eulait,urtait,culait,ellait,gulait,nciait,uttait,aulait,tivait,murait,toyait,iciait,uciait¦3r:rvissait,llissait¦3ir:venait,ourait,artait,uvrait,vêtait,tenait¦3re:batait,uivait,endait,vivait,ompait,cluait¦3ître:croissait¦3tre:raissait¦4er:nvoyait,ppuyait,bondait,dentait,chevait,rrivait,mandait,ballait,portait,ientait,ointait,rouvait,alisait,droyait,landait,rattait,rondait,nondait,ventait,mentait,ipulait,troyait¦4r:tégeait,ortissait,arrissait¦4oir:évalait,mouvait¦4ir:dormait¦4re:mettait,fondait,battait¦5er:ttentait,bsentait,ssociait,essalait,caissait,seignait,ouettait,stallait,bservait¦5ir:ssortait,sservait¦5re:épondait",
      "ex": "était:être¦7ssait:asservir,assortir,départir¦2ait:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4ait:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7ait:ressortir,desservir,resservir,organiser,fourvoyer¦3ait:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yait:fuir,voir¦3sait:taire,coudre,faire¦2gnait:iendre¦1uvait:boire¦3vait:crire¦2sait:dire,lire,uire¦3lait:moudre¦2lvait:soudre¦5ssait:barrir,mollir¦4yait:revoir¦4ssait:vomir,jouir¦6ssait:grossir¦3êtait:arreter¦1isait:gésir¦6yait:pourvoir¦3issait:croître¦2issait:paître,naître¦4issait:repaître¦3yait:croire,braire¦5ait:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ait:accorder,revouloir,froisser¦1épartissait:repartir"
    },
    "nous": {
      "fwd": "ions:er¦isions:ésir¦oyions:eoir¦issions:ître¦quions:cre¦éions:eer¦édions:eder¦érions:erir¦1ions:loir,ure,pre,vre¦1ssions:itre¦2ions:uvoir,avoir,atre,ttre,utre,rdre¦2yions:soir,roire,raire¦3ons:enir,urir,êtir,rmir,vrir,érir¦3ions:ondre¦4yions:urvoir¦5ons:sentir",
      "both": "5ssions:rantir,tentir,bellir¦5ions:scendre¦5ons:pentir¦4ions:tendre,vendre,pendre,pandre¦4ssions:ussir,urrir,rtrir,ossir,eurir,ertir,arrir,errir,ouvir,mbrir¦4sions:oncire¦4ons:illir¦3ions:urire,rendre,cevoir¦3érions:nsferer¦3ssions:unir,grir,ouir,stir,avir,blir,rnir,nnir,drir,plir,utir,olir,udire,inir,énir,isir¦3sions:rdire,faire,laire¦3vions:crire¦3yions:évoir¦2ssions:bir,gir,cir,hir,pir,dir¦2êtions:rreter¦2sions:uire,fire¦2lvions:soudre¦2tions:âtre¦1éférions:referer¦1égions:ieger¦1gnions:indre¦1ssions:ïr¦éressions:eresser¦éciions:ecier¦épartissions:epartir",
      "rev": "udre:lvions¦1er:bions,cions,hions,uions,mions,pions,xions,zions,wions¦1ndre:egnions¦1eer:réions¦1eder:cédions¦2er:etions,ftions,esions,brions,glions,ngions,rlions,inions,nnions,asions,itions,usions,arions,odions,stions,rnions,orions,osions,blions,elions,siions,ayions,adions,rrions,ctions,utions,rsions,gtions,otions,irions,fiions,liions,anions,agions,nsions,plions,idions,niions,trions,olions,flions,ptions,igions,rgions,eyions,grions,lsions,tiions,ogions,ugions,ovions,diions,crions¦2eoir:rsoyions¦2ître:naissions,loissions¦2re:aisions¦2cre:inquions¦2r:missions,uissions¦2erir:quérions¦3er:turions,evrions,tégions,ardions,jurions,euvions,agnions,mulions,priions,senions,surions,risions,visions,tisions,eurions,ndrions,assions,loyions,untions,antions,dulions,vulions,durions,phiions,ussions,aurions,ariions,gurions,boyions,mations,ottions,revions,ravions,eulions,urtions,culions,ellions,gulions,nciions,uttions,pulions,aulions,tivions,murions,toyions,uciions¦3r:rvissions,llissions,frions¦3ir:ssoyions¦3re:bations,uivions,endions,vivions,ompions,cluions¦3ître:croissions¦3tre:raissions¦4er:nvoyions,ppuyions,bondions,dentions,chevions,rrivions,mandions,ballions,portions,ientions,ointions,alisions,droyions,landions,rattions,rondions,nondions,ventions,mentions,troyions¦4r:venions,ourions,artions,vêtions,ortissions,tenions,uvrions¦4oir:évalions,mouvions,voulions¦4re:mettions,fondions,pondions¦5er:ttentions,bsentions,prouvions,essalions,caissions,seignions,trouvions,ouettions,stallions,bservions¦5r:sortions,dormions¦5re:abattions",
      "ex": "étions:être¦7ssions:asservir,assortir¦2ions:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦5ons:mentir,partir,sortir,servir,offrir,sentir,dormir,quérir¦8ons:ressortir,desservir,resservir,ressentir¦3ions:devoir,aller,céder,savoir,valoir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier¦2yions:fuir,voir¦3sions:taire,coudre,faire¦2gnions:iendre¦1uvions:boire¦3vions:crire¦2sions:dire,lire,uire¦3lions:moudre¦2lvions:soudre¦4ions:pendre,rendre,vendre,fendre,porter,mouvoir,pouvoir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦4yions:revoir¦4ssions:vomir¦6ssions:languir¦5ssions:mollir¦7ons:départir¦1isions:gésir¦4ons:vêtir,venir,tenir¦6yions:pourvoir¦3issions:croître¦2issions:paître,naître¦4issions:repaître¦3yions:croire,braire¦5ions:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6ions:accorder,associer,froisser,officier¦7ions:organiser,fourvoyer"
    },
    "vous": {
      "fwd": "iez:er¦isiez:ésir¦oyiez:eoir¦issiez:ître¦quiez:cre¦éiez:eer¦édiez:eder¦ériez:erir¦1iez:loir,ure,pre,vre¦1ssiez:itre¦2iez:uvoir,avoir,atre,ttre,utre,rdre¦2yiez:soir,roire,raire¦3ez:enir,urir,êtir,rmir,vrir,érir¦3iez:ondre¦4yiez:urvoir¦5ez:sentir",
      "both": "5ssiez:rantir,tentir,bellir¦5iez:scendre¦5ez:pentir¦4iez:tendre,vendre,pendre,pandre¦4ssiez:ussir,urrir,rtrir,ossir,eurir,ertir,arrir,errir,ouvir,mbrir¦4siez:oncire¦4ez:illir¦3iez:urire,rendre,cevoir¦3ériez:nsferer¦3ssiez:unir,grir,ouir,stir,avir,blir,rnir,nnir,drir,plir,utir,olir,udire,inir,énir,isir¦3siez:rdire,faire,laire¦3viez:crire¦3yiez:évoir¦2ssiez:bir,gir,cir,hir,pir,dir¦2êtiez:rreter¦2siez:uire,fire¦2lviez:soudre¦2tiez:âtre¦1éfériez:referer¦1égiez:ieger¦1gniez:indre¦1ssiez:ïr¦éressiez:eresser¦éciiez:ecier¦épartissiez:epartir",
      "rev": "udre:lviez¦1er:biez,ciez,hiez,uiez,miez,piez,xiez,ziez,wiez¦1ndre:egniez¦1eer:réiez¦1eder:cédiez¦2er:etiez,ftiez,esiez,briez,gliez,ngiez,rliez,iniez,nniez,asiez,itiez,usiez,ariez,odiez,stiez,rniez,oriez,osiez,bliez,eliez,siiez,ayiez,adiez,rriez,ctiez,utiez,rsiez,gtiez,otiez,iriez,fiiez,liiez,aniez,agiez,nsiez,pliez,idiez,niiez,triez,oliez,fliez,ptiez,igiez,rgiez,eyiez,griez,lsiez,tiiez,ogiez,ugiez,oviez,diiez,criez¦2eoir:rsoyiez¦2ître:naissiez,loissiez¦2re:aisiez¦2cre:inquiez¦2r:missiez,uissiez¦2erir:quériez¦3er:turiez,evriez,tégiez,ardiez,juriez,euviez,agniez,muliez,priiez,seniez,suriez,risiez,visiez,tisiez,euriez,ndriez,assiez,loyiez,untiez,antiez,duliez,vuliez,duriez,phiiez,ussiez,auriez,ariiez,guriez,boyiez,matiez,ottiez,reviez,raviez,euliez,urtiez,culiez,elliez,guliez,nciiez,uttiez,puliez,auliez,tiviez,muriez,toyiez,uciiez¦3r:rvissiez,llissiez,friez¦3ir:ssoyiez¦3re:batiez,uiviez,endiez,viviez,ompiez,cluiez¦3ître:croissiez¦3tre:raissiez¦4er:nvoyiez,ppuyiez,bondiez,dentiez,cheviez,rriviez,mandiez,balliez,portiez,ientiez,ointiez,alisiez,droyiez,landiez,rattiez,rondiez,nondiez,ventiez,mentiez,troyiez¦4r:veniez,ouriez,artiez,vêtiez,ortissiez,teniez,uvriez¦4oir:évaliez,mouviez,vouliez¦4re:mettiez,fondiez,pondiez¦5er:ttentiez,bsentiez,prouviez,essaliez,caissiez,seigniez,trouviez,ouettiez,stalliez,bserviez¦5r:sortiez,dormiez¦5re:abattiez",
      "ex": "étiez:être¦7ssiez:asservir,assortir¦2iez:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦5ez:mentir,partir,sortir,servir,offrir,sentir,dormir,quérir¦8ez:ressortir,desservir,resservir,ressentir¦3iez:devoir,aller,céder,savoir,valoir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier¦2yiez:fuir,voir¦3siez:taire,coudre,faire¦2gniez:iendre¦1uviez:boire¦3viez:crire¦2siez:dire,lire,uire¦3liez:moudre¦2lviez:soudre¦4iez:pendre,rendre,vendre,fendre,porter,mouvoir,pouvoir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦4yiez:revoir¦4ssiez:vomir¦6ssiez:languir¦5ssiez:mollir¦7ez:départir¦1isiez:gésir¦4ez:vêtir,venir,tenir¦6yiez:pourvoir¦3issiez:croître¦2issiez:paître,naître¦4issiez:repaître¦3yiez:croire,braire¦5iez:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6iez:accorder,associer,froisser,officier¦7iez:organiser,fourvoyer"
    },
    "ils": {
      "fwd": "aient:er¦isaient:ésir¦oyaient:eoir¦issaient:ître¦quaient:cre¦éaient:eer¦édaient:eder¦éraient:erir¦1aient:loir,ure,pre,vre¦1ssaient:itre¦2aient:enir,urir,uvoir,êtir,rmir,vrir,érir,avoir,atre,ttre,utre,rdre¦2yaient:roire,raire¦3aient:éger,ondre¦3yaient:rvoir",
      "both": "5aient:épartir,ssentir¦5ssaient:aigrir,rantir,tentir,terrir,brutir¦4aient:ourire,vendre,pendre,cendre,tendre,pandre,pentir¦4ssaient:ussir,urrir,rtrir,nguir,ravir,eurir,ellir,ertir,outir¦4saient:oncire¦3ssaient:blir,unir,stir,rnir,nnir,drir,uvir,brir,plir,olir,udire,inir,énir,isir¦3aient:ager,uger,rger,nger,cevoir,iger,oger,rendre,illir¦3saient:rdire,faire,laire¦3vaient:crire¦3yaient:ssoir,évoir¦2ssaient:bir,cir,hir,pir,gir,dir¦2éraient:sferer¦2aient:frir¦2saient:uire,fire¦2lvaient:soudre¦2taient:âtre¦1éféraient:referer¦1égeaient:ieger¦1gnaient:indre¦1ssaient:ïr¦éressaient:eresser¦éciaient:ecier¦épartissaient:epartir¦çaient:cer",
      "rev": "udre:lvaient¦1er:baient,haient,uaient,maient,paient,xaient,zaient,waient¦1ndre:egnaient¦1eer:réaient¦1eter:rêtaient¦1eder:cédaient¦2er:etaient,ftaient,esaient,braient,glaient,traient,rlaient,inaient,nnaient,asaient,itaient,usaient,araient,odaient,staient,rnaient,oraient,osaient,blaient,elaient,siaient,ayaient,adaient,rraient,ctaient,utaient,rsaient,gtaient,otaient,iraient,fiaient,liaient,anaient,nsaient,plaient,idaient,niaient,olaient,flaient,ptaient,eyaient,graient,lsaient,tiaient,ovaient,diaient,craient¦2eoir:rsoyaient¦2ître:naissaient,loissaient¦2re:aisaient¦2cre:inquaient¦2r:missaient,sissaient,uissaient¦2erir:quéraient¦3er:turaient,evraient,ardaient,juraient,euvaient,agnaient,mulaient,priaient,senaient,suraient,risaient,visaient,tisaient,euraient,ndraient,assaient,loyaient,untaient,antaient,dulaient,vulaient,duraient,phiaient,ussaient,auraient,ariaient,guraient,boyaient,mataient,ottaient,revaient,ravaient,eulaient,urtaient,culaient,ellaient,gulaient,nciaient,uttaient,aulaient,tivaient,muraient,toyaient,iciaient,uciaient¦3r:rvissaient,llissaient¦3ir:venaient,ouraient,artaient,uvraient,vêtaient,tenaient¦3re:bataient,uivaient,endaient,vivaient,ompaient,cluaient¦3ître:croissaient¦3tre:raissaient¦4er:nvoyaient,ppuyaient,bondaient,dentaient,chevaient,rrivaient,mandaient,ballaient,portaient,ientaient,ointaient,rouvaient,alisaient,droyaient,landaient,rattaient,rondaient,nondaient,ventaient,mentaient,ipulaient,troyaient¦4r:tégeaient,ortissaient,arrissaient¦4oir:évalaient,mouvaient¦4ir:dormaient¦4re:mettaient,fondaient,battaient¦5er:ttentaient,bsentaient,ssociaient,essalaient,caissaient,seignaient,ouettaient,stallaient,bservaient¦5ir:ssortaient¦5oir:evoulaient¦5re:épondaient",
      "ex": "étaient:être¦7ssaient:asservir,assortir¦2aient:avoir,rire,béer,ayer,oyer,oser,user,fier,lier,nier¦4aient:mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,porter,mouvoir,pouvoir,dormir,quérir,vouloir,battre,foutre,mettre,avaler,bander,perdre,pondre,visser,fonder,livrer,mander,monter,mordre,broyer¦7aient:ressortir,desservir,resservir,organiser,fourvoyer¦3aient:devoir,aller,céder,vêtir,savoir,valoir,venir,clure,ompre,vivre,baver,biser,durer,paver,viser,gener,haler,jurer,lever,laver,mener,mater,miser,murer,noyer,gérer,prier,tenir¦2yaient:fuir,voir¦3saient:taire,coudre,faire¦2gnaient:iendre¦1uvaient:boire¦3vaient:crire¦2saient:dire,lire,uire¦3laient:moudre¦2lvaient:soudre¦5ssaient:barrir,mollir¦4yaient:revoir¦4ssaient:vomir,jouir¦6ssaient:grossir¦3êtaient:arreter¦1isaient:gésir¦6yaient:pourvoir¦3issaient:croître¦2issaient:paître,naître¦4issaient:repaître¦3yaient:croire,braire¦5aient:aborder,baigner,baisser,dresser,emmener,flatter,glisser,grogner,guetter,laisser¦6aient:accorder,froisser"
    }
  },
  "pastParticiple": {
    "prt": {
      "fwd": "2:vir,uir¦3:aturer,urire¦4:échir¦is:erir,ettre,eoir¦u:aître,oire,aitre,avoir¦égé:eger¦éé:eer¦:turber¦éféré:eferer¦échi:echir¦éparti:epartir¦1u:hoir,loître,cre,pre,lire,loir,laire¦1su:stre¦2is:quérir¦2u:atre",
      "both": "1:ïr,nturer¦2:ieillir,bir,éir,cir,mir,pir,dir,gir,lir¦3:ahir,roir,grir,stir,rnir,unir,âtir,atir,isir,nnir,rrir,ttir,inir,ntir,drir,utir¦4:ansir,uffire,aurir,abattre,rtrir,ossir,xclure,hérir,nchir,ertir,mbrir,ortir¦5:éussir,aîchir,leurir,richir,planir¦5u:ébattre,mbattre¦4u:vendre,cendre,tendre,pendre,fendre¦4s:assir,ssoudre¦4t:onfire,bsoudre¦3lu:ésoudre¦3u:andre,revoir,ondre,ourir¦3û:ecroître¦3i:uivre¦3t:faire,raire,énir¦2u:évoir,rdre,utre,êtir,rvoir,enir¦2t:rire,dire,uire,indre¦2s:cire¦2êté:rreter¦2tu:âtre¦1écu:vivre¦1ert:frir,vrir¦1u:mouvoir¦1s:ore¦1is:rendre¦ê:etir¦uicidé:e suicider¦éressé:eresser¦écié:ecier¦çu:cevoir¦é:er",
      "rev": "e souvenir:ouvenu¦ivre:écu¦1ettre:mis¦1iller:b¦1dre:usu,nt¦1oître:rû¦1re:du¦1urir:ort¦1turber:r¦1eferer:référé¦1oir:vu¦1udre:olu¦2oître:cru¦2aître:aru,nnu¦2eger:siégé¦2re:ncu,ait,lus,mpu¦2ir:éru¦2oir:alu¦2ire:elu¦2eoir:rsis¦2tre:issu¦2r:ni¦3re:attu,rui,clu¦3r:rvi,eui,avi,oui,éri,évi¦3oir:échu,allu¦3érir:nquis,equis¦4r:ouvi,auvi,ngui,efui¦4re:mbatu,ouri¦4oir:voulu¦5rer:rbatu",
      "ex": "2:rire¦3:babiller,luire,unir,fuir,huir¦4:bruire,périr¦5:guérir,partir,tartir¦6:conclure,fléchir¦7:départir,impartir¦8:infléchir¦eu:avoir¦été:être¦abstenu:s'abstenir¦adonné:s'adonner¦amariné:s'amariner¦écroulé:s'écrouler¦efforcé:s'efforcer¦enfui:s'enfuir¦enquis:s'enquérir¦envolé:s'envoler¦évadé:s'évader¦ingénié:s'ingénier¦contrebalancé:se contrebalancer¦désertifié:se désertifier¦méfié:se méfier¦récrié:se récrier¦5u:abattre¦4u:accroître,battre,décroître,fendre,ficher,pendre,rendre,vendre,vouloir¦3su:coudre¦2û:croître¦1û:devoir,mouvoir¦2t:dire,uire¦3t:faire,iendre,raire¦3u:férir,issir,revoir,échoir,paraitre,repaître¦1éré:gerer¦5s:inclure,reclure¦1u:lire,taire,voir,boire,paître,savoir¦3lu:moudre¦2rt:mourir¦1é:naître¦2is:quérir¦1ouvenu:se souvenir¦2lu:soudre¦1écu:vivre¦4is:acquerir¦3is:asseoir¦2u:choir,cloître,croire,élire,plaire¦2éé:creer¦1is:mettre,seoir¦4échi:réflechir¦1éparti:repartir"
    }
  },
  "presentTense": {
    "je": {
      "fwd": "3:tter,êter,frer¦4:eller,ièger,fèrer,uvrer¦èce:ecer,écer¦èse:eser,éser¦is:uïr,ître¦ois:eoir¦eux:ouloir¦s:vre¦ène:ener,éner¦échis:echir¦iers:erir¦ète:éter¦èle:éler¦ème:emer,émer¦1ux:aloir¦1s:uillir,ire,ure,itre¦1is:aïr,avoir¦1ère:ferer¦2s:uir,ormir,outre,dir¦2e:vrir,frir¦2iers:quérir¦3s:soir,elir¦3le:peler¦3te:ueter¦4s:échir",
      "both": "2:fer,ker,éer,wer,zer,xer,ier,ber¦3:pser,omer,êler,nler,yder,ruer,icer,lper,îmer,muer,cler,over,ôner,oner,gmer,duer,âter,pher,aner,tuer,iler,lter,uder,lser,êver,lmer,mper,cuer,amer,ûler,ater,uner,îner,rver,luer,ûter,nuer,crer,imer,ager,uper,uger,oser,umer,user,pper,rger,rmer,smer,orer,ider,rper,fler,oler,iter,arer,ncer,pler,aver,ayer,sser,drer,aper,gter,buer,iper,nser,iger,cter,aler,rcer,aser,ader,nner,ouer,iser,ster,mmer,irer,iver,iner,uler,oter,oder,pter,bler,oger,uver,nder,rler,rrer,rder,nter,rser,uter,oper,rner,rter,nger,acer,urer¦4:utrer,itrer,ogner,ibrer,ngler,âcher,aquer,ôcher,strer,lâmer,uquer,rgner,ltrer,oquer,ntrer,lyser,iller,nquer,rguer,igrer,seyer,iguer,oguer,aguer,squer,igner,rquer,ucher,nguer,iquer,acher,ocher,agner,ncher,rcher,icher¦5:rêcher,ulquer,coller,otyper,livrer,trôler,taller,baller¦5s:fermir,revoir,aîchir,mortir,richir,aigrir,tentir,esservir,ombrir,essortir¦5le:ordeler¦5te:illeter,elleter¦5e:saillir¦4s:antir,aroir,patir,rahir,vahir,choir,ollir,arnir,urnir,nchir,ertir,pandre,rvoir,évoir¦4le:rceler,iceler,ateler,tteler¦3s:alir,ttir,anir,âtir,ourir,ôtir,ondre,rrir,unir,stir,avir,blir,omir,sentir,nnir,drir,uvir,plir,utir,olir,endre,soudre,inir,pentir,énir¦3te:feter,jeter¦3le:veler¦2èle:eceler,nteler,éceler,odeler,rteler¦2s:éir,bir,rdre,cir,pir,gir,indre,âtre,êtir,sir¦2us:faillir¦2ête:rreter¦2ète:aleter,ureter¦1èle:geler¦1vais:-aller¦1eus:mouvoir¦1s:cre,pre,ttre,ore¦1ie:uyer,oyer¦1ète:heter¦èque:équer¦ètre:étrer¦èpe:eper¦ègne:égner¦ègue:éguer¦ègre:égrer¦ède:éder¦ève:ever¦çois:cevoir¦iens:enir¦ère:érer¦ège:éger¦èche:écher¦èbre:ébrer",
      "rev": "voir:i¦evrer:èvre¦égler:ègle¦ourir:eurs¦1ecer:mèce¦1écer:ièce¦1tre:îs¦1re:ds¦1ener:sène,mène,rène¦1ouloir:veux¦1éter:pète,iète¦1éler:vèle,rèle¦1éner:iène¦1émer:rème¦1éser:lèse,rèse¦2ecer:épèce¦2r:tis,nis,ye¦2tir:ars¦2loir:vaux¦2eoir:rsois¦2re:lus,fis¦2ître:nais,lois¦2erer:sfère¦2éter:plète,flète,crète¦3r:hois,ndis,llis,rdis,ene,ouis,tris,idis,êne,fuis,éris,euis,spe,âne,évis¦3mir:dors¦3re:fais,rais,duis,cris,lais,ruis,édis,edis¦3ître:crois¦3vre:evis¦3er:lette¦3echir:éfléchis¦3éter:rprète¦3érir:equiers¦4r:otte,ssois,lgue,evois,atte,nguis,utte,itte,êche,auris,ufre,bête,ugue,mbre,velis,ûche¦4re:oncis,ouris¦4er:ppelle¦4ir:ouvre,uffre¦4vre:rsuis,urvis¦5r:servis,leuris,siège,euvre,quête,iffre,laudis¦5ir:ueille¦5re:terdis¦5er:iquette",
      "ex": "3:oser,user,huer,muer,nuer,ayer,tuer,ôter¦4:gener,gêner,fêter¦5:livrer,coller,pêcher,jasper,flâner,bûcher,prêter¦6:sombrer,guetter,sceller¦7:empêcher,dépêcher,fouetter,préfèrer,exceller¦8:divulguer,conjuguer,regretter¦9:promulguer¦10:interpeller¦suis:être¦vais:aller¦m'abstiens:s'abstenir¦me souviens:se souvenir¦m'enfuis:s'enfuir¦m'ingénie:s'ingénier¦m'efforce:s'efforcer¦me désertifie:se désertifier¦me récrie:se récrier¦m'adonne:s'adonner¦me contrebalance:se contrebalancer¦m'écroule:s'écrouler¦m'enquiers:s'enquérir¦me suicide:se suicider¦me méfie:se méfier¦m'évade:s'évader¦m'envole:s'envoler¦m'amarine:s'amariner¦1i:avoir¦1èle:geler,peler¦3te:jeter¦1èvre:sevrer¦1ie:oyer¦1ègle:régler¦4e:montrer,ouvrir,offrir¦7s:asservir,impartir,assortir,embellir,répartir,vieillir,meurtrir,ralentir¦4s:choir,croître,coudre,moudre,périr,sévir,croire,relire¦1is:gésir,ouïr¦3s:mentir,partir,sortir,servir,voir,iendre,soudre,sentir,unir,huir,bouillir,dormir,fuir,taire,boire,crire,faire,foutre,luire,nuire,cuire,élire¦1eurs:mourir¦1eus:mouvoir¦1eux:pouvoir,vouloir¦6e:cueillir¦1ois:devoir¦2iers:quérir¦5s:revoir,vernir,départir,guérir,clatir,chérir,saurir,repartir,tartir,maudire,paraitre,baudir¦5te:voleter¦6s:fleurir,fléchir¦2ux:faillir,valoir¦8e:accueillir,recueillir¦11s:enorgueillir¦1èse:peser,léser¦2is:haïr,savoir,paître,naître¦4is:repaître¦2s:dire,lire,rire,uire,vivre¦1ène:mener,géner¦4iers:acquerir¦1ème:semer¦2ène:gléner¦5iers:conquérir¦1ète:péter¦6le:chapeler¦7iers:reconquérir¦8s:infléchir¦4le:épeler"
    },
    "tu": {
      "fwd": "èces:ecer¦èses:eser,éser¦is:uïr,ître¦ois:eoir¦eux:ouloir¦s:vre¦iers:erir¦ètes:éter¦èles:éler¦èmes:emer¦ènes:éner¦1ux:aloir¦1s:uillir,ire,ure,itre¦1is:aïr,avoir¦1ères:ferer¦2s:ormir,outre¦2es:vrir,frir¦2échis:flechir¦2iers:quérir¦3tes:ueter",
      "both": "5les:hapeler¦5s:esservir,essortir¦5es:saillir¦4les:rdeler,ppeler,rceler,tteler¦4s:epartir,pandre¦4tes:oleter,lleter¦3tes:feter,jeter¦3les:veler¦3s:sentir,ondre,endre,soudre,ourir,pentir¦2èles:odeler,eceler,nteler,éceler,rteler¦2us:faillir¦2êtes:rreter¦2ètes:ureter¦2s:rdre,indre,âtre,êtir¦2èces:piécer¦1ènes:rener,mener,sener¦1èles:geler¦1vas:-aller¦1eus:mouvoir¦1s:cre,pre,ttre,ore¦1ies:uyer,oyer¦1ètes:heter¦èques:équer¦ètres:étrer¦èpes:eper¦ègnes:égner¦ègues:éguer¦ègres:égrer¦èdes:éder¦èves:ever¦çois:cevoir¦iens:enir¦ères:érer¦èges:éger¦èches:écher¦èbres:ébrer¦s:r",
      "rev": "evrer:èvres¦égler:ègles¦ourir:eurs¦1ecer:mèces¦1tre:îs¦1re:ds¦1ouloir:veux¦1éter:pètes,iètes¦1éler:vèles,rèles¦1éner:iènes¦1émer:rèmes¦1éser:lèses,rèses¦2ecer:épèces¦2tir:ars¦2loir:vaux¦2eoir:rsois¦2re:lus,fis¦2ître:nais,lois¦2eter:alètes¦2erer:sfères¦2éter:plètes,flètes,crètes¦3mir:dors¦3re:fais,rais,duis,cris,lais,ruis,édis,edis¦3ître:crois¦3er:telles¦3vre:evis¦3echir:éfléchis¦3éter:rprètes¦3érir:nquiers,equiers¦4re:oncis¦4ir:ouvres¦4tre:arais¦4vre:rsuis,urvis¦4er:quettes¦5ir:ueilles,ouffres¦5re:terdis",
      "ex": "es:être¦vas:aller¦t'abstiens:s'abstenir¦te souviens:se souvenir¦t'enfuis:s'enfuir¦t'ingénies:s'ingénier¦t'efforces:s'efforcer¦te désertifies:se désertifier¦te récries:se récrier¦t'adonnes:s'adonner¦te contrebalances:se contrebalancer¦t'écroules:s'écrouler¦t'enquiers:s'enquérir¦te suicides:se suicider¦te méfies:se méfier¦t'évades:s'évader¦t'envoles:s'envoler¦t'amarines:s'amariner¦1s:avoir¦1èles:geler,peler¦3tes:jeter¦1èvres:sevrer¦1ies:oyer¦1ègles:régler¦4es:montrer,ouvrir,offrir¦1is:gésir,ouïr¦3s:mentir,partir,sortir,servir,iendre,soudre,sentir,bouillir,dormir,taire,boire,crire,faire,foutre,luire,suivre,nuire,cuire,élire¦1eurs:mourir¦1eus:mouvoir¦1eux:pouvoir,vouloir¦6es:cueillir¦1ois:devoir¦2iers:quérir¦4s:croître,coudre,moudre,croire,relire¦5les:bateler,ficeler¦3ètes:haleter¦1ènes:mener,géner¦5s:départir,maudire,sourire¦2ux:faillir,valoir¦8es:accueillir,recueillir¦3èmes:écrémer¦4les:épeler¦1èses:peser,léser¦2is:haïr,savoir,paître,naître¦4is:repaître¦2s:dire,lire,rire,uire,vivre¦4iers:acquerir¦1èmes:semer¦2ènes:gléner¦1ètes:péter"
    },
    "il": {
      "fwd": "1:ttre¦2:utre¦3:tter,èger,êter,frer¦4:eller,uvrer¦èce:ecer,écer¦èse:eser,éser¦eut:ouvoir,ouloir¦oit:eoir¦t:vre¦ène:ener,éner¦échit:echir¦iert:erir¦ît:itre¦ète:éter¦èle:éler¦ème:emer,émer¦1ut:aloir¦1t:uillir,ire,ure¦1it:aïr,avoir¦1ère:ferer¦2t:uir,ormir,dir¦2e:vrir,frir¦3t:soir,roir,elir¦3te:ueter¦3le:peler¦4t:échir",
      "both": "1:cre¦2:fer,ker,éer,wer,zer,rdre,xer,ier,ître,âtre,êtir,ber¦3:pser,êler,pher,nler,yder,ruer,icer,lper,îmer,muer,sper,cler,over,ôner,oner,gmer,duer,âter,pler,iler,lter,uder,iper,aser,lmer,cuer,ûler,uner,îner,rver,tuer,ûter,bler,nuer,crer,imer,ater,uper,ouer,uger,luer,lser,umer,aler,mper,fler,pper,rmer,iger,rper,oder,oler,iter,oser,mmer,ondre,ider,nser,ager,aner,pter,sser,drer,aper,orer,rcer,rger,cter,iner,aver,ader,ayer,ncer,buer,iser,ster,irer,iver,nner,uler,oter,amer,arer,user,oger,uver,nder,endre,rler,rrer,rder,nter,rser,uter,oper,rner,rter,nger,acer,urer¦4:oomer,lyser,mbrer,lquer,lguer,ôcher,iguer,uquer,âcher,ibrer,strer,oquer,iller,êcher,rôler,ntrer,ucher,nquer,ivrer,ngler,igrer,ogner,seyer,asmer,aquer,squer,sentir,igner,rquer,igter,nguer,iquer,aguer,acher,ocher,agner,pandre,ncher,rcher,icher¦5:pitrer,juguer,coller,epartir,erguer,argner,arguer,taller,iltrer,baller,epentir¦5le:ordeler,arceler¦5t:mortir,mpatir,lentir,aigrir,leurir,tentir,esservir,ombrir¦5e:saillir¦4t:ermir,antir,aurir,ichir,ollir,ennir,nchir,ellir,annir,ertir,rvoir,évoir¦4te:lleter,oleter¦4le:tteler¦4it:ccroître¦3t:alir,ttir,anir,âtir,ahir,soudre,unir,ôtir,stir,blir,omir,rnir,ourir,rrir,drir,uvir,plir,utir,olir,inir,énir¦3te:feter,jeter¦3le:veler¦2èle:eceler,nteler,éceler,odeler,rteler¦2t:éir,bir,cir,pir,gir,indre,sir¦2ît|plait:laire¦2et:choir¦2ête:rreter¦2ète:aleter,ureter¦1èle:geler¦1va:-aller¦1t:pre,ore¦1iert:uérir¦1ie:uyer,oyer¦1ète:heter¦èque:équer¦ètre:étrer¦èpe:eper¦ègne:égner¦ègue:éguer¦ègre:égrer¦ède:éder¦ève:ever¦çoit:cevoir¦ient:enir¦ère:érer¦ège:éger¦èche:écher¦èbre:ébrer",
      "rev": "evrer:èvre¦égler:ègle¦ourir:eurt¦1ecer:mèce¦1écer:ièce¦1ouvoir:meut¦1re:d¦1ener:sène,mène,rène¦1ouloir:veut¦1éter:pète,iète¦1éler:vèle,rèle¦1éner:iène¦1émer:rème¦1éser:lèse,rèse¦2ecer:épèce¦2r:tit,nit,ye¦2loir:vaut¦2eoir:rsoit¦2re:lut,fit¦2tre:at¦2erer:sfère¦2itre:raît¦2éter:plète,flète,crète¦3r:hoit,ndit,rdit,llit,ene,avit,ouit,trit,idit,êve,âme,êne,fuit,érit,euit,voit,âne,évit¦3ir:art¦3mir:dort¦3re:fait,rait,duit,crit,ruit,édit,edit¦3er:telle¦3tre:met¦3vre:evit,suit¦3echir:éfléchit¦3illir:éfaut¦3éter:rprète¦4r:otte,ssoit,rgue,ogue,atte,nguit,itte,uête,aroit,îchit,velit,ûche,utre¦4ir:sort,ouvre,uffre¦4re:oncit,ourit¦4er:ppelle,apelle,quette¦4vre:urvit¦5r:servit,siège,euvre,rette,otype,iffre,mbête,outte¦5ir:ueille¦5re:terdit",
      "ex": "1:avoir¦3:oser,user,huer,muer,nuer,ayer,tuer,ôter,mettre¦4:mentir,partir,sortir,coudre,moudre,gener,sentir,rêver,gêner,foutre,fêter¦5:arguer,voguer,coller,blâmer,flâner,bûcher,outrer,lutter,prêter¦6:guetter,sceller,soufrer¦7:ressortir,préfèrer,fouetter,exceller¦8:dialoguer¦10:stéréotyper,interpeller¦est:être¦va:aller¦1èle:geler,peler¦3te:jeter¦1èvre:sevrer¦1ie:oyer¦1ègle:régler¦4e:montrer,ouvrir,offrir¦7t:asservir,impartir,assortir,répartir,vieillir,meurtrir,départir¦4t:choir,périr,ravir,sévir,croire,relire¦1ît:gésir¦1eurt:mourir¦1it:ouïr¦6e:cueillir¦1oit:devoir¦3t:servir,voir,iendre,soudre,unir,huir,bouillir,dormir,fuir,taire,boire,crire,faire,luire,suivre,nuire,cuire,élire¦5le:bateler,ficeler¦5t:revoir,gravir,honnir,guérir,clatir,chérir,tartir,maudire,baudir¦4ut:défaillir¦2ut:faillir,valoir¦8e:accueillir,recueillir¦9t:rafraîchir¦8t:entrevoir,applaudir,infléchir¦11t:enorgueillir¦1èse:peser,léser¦1eut:mouvoir,pouvoir,vouloir¦2it:haïr,savoir¦2t:dire,lire,rire,uire,vivre¦1ène:mener,géner¦4iert:acquerir¦1ème:semer¦2ène:gléner¦1ète:péter¦6t:fléchir¦4le:épeler"
    },
    "nous": {
      "fwd": "ons:er¦isons:ésir¦oyons:eoir¦issons:ître¦quons:cre¦égeons:èger¦érons:èrer,erir¦échissons:echir¦1sons:ore¦1gnons:indre¦1ons:ure,pre,vre¦1érons:ferer¦1ssons:itre¦2ons:enir,urir,êtir,vrir,ttre,utre,rdre,frir¦2ns:loir¦2yons:roire,raire¦2vons:rire¦2sons:lire¦3ns:uvoir,avoir¦3ons:ormir,rendre,ondre¦3yons:rvoir¦3ssons:udire,roir¦4ons:uillir,aillir,sentir,quérir,cendre¦4ssons:échir",
      "both": "5ssons:planir,mortir,mpatir,lentir,anguir,tentir,bellir,brutir¦5ons:epartir¦4ssons:ermir,antir,aurir,ansir,ichir,ussir,igrir,ossir,eurir,ertir,nchir,outir¦4ons:fendre,vendre,pendre,tendre,pandre,pentir¦4yons:échoir¦4ns:cevoir¦4sons:oncire¦3ssons:évir,elir,rrir,ttir,euir,ouir,âtir,ahir,blir,trir,unir,stir,avir,omir,rnir,nnir,drir,uvir,brir,plir,olir,inir,énir,isir¦3sons:edire,édire,faire,laire,rdire¦3ons:urire,uger,rger,nger,ager,iger,oger,éger¦3yons:ssoir,évoir¦2yons:fuir¦2ssons:éir,bir,cir,pir,gir,dir¦2sons:uire,fire¦2lvons:soudre¦2tons:âtre¦1ssons:ïr¦çons:cer",
      "rev": "udre:lvons¦1er:lons,rons,hons,uons,pons,bons,mons,xons,zons,wons,éons,kons,fons¦1ndre:egnons¦2er:etons,esons,édons,rdons,utons,rsons,ctons,inons,nnons,itons,usons,odons,stons,rnons,osons,cions,sions,otons,adons,asons,nsons,gtons,fions,lions,anons,avons,hions,idons,nions,ptons,atons,eyons,lsons,ovons,dions,ûtons,ltons,înons,étons,unons,gions,pions,êvons,udons,vions,énons,ésons,tions,onons,ônons,kions,ysons,ydons,ânons,âtons,psons¦2r:vissons,uissons,tissons,rissons,nissons¦2eoir:rsoyons¦2ître:naissons,loissons¦2cre:inquons¦2ndre:eignons¦2èger:siégeons¦2eter:rrêtons¦2erer:sférons¦3er:ortons,ottons,ontons,boyons,euvons,agnons,hevons,senons,risons,layons,tisons,essons,assons,untons,antons,nisons,gayons,intons,ussons,lisons,toyons,revons,ognons,urtons,uttons,arions,tivons,sayons,levons,ittons,menons,misons,visons,rgnons,ossons,égnons,érions,oisons,doyons,nuyons,bêtons,suyons,orions,trions,indons,hisons,éisons¦3ir:venons,vêtons,tenons,evoyons¦3re:closons,erdons,cluons,crivons¦3ître:croissons¦3ndre:joignons,laignons,raignons¦3r:llissons,alissons¦3èrer:référons¦3echir:éfléchissons¦3tre:raissons¦3ire:trayons¦4er:nvoyons,ppuyons,bondons,dentons,oprions,rrivons,mandons,ployons,ientons,rouvons,lattons,droyons,landons,rattons,uettons,ventons,mentons,nnayons,troyons,écisons,lignons,cartons,quêtons,signons,hendons,paisons,lertons,érivons,gentons,xondons,puisons,chivons,avivons,quivons,condons,guisons¦4ir:sortons,dormons,courons,ouvrons,partons,uffrons¦4re:mettons,fondons,battons,suivons,rvivons,pondons¦4dre:prenons¦4r:aroissons,îchissons¦5er:ttentons,bsentons,mbrayons,seignons,bservons,ésentons,éservons,moignons,loignons,baissons,ntentons,grettons,ulissons,enouvons,nicisons,égrenons¦5ir:évalons,ueillons,mouvons,saillons,sservons,voulons,faillons,nquérons,equérons¦5re:rrompons",
      "ex": "sommes:être¦nous abstenons:s'abstenir¦nous souvenons:se souvenir¦nous enfuyons:s'enfuir¦nous ingénions:s'ingénier¦nous efforçons:s'efforcer¦nous désertifions:se désertifier¦nous récrions:se récrier¦nous adonnons:s'adonner¦nous contrebalançons:se contrebalancer¦nous écroulons:s'écrouler¦nous enquérons:s'enquérir¦nous suicidons:se suicider¦nous méfions:se méfier¦nous évadons:s'évader¦nous envolons:s'envoler¦nous amarinons:s'amariner¦3ns:avoir,choir¦4ons:montrer,mentir,partir,sortir,quérir,servir,pendre,rendre,vendre,fendre,sentir,choyer,brayer,mourir,courir,dormir,ouvrir,battre,prendre,foutre,mettre,suivre,bander,ployer,pondre,rompre,visser,fonder,frayer,mander,mordre,offrir,broyer,sauver,signer,prêter,tenter,priver,grener,renter,nerver,farter,ligner,puiser,sonder,tisser,lisser,tordre,hisser¦7ssons:asservir,impartir,assortir,répartir,vieillir¦3ssons:huir,unir¦7ons:ressortir,desservir,resservir,descendre,encaisser,ressentir,fourvoyer,conserver,consentir¦6ons:cueillir,départir,bouillir,effrayer,froisser¦4ns:devoir,savoir,valoir¦2yons:fuir,voir¦3sons:taire,coudre,faire,élire¦2gnons:iendre,aindre¦1uvons:boire¦2sons:dire,lire,uire¦3lons:moudre¦2ons:rire,oyer,oser,user,fier,lier,nier,ayer,ôter¦2lvons:soudre¦4yons:revoir¦5ssons:mollir,guérir,clatir,chérir,tartir,maudire¦3êtons:arreter¦4ssons:rôtir,salir,périr¦8ons:accueillir,recueillir,fréquenter¦9ssons:rafraîchir¦7yons:entrevoir¦11ssons:enorgueillir¦5ons:daigner,baigner,baisser,revivre,glisser,gronder,inonder,laisser,faillir,soigner,amender,saigner¦1isons:gésir¦5ns:mouvoir,pouvoir,vouloir¦3ons:vêtir,venir,clure,ompre,vivre,bayer,biser,payer,viser,gener,lever,mener,miser,noyer,prier,rayer,tenir,river,crier,fêter,trier,gêner¦6yons:pourvoir¦3issons:croître¦2issons:paître,naître¦4issons:repaître¦3vons:crire¦3yons:croire,traire¦3gnons:joindre¦4érons:acquerir¦4sons:relire¦6ssons:fléchir¦9ons:redescendre,transcender¦8ssons:infléchir"
    },
    "vous": {
      "fwd": "isez:ésir¦oyez:eoir¦issez:ître¦quez:cre¦égez:èger¦érez:èrer,erir¦échissez:echir¦1ez:loir,ure,pre,vre¦1sez:ore¦1gnez:indre¦1érez:ferer¦1ssez:itre¦2ez:enir,urir,uvoir,êtir,vrir,avoir,ttre,utre,rdre,frir¦2yez:roire,hoir,raire¦2vez:rire¦2sez:lire¦3ez:ormir,rendre,ondre¦3yez:rvoir¦3ssez:udire¦4ez:uillir,aillir,sentir,quérir,cendre¦4ssez:échir",
      "both": "5sez:tredire¦5ssez:mortir,lentir,anguir,tentir,bellir¦5ez:epartir¦4ssez:ermir,lanir,antir,aurir,ichir,ussir,rtrir,ossir,eurir,ertir,nchir,mbrir¦4ez:fendre,vendre,pendre,tendre,pandre,pentir¦4sez:oncire¦3ssez:évir,elir,rrir,ttir,uvir,euir,nsir,atir,âtir,ahir,blir,unir,grir,ouir,stir,avir,omir,rnir,nnir,drir,plir,utir,olir,inir,énir,isir¦3sez:édire,laire¦3tes:faire,rdire¦3ez:urire,cevoir¦3yez:ssoir,évoir¦2yez:fuir¦2ssez:éir,bir,gir,cir,pir,dir¦2sez:uire,fire¦2lvez:soudre¦2tez:âtre¦1ssez:ïr¦z:r",
      "rev": "udre:lvez¦1ndre:egnez¦1re:ites¦2r:vissez,uissez,tissez,rissez,nissez¦2eoir:rsoyez¦2ître:naissez,loissez¦2cre:inquez¦2èger:siégez¦2erer:sférez¦3ir:venez,vêtez,tenez,evoyez,choyez¦3re:closez,erdez,crivez,elisez¦3ître:croissez¦3ndre:reignez,joignez,laignez,peignez,raignez,teignez¦3r:llisez,alissez,llissez¦3èrer:référez¦3erir:cquérez¦3ire:trayez¦4oir:évalez,mouvez¦4ir:dormez,courez,ouvrez,partez,uffrez¦4re:ncluez,mettez,evivez,xcluez,fondez,pondez,suivez,battez¦4dre:prenez¦4tre:araissez¦4r:aroissez,îchissez¦5ir:ssortez,ueillez,saillez,sservez,ssentez,faillez,nsentez,nquérez,equérez¦5re:rrompez,urvivez",
      "ex": "vous abstenez:s'abstenir¦vous souvenez:se souvenir¦vous enfuyez:s'enfuir¦vous ingéniez:s'ingénier¦vous efforcez:s'efforcer¦vous désertifiez:se désertifier¦vous récriez:se récrier¦vous adonnez:s'adonner¦vous contrebalancez:se contrebalancer¦vous écroulez:s'écrouler¦vous enquérez:s'enquérir¦vous suicidez:se suicider¦vous méfiez:se méfier¦vous évadez:s'évader¦vous envolez:s'envoler¦vous amarinez:s'amariner¦2es:être¦2ez:avoir,rire¦4ez:montrer,mentir,partir,sortir,quérir,servir,pendre,rendre,vendre,fendre,sentir,mourir,mouvoir,pouvoir,courir,dormir,ouvrir,vouloir,battre,prendre,foutre,mettre,suivre,pondre,rompre,mordre,offrir,tordre¦7ssez:asservir,impartir,assortir,répartir¦3ssez:huir,unir¦7ez:ressortir,desservir,resservir,descendre¦6ez:cueillir,départir,bouillir,revouloir¦3ez:devoir,vêtir,savoir,valoir,venir,clure,ompre,vivre,tenir¦2yez:fuir,voir¦3sez:taire,coudre,élire¦2gnez:iendre,aindre¦1uvez:boire¦2tes:dire¦3tes:faire¦2sez:lire,uire¦3lez:moudre¦2lvez:soudre¦4yez:revoir¦7sez:vieillir¦5ssez:mollir,guérir,paroir,chérir,tartir,maudire¦3êtez:arreter¦4ssez:rôtir,salir,périr¦8ez:accueillir,recueillir¦9ssez:rafraîchir¦4tes:redire¦7yez:entrevoir¦11ssez:enorgueillir¦1isez:gésir¦6yez:pourvoir¦3issez:croître¦2issez:paître,naître¦4issez:repaître¦3vez:crire¦3yez:croire,traire¦3gnez:joindre,peindre,feindre,geindre¦4échissez:réflechir¦5ez:faillir¦6ssez:fléchir¦9ez:redescendre¦8ssez:infléchir"
    },
    "ils": {
      "fwd": "ècent:ecer,écer¦èsent:eser,éser¦euvent:ouvoir¦oient:eoir¦eulent:ouloir¦issent:ître¦quent:cre¦ènent:ener,éner¦échissent:echir¦ièrent:erir¦ètent:éter¦èlent:éler¦èment:emer,émer¦1ient:oyer,uyer¦1sent:ore¦1gnent:indre¦1ent:ure,pre,vre¦1èrent:ferer¦1ssent:itre¦2ent:aloir,êtir,vrir,avoir,ttre,utre,rdre,frir¦2nt:ier¦2vent:rire¦2sent:lire¦3ent:soir,ourir,ormir,roire,ondre¦3ssent:udire¦3nt:nder,uver,iver,iser,nner,sser,luer,tter,rver,èger,êter,mper,frer¦3tent:ueter¦3lent:peler¦4ent:uillir,rvoir,aillir,sentir,cendre¦4nt:igner,eller,nquer,iller,uvrer¦5nt:éfèrer",
      "both": "5ssent:fermir,mortir,richir,aigrir,leurir,tentir,vertir,ombrir¦5nt:angler,asquer,argner,taller,iltrer,isquer,baller¦5ent:revoir,epartir,epentir¦5lent:arceler¦4nt:utrer,ûcher,itrer,lyser,mbrer,ulper,lquer,oller,ôcher,typer,uquer,âcher,ibrer,strer,rquer,oquer,êcher,rguer,ivrer,iguer,igrer,ogner,asmer,oguer,aquer,ntrer,ucher,aguer,lguer,nguer,iquer,acher,ocher,agner,ncher,rcher,icher¦4lent:rdeler,iceler,tteler¦4ssent:îchir,hérir,ollir,antir,nchir¦4ent:fendre,choir,ourire,vendre,pendre,tendre,pandre,évoir¦4tent:lleter¦4sent:oncire¦3nt:pser,êler,oner,pher,nler,yder,ruer,icer,uger,îmer,muer,sper,cler,ôner,gmer,duer,âter,êner,lter,uder,iler,pler,êver,lmer,cuer,amer,ûler,uper,uner,rger,îner,arer,tuer,ôler,nuer,crer,imer,aver,over,lser,umer,eyer,ager,pper,ater,rmer,aner,orer,ider,rper,fler,oler,iter,ncer,iper,nser,user,ayer,drer,aper,gter,buer,oser,iger,cter,aler,rcer,aser,ader,ouer,ster,mmer,irer,iner,uler,oter,oder,pter,bler,oger,rler,rrer,rder,nter,rser,uter,oper,rner,rter,nger,acer,urer¦3ssent:elir,alir,rrir,ttir,anir,euir,âtir,atir,ahir,blir,trir,guir,ouir,unir,stir,avir,omir,rnir,nnir,drir,uvir,plir,utir,olir,inir,énir¦3sent:edire,édire,laire,rdire¦3tent:feter,jeter¦3ent:fuir,raire¦3lent:veler¦3nent:rendre¦2èlent:eceler,nteler,éceler,odeler,rteler¦2ssent:éir,bir,cir,pir,gir,dir,sir¦2nt:fer,ker,éer,wer,zer,xer,ber¦2êtent:rreter¦2ètent:aleter,ureter¦2sent:uire,fire¦2lvent:soudre¦2tent:âtre¦1èlent:geler¦1vont:-aller¦1ont:faire¦1ièrent:uérir¦1ssent:ïr¦1ètent:heter¦èquent:équer¦ètrent:étrer¦èpent:eper¦ègnent:égner¦èguent:éguer¦ègrent:égrer¦èdent:éder¦èvent:ever¦çoivent:cevoir¦iennent:enir¦èrent:érer¦ègent:éger¦èchent:écher¦èbrent:ébrer",
      "rev": "evrer:èvrent¦égler:èglent¦udre:lvent¦1ecer:mècent¦1écer:iècent¦1ouvoir:meuvent¦1ndre:egnent¦1ener:sènent,mènent,rènent¦1ouloir:veulent¦1éter:pètent,iètent¦1éler:vèlent,rèlent¦1éner:iènent,lènent¦1émer:rèment¦1éser:lèsent,rèsent¦2ecer:épècent¦2yer:puient,boient,loient,toient,doient,nuient,suient¦2r:vissent,uissent,tissent,yent,rissent,nissent¦2eoir:rsoient¦2ître:naissent,loissent¦2cre:inquent¦2ndre:eignent¦2erer:sfèrent¦2éter:plètent,flètent,prètent,crètent¦3yer:nvoient,droient,troient¦3ir:vêtent¦3re:closent,erdent,crivent,cluent,elisent¦3ître:croissent¦3r:cient,sient,tient,llissent,fient,lient,hient,nient,llisent,enent,dient,ûtent,gient,âment,vient,kient,ânent,oment¦3er:tellent,lettent¦3ndre:joignent,raignent¦3echir:éfléchissent¦3tre:raissent¦4r:essent,ottent,ssoient,onnent,ouvent,tisent,visent,assent,annent,lluent,ussent,arient,risent,impent,fluent,nglent,uttent,aluent,ittent,misent,tivent,nisent,oluent,ossent,aroissent,oisent,orient,ampent,ufrent,bêtent,iluent,uguent,crient,hivent,trient,indent,hisent,éisent¦4oir:évalent¦4ir:dorment,courent,ouvrent,partent,uffrent¦4re:mettent,evivent,fondent,battent,pondent¦4er:ppellent,quettent¦5ir:ssortent,ueillent,saillent,sservent,ssentent,faillent¦5r:bondent,oprient,mandent,ilisent,alisent,landent,rattent,nondent,anquent,siègent,lignent,écisent,euvrent,billent,quêtent,rettent,signent,hendent,paisent,érivent,icisent,mendent,pillent,iffrent,élisent,uillent,cillent,avivent,condent,rillent,guisent¦5re:rrompent,rsuivent,urvivent¦5er:hapellent",
      "ex": "sont:être¦ont:avoir¦vont:aller¦1èlent:geler,peler¦3tent:jeter¦1èvrent:sevrer¦1ient:oyer¦1èglent:régler¦4ent:montrer,mentir,partir,sortir,servir,pendre,rendre,vendre,fendre,sentir,courir,dormir,ouvrir,battre,croire,foutre,mettre,suivre,pondre,rompre,mordre,offrir,tordre¦7ssent:asservir,impartir,assortir,embellir,répartir,ralentir¦1isent:gésir¦3ssent:huir,unir¦1eurent:mourir¦7ent:ressortir,desservir,resservir,pourvoir,descendre,consentir¦6ent:cueillir,départir,bouillir¦1oivent:devoir¦3ent:fuir,voir,vêtir,savoir,valoir,clure,ompre,vivre¦3sent:taire,coudre,élire¦2gnent:iendre,aindre¦3vent:boire,crire¦2sent:dire,lire,uire¦1ont:faire¦3lent:moudre¦2ent:rire¦2lvent:soudre¦5lent:bateler¦3nt:oser,user,huer,muer,nuer,ayer,tuer,ôter,fier,lier,nier¦5ent:revoir,faillir¦7sent:vieillir¦5tent:voleter¦4nt:gener,biser,viser,miser,prier,river,crier,fêter,trier¦6nt:jongler,daigner,arriver,baigner,baisser,flatter,glisser,gronder,guetter,laisser,soigner,veiller,tromper,sceller,exonder,épuiser,tailler,tremper,saigner¦4ssent:rôtir,périr,sévir¦5nt:goûter,coûter,blâmer,flâner,zoomer,bander,visser,fonder,mander,sauver,signer,prêter,copier,priver,sérier,nerver,ligner,puiser,pomper,sonder,tisser,lisser,piller,hisser¦8ent:accueillir,recueillir¦5ssent:guérir,paroir,saurir,tartir,maudire¦8nt:conjuguer,encaisser,conserver,préserver,enseigner,témoigner,réveiller,coulisser,distiller,détailler,temoigner,rabaisser¦6ssent:fléchir¦8ssent:infléchir¦11ssent:enorgueillir¦1èsent:peser,léser¦3ient:choyer,broyer¦1euvent:mouvoir,pouvoir¦1eulent:vouloir¦3issent:croître¦2issent:paître,naître¦4issent:repaître¦3gnent:joindre¦7nt:abreuver,fouetter,froisser,observer,préfèrer,réserver,éloigner,abaisser,éveiller,esquiver,exceller¦4gnent:plaindre¦9nt:renseigner,travailler,surveiller,conseiller¦6ient:fourvoyer¦10nt:interpeller,transcender¦1ènent:mener,géner¦2ient:noyer¦4ièrent:acquerir¦1èment:semer¦1ètent:péter¦9ent:redescendre¦4lent:épeler"
    }
  }
}