export default {
  // to be
  etre: {
    first: 'suis',
    second: 'es',
    third: 'est',
    firstPlural: 'sommes',
    secondPlural: 'êtes',
    thirdPlural: 'sont',
    part: 'été',
  },
  // to go
  aller: {
    first: 'vais',
    second: 'vas',
    third: 'va',
    firstPlural: 'allons',
    secondPlural: 'allez',
    thirdPlural: 'vont',
    part: 'allé',
  },

  // to have
  avoir: {
    first: 'ai',
    second: 'as',
    third: 'a',
    firstPlural: 'avons',
    secondPlural: 'avez',
    thirdPlural: 'ont',
    part: 'eu',
  },

  //to say, to tell
  dire: {
    first: 'dis',
    second: 'dis',
    third: 'dit',
    firstPlural: 'disons',
    secondPlural: 'dites',
    thirdPlural: 'disent',
    part: 'dit',
  },

  // to make, to do
  faire: {
    first: 'fais',
    second: 'fais',
    third: 'fait',
    firstPlural: 'faisons',
    secondPlural: 'faites',
    thirdPlural: 'font',
    part: 'fait',
  },

  // to be necessary',
  falloir: {
    third: 'faut',
    part: 'fallu',
  },
  // to be able to do
  pouvoir: {
    first: 'peux',
    second: 'peux',
    third: 'peut',
    firstPlural: 'pouvons',
    secondPlural: 'pouvez',
    thirdPlural: 'peuvent',
    part: 'pu',
  },

  // to know, to know how to
  savoir: {
    first: 'sais',
    second: 'sais',
    third: 'sait',
    firstPlural: 'savons',
    secondPlural: 'savez',
    thirdPlural: 'savent',
    part: 'su',
  },

  // to see
  voir: {
    first: 'vois',
    second: 'vois',
    third: 'voit',
    firstPlural: 'voyons',
    secondPlural: 'voyez',
    thirdPlural: 'voient',
    part: 'vu',
  },

  absoudre: {
    third: 'absout',
    firstPlural: 'absolvons',
    secondPlural: 'absolvez',
    thirdPlural: 'absolvent',
  },
  accroître: {
    first: 'accrois',
    second: 'accrois',
    firstPlural: 'accroissons',
    thirdPlural: 'accroissent',
  },
  accueillir: {
    first: 'accueille',
    second: 'accueilles',
    firstPlural: 'accueillons',
    secondPlural: 'accueillez',
  },
  acheter: {
    first: 'achète',
    second: 'achètes',
    thirdPlural: 'achètent',
  },
  acquérir: {
    firstPlural: 'acquérons',
    secondPlural: 'acquérez',
    thirdPlural: 'acquièrent',
  },
  adjoindre: {
    third: 'adjoint',
    firstPlural: 'adjoignons',
    thirdPlural: 'adjoignent',
  },
  agneler: {
    first: 'agnelle',
    second: 'agnelles',
    thirdPlural: 'agnellent',
  },
  ahurir: {
    second: 'ahuris',
    third: 'ahurit',
    thirdPlural: 'ahurissent',
  },
  aiguilleter: {
    first: 'aiguillette',
    second: 'aiguillettes',
    third: 'aiguillette',
    thirdPlural: 'aiguillettent',
  },
  amonceler: {
    first: 'amoncelle',
    second: 'amoncelles',
    third: 'amoncelle',
    thirdPlural: 'amoncellent',
  },
  amuïr: {
    second: 'amuïs',
    third: 'amuït',
    firstPlural: 'amuïssons',
    secondPlural: 'amuïssez',
    thirdPlural: 'amuïssent',
  },
  anneler: {
    first: 'annelle',
    second: 'annelles',
    thirdPlural: 'annellent',
  },
  apercevoir: {
    first: 'aperçois',
    second: 'aperçois',
    third: 'aperçoit',
    firstPlural: 'apercevons',
    secondPlural: 'apercevez',
    thirdPlural: 'aperçoivent',
  },
  apparaître: {
    first: 'apparais',
    second: 'apparais',
    firstPlural: 'apparaissons',
  },
  appauvrir: {
    second: 'appauvris',
    third: 'appauvrit',
    thirdPlural: 'appauvrissent',
  },
  appendre: {
    first: 'appends',
    second: 'appends',
    firstPlural: 'appendons',
  },
  apprendre: {
    first: 'apprends',
    second: 'apprends',
    secondPlural: 'apprenez',
    thirdPlural: 'apprennent',
  },
  assaillir: {
    first: 'assaille',
    second: 'assailles',
    firstPlural: 'assaillons',
    secondPlural: 'assaillez',
    thirdPlural: 'assaillent',
  },
  asseoir: {
    firstPlural: 'asseyons',
    secondPlural: 'asseyez',
    thirdPlural: 'assoient',
  },
  asservir: {
    second: 'asservis',
    third: 'asservit',
    thirdPlural: 'asservissent',
  },
  atteler: {
    first: 'attelle',
    second: 'attelles',
    third: 'attelle',
    thirdPlural: 'attellent',
  },
  attendre: {
    first: 'attends',
    second: 'attends',
    firstPlural: 'attendons',
  },
  autoconstruire: {
    third: 'autoconstruit',
    firstPlural: 'autoconstruisons',
    thirdPlural: 'autoconstruisent',
  },
  autodétruire: {
    third: 'autodétruit',
    firstPlural: 'autodétruisons',
    thirdPlural: 'autodétruisent',
  },
  automaintenir: {
    second: 'automaintenis',
    third: 'automaintenit',
    firstPlural: 'automaintenissons',
    secondPlural: 'automaintenissez',
    thirdPlural: 'automaintenissent',
  },
  autorevendre: {
    first: 'autorevends',
    second: 'autorevends',
    firstPlural: 'autorevendons',
  },
  autosuffire: {
    third: 'autosuffit',
    firstPlural: 'autosuffisons',
    thirdPlural: 'autosuffisent',
  },
  balayer: {
    first: 'balaye',
    third: 'balaye',
    thirdPlural: 'balayent',
  },
  banqueter: {
    first: 'banquette',
    second: 'banquettes',
    third: 'banquette',
    thirdPlural: 'banquettent',
  },
  bateler: {
    first: 'batelle',
    second: 'batelles',
    third: 'batelle',
    thirdPlural: 'batellent',
  },
  bayer: {
    first: 'baye',
    third: 'baye',
    thirdPlural: 'bayent',
  },
  becqueter: {
    first: 'becquète',
    second: 'becquètes',
    thirdPlural: 'becquètent',
  },
  bégayer: {
    first: 'bégaye',
    third: 'bégaye',
    thirdPlural: 'bégayent',
  },
  bégueter: {
    first: 'béguette',
    second: 'béguettes',
    third: 'béguette',
    thirdPlural: 'béguettent',
  },
  boire: {
    third: 'boit',
    firstPlural: 'buvons',
    secondPlural: 'buvez',
    thirdPlural: 'boivent',
  },
  bosseler: {
    first: 'bosselle',
    second: 'bosselles',
    third: 'bosselle',
    thirdPlural: 'bossellent',
  },
  botteler: {
    first: 'bottelle',
    second: 'bottelles',
    third: 'bottelle',
    thirdPlural: 'bottellent',
  },
  bouillir: {
    first: 'bous',
    second: 'bous',
    third: 'bout',
    firstPlural: 'bouillons',
    secondPlural: 'bouillez',
  },
  bretteler: {
    first: 'brettelle',
    second: 'brettelles',
    third: 'brettelle',
    thirdPlural: 'brettellent',
  },
  briqueter: {
    first: 'briquette',
    second: 'briquettes',
    third: 'briquette',
    thirdPlural: 'briquettent',
  },
  cacheter: {
    first: 'cachette',
    second: 'cachettes',
    third: 'cachette',
    thirdPlural: 'cachettent',
  },
  cailleter: {
    first: 'caillette',
    second: 'caillettes',
    third: 'caillette',
    thirdPlural: 'caillettent',
  },
  caleter: {
    first: 'calette',
    second: 'calettes',
    third: 'calette',
    thirdPlural: 'calettent',
  },
  canneler: {
    first: 'cannelle',
    second: 'cannelles',
    thirdPlural: 'cannellent',
  },
  caqueter: {
    first: 'caquette',
    second: 'caquettes',
    third: 'caquette',
    thirdPlural: 'caquettent',
  },
  cartayer: {
    first: 'cartaye',
    third: 'cartaye',
    thirdPlural: 'cartayent',
  },
  celer: {
    first: 'cèle',
    second: 'cèles',
    third: 'cèle',
    thirdPlural: 'cèlent',
  },
  chanceler: {
    first: 'chancelle',
    second: 'chancelles',
    third: 'chancelle',
    thirdPlural: 'chancellent',
  },
  chevreter: {
    first: 'chevrette',
    second: 'chevrettes',
    third: 'chevrette',
    thirdPlural: 'chevrettent',
  },
  choir: {
    firstPlural: 'choyons',
    secondPlural: 'choyez',
    thirdPlural: 'choient',
  },
  circoncire: {
    third: 'circoncit',
    firstPlural: 'circoncisons',
    secondPlural: 'circoncisez',
    thirdPlural: 'circoncisent',
  },
  circonscrire: {
    third: 'circonscrit',
    firstPlural: 'circonscrivons',
    secondPlural: 'circonscrivez',
    thirdPlural: 'circonscrivent',
  },
  ciseler: {
    first: 'cisèle',
    second: 'cisèles',
    third: 'cisèle',
    thirdPlural: 'cisèlent',
  },
  claqueter: {
    first: 'claquette',
    second: 'claquettes',
    third: 'claquette',
    thirdPlural: 'claquettent',
  },
  cliqueter: {
    first: 'cliquette',
    second: 'cliquettes',
    third: 'cliquette',
    thirdPlural: 'cliquettent',
  },
  colleter: {
    first: 'collette',
    second: 'collettes',
    third: 'collette',
    thirdPlural: 'collettent',
  },
  comparaître: {
    first: 'comparais',
    second: 'comparais',
    firstPlural: 'comparaissons',
  },
  complaire: {
    firstPlural: 'complaisons',
    secondPlural: 'complaisez',
    thirdPlural: 'complaisent',
  },
  comprendre: {
    first: 'comprends',
    second: 'comprends',
    secondPlural: 'comprenez',
    thirdPlural: 'comprennent',
  },
  concevoir: {
    first: 'conçois',
    second: 'conçois',
    third: 'conçoit',
    firstPlural: 'concevons',
    secondPlural: 'concevez',
    thirdPlural: 'conçoivent',
  },
  condescendre: {
    first: 'condescends',
    second: 'condescends',
    firstPlural: 'condescendons',
  },
  confire: {
    third: 'confit',
    firstPlural: 'confisons',
    thirdPlural: 'confisent',
  },
  conjoindre: {
    third: 'conjoint',
    firstPlural: 'conjoignons',
    thirdPlural: 'conjoignent',
  },
  connaître: {
    first: 'connais',
    second: 'connais',
    firstPlural: 'connaissons',
  },
  conquérir: {
    firstPlural: 'conquérons',
    secondPlural: 'conquérez',
    thirdPlural: 'conquièrent',
  },
  consentir: {
    second: 'consens',
    third: 'consent',
    firstPlural: 'consentons',
    secondPlural: 'consentez',
    thirdPlural: 'consentent',
  },
  construire: {
    third: 'construit',
    firstPlural: 'construisons',
    thirdPlural: 'construisent',
  },
  contraindre: {
    third: 'contraint',
    firstPlural: 'contraignons',
    thirdPlural: 'contraignent',
  },
  contredire: {
    third: 'contredit',
    firstPlural: 'contredisons',
    secondPlural: 'contredisez',
    thirdPlural: 'contredisent',
  },
  contrefaire: {
    third: 'contrefait',
    firstPlural: 'contrefaisons',
    secondPlural: 'contrefaites',
    thirdPlural: 'contrefassent',
  },
  coqueter: {
    first: 'coquette',
    second: 'coquettes',
    third: 'coquette',
    thirdPlural: 'coquettent',
  },
  cordeler: {
    first: 'cordelle',
    second: 'cordelles',
    third: 'cordelle',
    thirdPlural: 'cordellent',
  },
  corseter: {
    first: 'corsète',
    second: 'corsètes',
    thirdPlural: 'corsètent',
  },
  coudre: {
    first: 'couds',
    second: 'couds',
    firstPlural: 'cousons',
    secondPlural: 'cousez',
    thirdPlural: 'cousent',
  },
  courrieler: {
    first: 'courrièle',
    second: 'courrièles',
    third: 'courrièle',
    thirdPlural: 'courrièlent',
  },
  craindre: {
    third: 'craint',
    firstPlural: 'craignons',
    thirdPlural: 'craignent',
  },
  craqueler: {
    first: 'craquelle',
    second: 'craquelles',
    third: 'craquelle',
    thirdPlural: 'craquellent',
  },
  craqueter: {
    first: 'craquète',
    second: 'craquètes',
    thirdPlural: 'craquètent',
  },
  créneler: {
    first: 'crénelle',
    second: 'crénelles',
    thirdPlural: 'crénellent',
  },
  crocheter: {
    first: 'crochète',
    second: 'crochètes',
    thirdPlural: 'crochètent',
  },
  croire: {
    third: 'croit',
    firstPlural: 'croyons',
    secondPlural: 'croyez',
  },
  cueillir: {
    first: 'cueille',
    second: 'cueilles',
    firstPlural: 'cueillons',
    secondPlural: 'cueillez',
  },
  cuire: {
    third: 'cuit',
    firstPlural: 'cuisons',
    thirdPlural: 'cuisent',
  },
  cureter: {
    first: 'curette',
    second: 'curettes',
    third: 'curette',
    thirdPlural: 'curettent',
  },
  déblayer: {
    first: 'déblaye',
    third: 'déblaye',
    thirdPlural: 'déblayent',
  },
  débosseler: {
    first: 'débosselle',
    second: 'débosselles',
    third: 'débosselle',
    thirdPlural: 'débossellent',
  },
  débouillir: {
    first: 'débous',
    second: 'débous',
    third: 'débout',
    firstPlural: 'débouillons',
    secondPlural: 'débouillez',
  },
  débrayer: {
    first: 'débraye',
    third: 'débraye',
    thirdPlural: 'débrayent',
  },
  décacheter: {
    first: 'décachette',
    second: 'décachettes',
    third: 'décachette',
    thirdPlural: 'décachettent',
  },
  déceler: {
    first: 'décèle',
    second: 'décèles',
    third: 'décèle',
    thirdPlural: 'décèlent',
  },
  décevoir: {
    first: 'déçois',
    second: 'déçois',
    third: 'déçoit',
    firstPlural: 'décevons',
    secondPlural: 'décevez',
    thirdPlural: 'déçoivent',
  },
  déchiqueter: {
    first: 'déchiquette',
    second: 'déchiquettes',
    third: 'déchiquette',
    thirdPlural: 'déchiquettent',
  },
  déchoir: {
    firstPlural: 'déchoyons',
    secondPlural: 'déchoyez',
    thirdPlural: 'déchoient',
  },
  décliqueter: {
    first: 'décliquète',
    second: 'décliquètes',
    thirdPlural: 'décliquètent',
  },
  décolleter: {
    first: 'décollette',
    second: 'décollettes',
    third: 'décollette',
    thirdPlural: 'décollettent',
  },
  déconfire: {
    third: 'déconfit',
    firstPlural: 'déconfisons',
    thirdPlural: 'déconfisent',
  },
  déconstruire: {
    third: 'déconstruit',
    firstPlural: 'déconstruisons',
    thirdPlural: 'déconstruisent',
  },
  découdre: {
    first: 'découds',
    second: 'découds',
    firstPlural: 'décousons',
    secondPlural: 'décousez',
    thirdPlural: 'décousent',
  },
  décrire: {
    third: 'décrit',
    firstPlural: 'décrivons',
    secondPlural: 'décrivez',
    thirdPlural: 'décrivent',
  },
  décroître: {
    first: 'décrois',
    second: 'décrois',
    firstPlural: 'décroissons',
    thirdPlural: 'décroissent',
  },
  dédire: {
    third: 'dédit',
    firstPlural: 'dédisons',
    secondPlural: 'dédisez',
    thirdPlural: 'dédisent',
  },
  défaillir: {
    first: 'défaille',
    second: 'défailles',
    firstPlural: 'défaillons',
    secondPlural: 'défaillez',
    thirdPlural: 'défaillent',
  },
  défaire: {
    third: 'défait',
    firstPlural: 'défaisons',
    secondPlural: 'défaites',
    thirdPlural: 'défont',
  },
  défendre: {
    first: 'défends',
    second: 'défends',
    firstPlural: 'défendons',
  },
  déficeler: {
    first: 'déficelle',
    second: 'déficelles',
    third: 'déficelle',
    thirdPlural: 'déficellent',
  },
  défrayer: {
    first: 'défraye',
    third: 'défraye',
    thirdPlural: 'défrayent',
  },
  déjeter: {
    first: 'déjette',
    second: 'déjettes',
    thirdPlural: 'déjettent',
  },
  délayer: {
    first: 'délaye',
    third: 'délaye',
    thirdPlural: 'délayent',
  },
  démanteler: {
    first: 'démantèle',
    second: 'démantèles',
    third: 'démantèle',
    thirdPlural: 'démantèlent',
  },
  démentir: {
    second: 'démens',
    third: 'dément',
    firstPlural: 'démentons',
    secondPlural: 'démentez',
    thirdPlural: 'démentent',
  },
  démoucheter: {
    first: 'démouchette',
    second: 'démouchettes',
    third: 'démouchette',
    thirdPlural: 'démouchettent',
  },
  démuseler: {
    first: 'démuselle',
    second: 'démuselles',
    third: 'démuselle',
    thirdPlural: 'démusellent',
  },
  denteler: {
    first: 'dentelle',
    second: 'dentelles',
    third: 'dentelle',
    thirdPlural: 'dentellent',
  },
  dépaqueter: {
    first: 'dépaquète',
    second: 'dépaquètes',
    thirdPlural: 'dépaquètent',
  },
  départir: {
    first: 'dépars',
    second: 'dépars',
    third: 'départ',
    firstPlural: 'départons',
    secondPlural: 'départez',
    thirdPlural: 'départent',
  },
  dépecer: {
    first: 'dépèce',
    second: 'dépèces',
    third: 'dépèce',
    thirdPlural: 'dépècent',
  },
  dépendre: {
    first: 'dépends',
    second: 'dépends',
    firstPlural: 'dépendons',
  },
  déplaire: {
    firstPlural: 'déplaisons',
    secondPlural: 'déplaisez',
    thirdPlural: 'déplaisent',
  },
  dépourvoir: {
    firstPlural: 'dépourvoyons',
    secondPlural: 'dépourvoyez',
    thirdPlural: 'dépourvoient',
  },
  déprendre: {
    first: 'déprends',
    second: 'déprends',
    secondPlural: 'déprenez',
    thirdPlural: 'déprennent',
  },
  dépuceler: {
    first: 'dépucèle',
    second: 'dépucèles',
    third: 'dépucèle',
    thirdPlural: 'dépucèlent',
  },
  dérayer: {
    first: 'déraye',
    third: 'déraye',
    thirdPlural: 'dérayent',
  },
  désapprendre: {
    first: 'désapprends',
    second: 'désapprends',
    secondPlural: 'désapprenez',
    thirdPlural: 'désapprennent',
  },
  descendre: {
    first: 'descends',
    second: 'descends',
    firstPlural: 'descendons',
  },
  désensorceler: {
    first: 'désensorcelle',
    second: 'désensorcelles',
    third: 'désensorcelle',
    thirdPlural: 'désensorcellent',
  },
  désintégrer: {
    first: 'désintègre',
    third: 'désintègre',
    thirdPlural: 'désintègrent',
  },
  dételer: {
    first: 'dételle',
    second: 'dételles',
    third: 'dételle',
    thirdPlural: 'détellent',
  },
  détendre: {
    first: 'détends',
    second: 'détends',
    firstPlural: 'détendons',
  },
  détruire: {
    third: 'détruit',
    firstPlural: 'détruisons',
    thirdPlural: 'détruisent',
  },
  dévêtir: {
    second: 'dévêts',
    firstPlural: 'dévêtons',
    secondPlural: 'dévêtez',
  },
  devoir: {
    first: 'dois',
    second: 'dois',
    third: 'doit',
    firstPlural: 'devons',
    secondPlural: 'devez',
    thirdPlural: 'doivent',
  },
  disjoindre: {
    third: 'disjoint',
    firstPlural: 'disjoignons',
    thirdPlural: 'disjoignent',
  },
  disparaître: {
    first: 'disparais',
    second: 'disparais',
    firstPlural: 'disparaissons',
  },
  dissoudre: {
    third: 'dissout',
    firstPlural: 'dissolvons',
    secondPlural: 'dissolvez',
    thirdPlural: 'dissolvent',
  },
  distendre: {
    first: 'distends',
    second: 'distends',
    firstPlural: 'distendons',
  },
  ébiseler: {
    first: 'ébiselle',
    second: 'ébiselles',
    third: 'ébiselle',
    thirdPlural: 'ébisellent',
  },
  écarteler: {
    first: 'écartèle',
    second: 'écartèles',
    third: 'écartèle',
    thirdPlural: 'écartèlent',
  },
  échoir: {
    firstPlural: 'échoyons',
    secondPlural: 'échoyez',
    thirdPlural: 'échoient',
  },
  écrire: {
    third: 'écrit',
    firstPlural: 'écrivons',
    secondPlural: 'écrivez',
    thirdPlural: 'écrivent',
  },
  effrayer: {
    first: 'effraye',
    third: 'effraye',
    thirdPlural: 'effrayent',
  },
  égayer: {
    first: 'égaye',
    third: 'égaye',
    thirdPlural: 'égayent',
  },
  élire: {
    third: 'élit',
    firstPlural: 'élisons',
    thirdPlural: 'élisent',
  },
  embrayer: {
    first: 'embraye',
    third: 'embraye',
    thirdPlural: 'embrayent',
  },
  émoudre: {
    first: 'émouds',
    second: 'émouds',
    firstPlural: 'émoulons',
    secondPlural: 'émoulez',
    thirdPlural: 'émoulent',
  },
  émouvoir: {
    first: 'émeus',
    second: 'émeus',
    third: 'émeut',
    firstPlural: 'émouvons',
    secondPlural: 'émouvez',
    thirdPlural: 'émeuvent',
  },
  empaqueter: {
    first: 'empaquète',
    second: 'empaquètes',
    thirdPlural: 'empaquètent',
  },
  encasteler: {
    first: 'encastelle',
    second: 'encastelles',
    third: 'encastelle',
    thirdPlural: 'encastellent',
  },
  enclore: {
    third: 'enclot',
    firstPlural: 'enclosons',
    secondPlural: 'enclosez',
  },
  enfiévrer: {
    first: 'enfièvre',
    second: 'enfièvres',
    third: 'enfièvre',
    thirdPlural: 'enfièvrent',
  },
  enjoindre: {
    third: 'enjoint',
    firstPlural: 'enjoignons',
    thirdPlural: 'enjoignent',
  },
  enquérir: {
    firstPlural: 'enquérons',
    secondPlural: 'enquérez',
    thirdPlural: 'enquièrent',
  },
  enrayer: {
    first: 'enraye',
    third: 'enraye',
    thirdPlural: 'enrayent',
  },
  ensorceler: {
    first: 'ensorcelle',
    second: 'ensorcelles',
    third: 'ensorcelle',
    thirdPlural: 'ensorcellent',
  },
  entendre: {
    first: 'entends',
    second: 'entends',
    firstPlural: 'entendons',
  },
  entrapercevoir: {
    first: 'entraperçois',
    second: 'entraperçois',
    third: 'entraperçoit',
    firstPlural: 'entrapercevons',
    secondPlural: 'entrapercevez',
    thirdPlural: 'entraperçoivent',
  },
  entredétruire: {
    third: 'entredétruit',
    firstPlural: 'entredétruisons',
    thirdPlural: 'entredétruisent',
  },
  entreprendre: {
    first: 'entreprends',
    second: 'entreprends',
    secondPlural: 'entreprenez',
    thirdPlural: 'entreprennent',
  },
  entrevoir: {
    firstPlural: 'entrevoyons',
    secondPlural: 'entrevoyez',
    thirdPlural: 'entrevoient',
  },
  épanneler: {
    first: 'épannelle',
    second: 'épannelles',
    thirdPlural: 'épannellent',
  },
  épinceler: {
    first: 'épincelle',
    second: 'épincelles',
    third: 'épincelle',
    thirdPlural: 'épincellent',
  },
  épinceter: {
    first: 'épincette',
    second: 'épincettes',
    third: 'épincette',
    thirdPlural: 'épincettent',
  },
  épousseter: {
    first: 'époussette',
    second: 'époussettes',
    third: 'époussette',
    thirdPlural: 'époussettent',
  },
  éprendre: {
    first: 'éprends',
    second: 'éprends',
    secondPlural: 'éprenez',
    thirdPlural: 'éprennent',
  },
  équivaloir: {
    firstPlural: 'équivalons',
    secondPlural: 'équivalez',
    thirdPlural: 'équivaillent',
  },
  essayer: {
    first: 'essaye',
    third: 'essaye',
    thirdPlural: 'essayent',
  },
  étayer: {
    first: 'étaye',
    third: 'étaye',
    thirdPlural: 'étayent',
  },
  étendre: {
    first: 'étends',
    second: 'étends',
    firstPlural: 'étendons',
  },
  étinceler: {
    first: 'étincelle',
    second: 'étincelles',
    third: 'étincelle',
    thirdPlural: 'étincellent',
  },
  étiqueter: {
    first: 'étiquette',
    second: 'étiquettes',
    third: 'étiquette',
    thirdPlural: 'étiquettent',
  },
  être: {
    second: 'sois',
    third: 'est',
    firstPlural: 'sommes',
    secondPlural: 'êtes',
    thirdPlural: 'soient',
  },
  exécrer: {
    first: 'exècre',
    second: 'exècres',
    third: 'exècre',
    thirdPlural: 'exècrent',
  },
  faillir: {
    first: 'faux',
    second: 'faille',
    third: 'faut',
    firstPlural: 'faillons',
    secondPlural: 'faillez',
    thirdPlural: 'faillent',
  },
  fendre: {
    first: 'fends',
    second: 'fends',
    firstPlural: 'fendons',
  },
  feuilleter: {
    first: 'feuillette',
    second: 'feuillettes',
    third: 'feuillette',
    thirdPlural: 'feuillettent',
  },
  ficeler: {
    first: 'ficelle',
    second: 'ficelles',
    third: 'ficelle',
    thirdPlural: 'ficellent',
  },
  fileter: {
    first: 'filette',
    second: 'filettes',
    third: 'filette',
    thirdPlural: 'filettent',
  },
  forjeter: {
    first: 'forjette',
    second: 'forjettes',
    thirdPlural: 'forjettent',
  },
  frayer: {
    first: 'fraye',
    third: 'fraye',
    thirdPlural: 'frayent',
  },
  frire: {
    third: 'frit',
    firstPlural: 'frisons',
    secondPlural: 'frisez',
    thirdPlural: 'frisent',
  },
  fureter: {
    first: 'furète',
    second: 'furètes',
    thirdPlural: 'furètent',
  },
  fuseler: {
    first: 'fuselle',
    second: 'fuselles',
    third: 'fuselle',
    thirdPlural: 'fusellent',
  },
  galéjer: {
    first: 'galèje',
    second: 'galèjes',
    third: 'galèje',
    thirdPlural: 'galèjent',
  },
  grasseyer: {
    first: 'grasseye',
    third: 'grasseye',
    thirdPlural: 'grasseyent',
  },
  greneler: {
    first: 'grenèle',
    second: 'grenèles',
    third: 'grenèle',
    thirdPlural: 'grenèlent',
  },
  guérir: {
    second: 'guéris',
    third: 'guérit',
    thirdPlural: 'guérissent',
  },
  guillemeter: {
    first: 'guillemète',
    second: 'guillemètes',
    thirdPlural: 'guillemètent',
  },
  haïr: {
    first: 'hais',
    second: 'hais',
    third: 'hait',
    firstPlural: 'haïssons',
    secondPlural: 'haïssez',
    thirdPlural: 'haïssent',
  },
  haleter: {
    first: 'halète',
    second: 'halètes',
    thirdPlural: 'halètent',
  },
  harceler: {
    first: 'harcèle',
    second: 'harcèles',
    third: 'harcèle',
    thirdPlural: 'harcèlent',
  },
  hoqueter: {
    first: 'hoquette',
    second: 'hoquettes',
    third: 'hoquette',
    thirdPlural: 'hoquettent',
  },
  inscrire: {
    third: 'inscrit',
    firstPlural: 'inscrivons',
    secondPlural: 'inscrivez',
    thirdPlural: 'inscrivent',
  },
  instruire: {
    third: 'instruit',
    firstPlural: 'instruisons',
    thirdPlural: 'instruisent',
  },
  intégrer: {
    first: 'intègre',
    third: 'intègre',
    thirdPlural: 'intègrent',
  },
  interdire: {
    third: 'interdit',
    firstPlural: 'interdisons',
    secondPlural: 'interdisez',
    thirdPlural: 'interdisent',
  },
  interjeter: {
    first: 'interjette',
    second: 'interjettes',
    thirdPlural: 'interjettent',
  },
  jarreter: {
    first: 'jarrette',
    second: 'jarrettes',
    third: 'jarrette',
    thirdPlural: 'jarrettent',
  },
  jeter: {
    first: 'jette',
    second: 'jettes',
    thirdPlural: 'jettent',
  },
  joindre: {
    third: 'joint',
    firstPlural: 'joignons',
    thirdPlural: 'joignent',
  },
  layer: {
    first: 'laye',
    third: 'laye',
    thirdPlural: 'layent',
  },
  lire: {
    third: 'lit',
    firstPlural: 'lisons',
    thirdPlural: 'lisent',
  },
  liserer: {
    first: 'lisère',
    second: 'lisères',
    third: 'lisère',
    thirdPlural: 'lisèrent',
  },
  luire: {
    third: 'luit',
    firstPlural: 'luisons',
    thirdPlural: 'luisent',
  },
  marqueter: {
    first: 'marquette',
    second: 'marquettes',
    third: 'marquette',
    thirdPlural: 'marquettent',
  },
  marteler: {
    first: 'martèle',
    second: 'martèles',
    third: 'martèle',
    thirdPlural: 'martèlent',
  },
  maudire: {
    third: 'maudit',
    firstPlural: 'maudissons',
    secondPlural: 'maudissez',
    thirdPlural: 'maudissent',
  },
  méconnaître: {
    first: 'méconnais',
    second: 'méconnais',
    firstPlural: 'méconnaissons',
  },
  médire: {
    third: 'médit',
    firstPlural: 'médisons',
    secondPlural: 'médisez',
    thirdPlural: 'médisent',
  },
  mentir: {
    second: 'mens',
    third: 'ment',
    firstPlural: 'mentons',
    secondPlural: 'mentez',
    thirdPlural: 'mentent',
  },
  méprendre: {
    first: 'méprends',
    second: 'méprends',
    secondPlural: 'méprenez',
    thirdPlural: 'méprennent',
  },
  modeler: {
    first: 'modèle',
    second: 'modèles',
    third: 'modèle',
    thirdPlural: 'modèlent',
  },
  moleter: {
    first: 'molette',
    second: 'molettes',
    third: 'molette',
    thirdPlural: 'molettent',
  },
  monnayer: {
    first: 'monnaye',
    third: 'monnaye',
    thirdPlural: 'monnayent',
  },
  morceler: {
    first: 'morcelle',
    second: 'morcelles',
    third: 'morcelle',
    thirdPlural: 'morcellent',
  },
  moucheter: {
    first: 'mouchette',
    second: 'mouchettes',
    third: 'mouchette',
    thirdPlural: 'mouchettent',
  },
  moudre: {
    first: 'mouds',
    second: 'mouds',
    firstPlural: 'moulons',
    secondPlural: 'moulez',
    thirdPlural: 'moulent',
  },
  moufeter: {
    first: 'moufette',
    second: 'moufettes',
    third: 'moufette',
    thirdPlural: 'moufettent',
  },
  mourir: {
    first: 'meurs',
    second: 'meurs',
    third: 'meurt',
    firstPlural: 'mourons',
    secondPlural: 'mourez',
    thirdPlural: 'meurent',
  },
  mouvoir: {
    first: 'meus',
    second: 'meus',
    third: 'meut',
    firstPlural: 'mouvons',
    secondPlural: 'mouvez',
    thirdPlural: 'meuvent',
  },
  museler: {
    first: 'muselle',
    second: 'muselles',
    third: 'muselle',
    thirdPlural: 'musellent',
  },
  naître: {
    first: 'nais',
    second: 'nais',
    firstPlural: 'naissons',
  },
  nickeler: {
    first: 'nickèle',
    second: 'nickèles',
    third: 'nickèle',
    thirdPlural: 'nickèlent',
  },
  nuire: {
    third: 'nuit',
    firstPlural: 'nuisons',
    thirdPlural: 'nuisent',
  },
  oindre: {
    third: 'oint',
    firstPlural: 'oignons',
    thirdPlural: 'oignent',
  },
  oiseler: {
    first: 'oiselle',
    second: 'oiselles',
    third: 'oiselle',
    thirdPlural: 'oisellent',
  },
  ouïr: {
    first: 'ois',
    second: 'ois',
    third: 'oit',
    firstPlural: 'oyons',
    secondPlural: 'oyez',
    thirdPlural: 'oient',
  },
  pagayer: {
    first: 'pagaye',
    third: 'pagaye',
    thirdPlural: 'pagayent',
  },
  pailleter: {
    first: 'paillette',
    second: 'paillettes',
    third: 'paillette',
    thirdPlural: 'paillettent',
  },
  paître: {
    first: 'pais',
    second: 'pais',
    firstPlural: 'paissons',
  },
  panteler: {
    first: 'pantelle',
    second: 'pantelles',
    third: 'pantelle',
    thirdPlural: 'pantellent',
  },
  paraître: {
    first: 'parais',
    second: 'parais',
    firstPlural: 'paraissons',
  },
  parqueter: {
    first: 'parquette',
    second: 'parquettes',
    third: 'parquette',
    thirdPlural: 'parquettent',
  },
  partir: {
    first: 'pars',
    second: 'pars',
    third: 'part',
    firstPlural: 'partons',
    secondPlural: 'partez',
    thirdPlural: 'partent',
  },
  payer: {
    first: 'paye',
    third: 'paye',
    thirdPlural: 'payent',
  },
  peler: {
    first: 'pèle',
    second: 'pèles',
    third: 'pèle',
    thirdPlural: 'pèlent',
  },
  pelleter: {
    first: 'pellette',
    second: 'pellettes',
    third: 'pellette',
    thirdPlural: 'pellettent',
  },
  pendre: {
    first: 'pends',
    second: 'pends',
    firstPlural: 'pendons',
  },
  percevoir: {
    first: 'perçois',
    second: 'perçois',
    third: 'perçoit',
    firstPlural: 'percevons',
    secondPlural: 'percevez',
    thirdPlural: 'perçoivent',
  },
  piqueter: {
    first: 'piquète',
    second: 'piquètes',
    thirdPlural: 'piquètent',
  },
  plaindre: {
    third: 'plaint',
    firstPlural: 'plaignons',
    thirdPlural: 'plaignent',
  },
  plaire: {
    firstPlural: 'plaisons',
    secondPlural: 'plaisez',
    thirdPlural: 'plaisent',
  },
  poindre: {
    third: 'point',
    firstPlural: 'poignons',
    thirdPlural: 'poignent',
  },
  pourfendre: {
    first: 'pourfends',
    second: 'pourfends',
    firstPlural: 'pourfendons',
  },
  pourvoir: {
    firstPlural: 'pourvoyons',
    secondPlural: 'pourvoyez',
    thirdPlural: 'pourvoient',
  },
  préacheter: {
    first: 'préachète',
    second: 'préachètes',
    thirdPlural: 'préachètent',
  },
  préconcevoir: {
    first: 'préconçois',
    second: 'préconçois',
    third: 'préconçoit',
    firstPlural: 'préconcevons',
    secondPlural: 'préconcevez',
    thirdPlural: 'préconçoivent',
  },
  préconstruire: {
    third: 'préconstruit',
    firstPlural: 'préconstruisons',
    thirdPlural: 'préconstruisent',
  },
  prédire: {
    third: 'prédit',
    firstPlural: 'prédisons',
    secondPlural: 'prédisez',
    thirdPlural: 'prédisent',
  },
  prendre: {
    first: 'prends',
    second: 'prends',
    secondPlural: 'prenez',
    thirdPlural: 'prennent',
  },
  prépayer: {
    first: 'prépaye',
    third: 'prépaye',
    thirdPlural: 'prépayent',
  },
  prescrire: {
    third: 'prescrit',
    firstPlural: 'prescrivons',
    secondPlural: 'prescrivez',
    thirdPlural: 'prescrivent',
  },
  pressentir: {
    second: 'pressens',
    third: 'pressent',
    firstPlural: 'pressentons',
    secondPlural: 'pressentez',
    thirdPlural: 'pressentent',
  },
  prétendre: {
    first: 'prétends',
    second: 'prétends',
    firstPlural: 'prétendons',
  },
  prévaloir: {
    firstPlural: 'prévalons',
    secondPlural: 'prévalez',
    thirdPlural: 'prévalent',
  },
  prévoir: {
    firstPlural: 'prévoyons',
    secondPlural: 'prévoyez',
    thirdPlural: 'prévoient',
  },
  projeter: {
    first: 'projette',
    second: 'projettes',
    thirdPlural: 'projettent',
  },
  promouvoir: {
    first: 'promeus',
    second: 'promeus',
    third: 'promeut',
    firstPlural: 'promouvons',
    secondPlural: 'promouvez',
    thirdPlural: 'promeuvent',
  },
  proscrire: {
    third: 'proscrit',
    firstPlural: 'proscrivons',
    secondPlural: 'proscrivez',
    thirdPlural: 'proscrivent',
  },
  racheter: {
    first: 'rachète',
    second: 'rachètes',
    thirdPlural: 'rachètent',
  },
  rapiécer: {
    first: 'rapièce',
    second: 'rapièces',
    third: 'rapièce',
    thirdPlural: 'rapiècent',
  },
  rapprendre: {
    first: 'rapprends',
    second: 'rapprends',
    secondPlural: 'rapprenez',
    thirdPlural: 'rapprennent',
  },
  rasseoir: {
    firstPlural: 'rasseyons',
    secondPlural: 'rasseyez',
    thirdPlural: 'rassoient',
  },
  râteler: {
    first: 'râtelle',
    second: 'râtelles',
    third: 'râtelle',
    thirdPlural: 'râtellent',
  },
  rayer: {
    first: 'raye',
    third: 'raye',
    thirdPlural: 'rayent',
  },
  réapparaître: {
    first: 'réapparais',
    second: 'réapparais',
    firstPlural: 'réapparaissons',
  },
  réapprendre: {
    first: 'réapprends',
    second: 'réapprends',
    secondPlural: 'réapprenez',
    thirdPlural: 'réapprennent',
  },
  réasservir: {
    second: 'réasservis',
    third: 'réasservit',
    thirdPlural: 'réasservissent',
  },
  reboire: {
    third: 'reboit',
    firstPlural: 'rebuvons',
    secondPlural: 'rebuvez',
    thirdPlural: 'reboivent',
  },
  recacheter: {
    first: 'recachette',
    second: 'recachettes',
    third: 'recachette',
    thirdPlural: 'recachettent',
  },
  receler: {
    first: 'recèle',
    second: 'recèles',
    third: 'recèle',
    thirdPlural: 'recèlent',
  },
  receper: {
    first: 'recèpe',
    second: 'recèpes',
    third: 'recèpe',
    thirdPlural: 'recèpent',
  },
  recéper: {
    first: 'recèpe',
    second: 'recèpes',
    third: 'recèpe',
    thirdPlural: 'recèpent',
  },
  recevoir: {
    first: 'reçois',
    second: 'reçois',
    third: 'reçoit',
    firstPlural: 'recevons',
    secondPlural: 'recevez',
    thirdPlural: 'reçoivent',
  },
  reconnaître: {
    first: 'reconnais',
    second: 'reconnais',
    firstPlural: 'reconnaissons',
  },
  reconquérir: {
    firstPlural: 'reconquérons',
    secondPlural: 'reconquérez',
    thirdPlural: 'reconquièrent',
  },
  reconstruire: {
    third: 'reconstruit',
    firstPlural: 'reconstruisons',
    thirdPlural: 'reconstruisent',
  },
  recoudre: {
    first: 'recouds',
    second: 'recouds',
    firstPlural: 'recousons',
    secondPlural: 'recousez',
    thirdPlural: 'recousent',
  },
  récrire: {
    third: 'récrit',
    firstPlural: 'récrivons',
    secondPlural: 'récrivez',
    thirdPlural: 'récrivent',
  },
  recroître: {
    first: 'recrois',
    second: 'recrois',
    firstPlural: 'recroissons',
    thirdPlural: 'recroissent',
  },
  recueillir: {
    first: 'recueille',
    second: 'recueilles',
    firstPlural: 'recueillons',
    secondPlural: 'recueillez',
  },
  recuire: {
    third: 'recuit',
    firstPlural: 'recuisons',
    thirdPlural: 'recuisent',
  },
  redécrire: {
    third: 'redécrit',
    firstPlural: 'redécrivons',
    secondPlural: 'redécrivez',
    thirdPlural: 'redécrivent',
  },
  redéfaire: {
    third: 'redéfait',
    firstPlural: 'redéfaisons',
    secondPlural: 'redéfaites',
    thirdPlural: 'redéfont',
  },
  redescendre: {
    first: 'redescends',
    second: 'redescends',
    firstPlural: 'redescendons',
  },
  redevoir: {
    first: 'redois',
    second: 'redois',
    third: 'redoit',
    firstPlural: 'redevons',
    secondPlural: 'redevez',
    thirdPlural: 'redoivent',
  },
  redire: {
    third: 'redit',
    firstPlural: 'redisons',
    secondPlural: 'redites',
    thirdPlural: 'redisent',
  },
  réécrire: {
    third: 'réécrit',
    firstPlural: 'réécrivons',
    secondPlural: 'réécrivez',
    thirdPlural: 'réécrivent',
  },
  réélire: {
    third: 'réélit',
    firstPlural: 'réélisons',
    thirdPlural: 'réélisent',
  },
  réentendre: {
    first: 'réentends',
    second: 'réentends',
    firstPlural: 'réentendons',
  },
  réessayer: {
    first: 'réessaye',
    third: 'réessaye',
    thirdPlural: 'réessayent',
  },
  refaire: {
    third: 'refait',
    firstPlural: 'refaisons',
    secondPlural: 'refaites',
    thirdPlural: 'refont',
  },
  refendre: {
    first: 'refends',
    second: 'refends',
    firstPlural: 'refendons',
  },
  réinscrire: {
    third: 'réinscrit',
    firstPlural: 'réinscrivons',
    secondPlural: 'réinscrivez',
    thirdPlural: 'réinscrivent',
  },
  réintégrer: {
    first: 'réintègre',
    third: 'réintègre',
    thirdPlural: 'réintègrent',
  },
  rejeter: {
    first: 'rejette',
    second: 'rejettes',
    thirdPlural: 'rejettent',
  },
  rejoindre: {
    third: 'rejoint',
    firstPlural: 'rejoignons',
    thirdPlural: 'rejoignent',
  },
  relayer: {
    first: 'relaye',
    third: 'relaye',
    thirdPlural: 'relayent',
  },
  relire: {
    third: 'relit',
    firstPlural: 'relisons',
    thirdPlural: 'relisent',
  },
  reloqueter: {
    first: 'reloquette',
    second: 'reloquettes',
    third: 'reloquette',
    thirdPlural: 'reloquettent',
  },
  reluire: {
    third: 'reluit',
    firstPlural: 'reluisons',
    thirdPlural: 'reluisent',
  },
  remblayer: {
    first: 'remblaye',
    third: 'remblaye',
    thirdPlural: 'remblayent',
  },
  remodeler: {
    first: 'remodèle',
    second: 'remodèles',
    third: 'remodèle',
    thirdPlural: 'remodèlent',
  },
  remoudre: {
    first: 'remouds',
    second: 'remouds',
    firstPlural: 'remoulons',
    secondPlural: 'remoulez',
    thirdPlural: 'remoulent',
  },
  rempaqueter: {
    first: 'rempaquète',
    second: 'rempaquètes',
    thirdPlural: 'rempaquètent',
  },
  renaître: {
    first: 'renais',
    second: 'renais',
    firstPlural: 'renaissons',
  },
  rendre: {
    first: 'rends',
    second: 'rends',
    firstPlural: 'rendons',
  },
  renformir: {
    second: 'renformis',
    third: 'renformit',
    thirdPlural: 'renformissent',
  },
  repaître: {
    first: 'repais',
    second: 'repais',
    firstPlural: 'repaissons',
  },
  reparaître: {
    first: 'reparais',
    second: 'reparais',
    firstPlural: 'reparaissons',
  },
  repartir: {
    first: 'repars',
    second: 'repars',
    third: 'repart',
    firstPlural: 'repartons',
    secondPlural: 'repartez',
    thirdPlural: 'repartent',
  },
  repayer: {
    first: 'repaye',
    third: 'repaye',
    thirdPlural: 'repayent',
  },
  rependre: {
    first: 'repends',
    second: 'repends',
    firstPlural: 'rependons',
  },
  repentir: {
    second: 'repens',
    third: 'repent',
    firstPlural: 'repentons',
    secondPlural: 'repentez',
    thirdPlural: 'repentent',
  },
  reprendre: {
    first: 'reprends',
    second: 'reprends',
    secondPlural: 'reprenez',
    thirdPlural: 'reprennent',
  },
  requérir: {
    firstPlural: 'requérons',
    secondPlural: 'requérez',
    thirdPlural: 'requièrent',
  },
  résoudre: {
    third: 'résout',
    firstPlural: 'résolvons',
    secondPlural: 'résolvez',
    thirdPlural: 'résolvent',
  },
  ressayer: {
    first: 'ressaye',
    third: 'ressaye',
    thirdPlural: 'ressayent',
  },
  ressentir: {
    second: 'ressens',
    third: 'ressent',
    firstPlural: 'ressentons',
    secondPlural: 'ressentez',
    thirdPlural: 'ressentent',
  },
  ressortir: {
    first: 'ressors',
    firstPlural: 'ressortons',
    secondPlural: 'ressortez',
  },
  retendre: {
    first: 'retends',
    second: 'retends',
    firstPlural: 'retendons',
  },
  retranscrire: {
    third: 'retranscrit',
    firstPlural: 'retranscrivons',
    secondPlural: 'retranscrivez',
    thirdPlural: 'retranscrivent',
  },
  revaloir: {
    firstPlural: 'revalons',
    secondPlural: 'revalez',
  },
  revendre: {
    first: 'revends',
    second: 'revends',
    firstPlural: 'revendons',
  },
  revêtir: {
    second: 'revêts',
    firstPlural: 'revêtons',
    secondPlural: 'revêtez',
  },
  revoir: {
    firstPlural: 'revoyons',
    secondPlural: 'revoyez',
    thirdPlural: 'revoient',
  },
  ruisseler: {
    first: 'ruisselle',
    second: 'ruisselles',
    third: 'ruisselle',
    thirdPlural: 'ruissellent',
  },
  saillir: {
    first: 'saille',
    second: 'sailles',
    third: 'saillit',
    secondPlural: 'saillez',
    thirdPlural: 'saillent',
  },
  satisfaire: {
    third: 'satisfait',
    firstPlural: 'satisfaisons',
    secondPlural: 'satisfaites',
    thirdPlural: 'satisfont',
  },
  sentir: {
    second: 'sens',
    third: 'sent',
    firstPlural: 'sentons',
    secondPlural: 'sentez',
    thirdPlural: 'sentent',
  },
  sortir: {
    first: 'sors',
    second: 'sors',
    third: 'sort',
    firstPlural: 'sortons',
    secondPlural: 'sortez',
  },
  souffleter: {
    first: 'soufflette',
    second: 'soufflettes',
    third: 'soufflette',
    thirdPlural: 'soufflettent',
  },
  'sous-entendre': {
    first: 'sous-entends',
    second: 'sous-entends',
    firstPlural: 'sous-entendons',
  },
  souscrire: {
    third: 'souscrit',
    firstPlural: 'souscrivons',
    secondPlural: 'souscrivez',
    thirdPlural: 'souscrivent',
  },
  soustendre: {
    first: 'soustends',
    second: 'soustends',
    firstPlural: 'soustendons',
  },
  suffire: {
    third: 'suffit',
    firstPlural: 'suffisons',
    thirdPlural: 'suffisent',
  },
  surfaire: {
    third: 'surfait',
    firstPlural: 'surfaisons',
    secondPlural: 'surfaites',
    thirdPlural: 'surfont',
  },
  surir: {
    second: 'suris',
    third: 'surit',
    thirdPlural: 'surissent',
  },
  surjeter: {
    first: 'surjette',
    second: 'surjettes',
    thirdPlural: 'surjettent',
  },
  surpayer: {
    first: 'surpaye',
    third: 'surpaye',
    thirdPlural: 'surpayent',
  },
  surprendre: {
    first: 'surprends',
    second: 'surprends',
    secondPlural: 'surprenez',
    thirdPlural: 'surprennent',
  },
  suspendre: {
    first: 'suspends',
    second: 'suspends',
    firstPlural: 'suspendons',
  },
  tacheter: {
    first: 'tachette',
    second: 'tachettes',
    third: 'tachette',
    thirdPlural: 'tachettent',
  },
  taire: {
    firstPlural: 'taisons',
    secondPlural: 'taisez',
    thirdPlural: 'taisent',
  },
  tendre: {
    first: 'tends',
    second: 'tends',
    firstPlural: 'tendons',
  },
  transcrire: {
    third: 'transcrit',
    firstPlural: 'transcrivons',
    secondPlural: 'transcrivez',
    thirdPlural: 'transcrivent',
  },
  transparaître: {
    first: 'transparais',
    second: 'transparais',
    firstPlural: 'transparaissons',
  },
  tressaillir: {
    first: 'tressaille',
    second: 'tressailles',
    firstPlural: 'tressaillons',
    secondPlural: 'tressaillez',
    thirdPlural: 'tressaillent',
  },
  trompeter: {
    first: 'trompette',
    second: 'trompettes',
    third: 'trompette',
    thirdPlural: 'trompettent',
  },
  valoir: {
    firstPlural: 'valons',
    secondPlural: 'valez',
    thirdPlural: 'valent',
  },
  vendre: {
    first: 'vends',
    second: 'vends',
    firstPlural: 'vendons',
  },
  vermoudre: {
    first: 'vermouds',
    second: 'vermouds',
    firstPlural: 'vermoulons',
    secondPlural: 'vermoulez',
    thirdPlural: 'vermoulent',
  },
  vêtir: {
    second: 'vêts',
    firstPlural: 'vêtons',
    secondPlural: 'vêtez',
  },
  voleter: {
    first: 'volette',
    second: 'volettes',
    third: 'volette',
    thirdPlural: 'volettent',
  },
  vouloir: {
    first: 'veux',
    second: 'veux',
    third: 'veut',
    firstPlural: 'voulons',
    secondPlural: 'voulez',
    thirdPlural: 'voulent',
  },
  zézayer: {
    first: 'zézaye',
    third: 'zézaye',
    thirdPlural: 'zézayent',
  },
}
