import test from 'tape'
import nlp from './_lib.js'
let here = '[root-match] '
nlp.verbose(false)

test('root-match:', function (t) {
  let arr = [
    ['Nous jetons les chaussures actuelles dans les maisons', '{jeter} les {chaussure} {actuel}'],
    ['dans les maisons actuels', 'dans les {maison} {actuel}'],
    ['infinitésimal', '{infinitésimal}'], //masc
    ['infinitésimale', '{infinitésimal}'], //fem
    ['infinitésimaux', '{infinitésimal}'], //masc plural
    ['infinitésimales', '{infinitésimal}'], //fem plural
    [`Étouffé par sa propre moustache `, '{étouffer}'], //'étouffer'
    [`Quelle est la chose préférée des pirates à tricoter ?`, '{tricoter}'], //tricoter'
    [`Déballé en 1913`, '{déballer}'], //'déballer'
    [`J'ai regardé ce que j'avais tranché`, '{trancher}'], //trancher
    [`Vous devez apprendre à rendre les choses plus rapides`, '{rapide}'], //'rapide'
    [`Les analystes ont attribué le faible`, '{attribuer}'], //attribuer
    [`La production a cessé en octobre.`, '{cesser}'], //'cesser'
    [` Entre-temps, j'ai institué une recherche privée rigoureuse du cadavre`, '{rigoureux}'], //'rigoureux'
    // [`nous avons déballés`, '{déballer}'],//'déballer'
    // [`Appuyez sur le bouton du département correspondant.`, '{correspond}'],//'correspond'
    // [`vous exécutez qu'il active la version.`, '{activer}'],//activer
    // [`Tu sais, je pensais, et si je déballais ici ?`, '{déballer}'],//'déballer'
    // ['en marchant', '{marcher}'],
    // [`Avant, je cherchais à attirer`, '{chercher}'],
    ['les cheminées', '{cheminée}'],
    ['les habitués', '{habitué}'],
    //raison
    [`J'ai dû le faire pour des raisons.`, '{raison}'],
    [`avancé des raisons différentes.`, '{raison}'],
    // [`pour plusieurs raisons.`, '{raison}'],
    // blanc
    [`la boîte blanche`, '{blanc}'],
    [`Une boule blanche géante`, '{blanc}'],
    // libérer
    [`Le Karnataka ne libérera plus`, '{libérer}'],
    [`Il a été libéré par les Royals`, '{libérer}'],
    [`les mascarades était prodigieuse`, '{prodigieux}'],
    [`puissance musculaire prodigieuse`, '{prodigieux}'],
    // [`Tellement stressé que`, '{stresser}'],
    // [`du département correspondant.`, '{correspond}'],
    [`des vins sont bien calculée`, '{calculé}'], //adj
    [`l'ai filtré par mes reins.`, '{rein}'],
    [`les humains naissent avec quatre reins`, '{rein}'],
    // interdire
    // [`Elle interdit les transactions`, '{interdire}'],
    // [`les promotions sont interdites par l'interdiction`, '{interdire}'],
    //endommager
    // [`Il a été endommagé dans deux énormes incendies`, '{endommager}'],

    ['des réductions moins que soudaines et importantes', '{soudain}'], //adj
    // ['chefs d’État ont été assassinés entre 1881 et 1914', '{assassiner}'], //verb
    // ['ils sont critiqués ici ', '{critiquer}'], //verb

    // ['je m\'endorme ', '{endormir}'], //subjunctif
    // ['Milly sanglotait tout son cœur ', '{sangloter}'], //imparfait

    // [`géante est réveillée `, '{réveiller}'],
    [`Ces capacités sont précieuses `, '{précieux}'],
    // ['Graham, interdit de condamner', '{interdire}'],
    ['Leur acquisition serait aussi avantageuse ', '{avantageux}'],
    ['de camionnage ennuyeuse ', '{ennuyeux}'],
    ["vos collègues s'endorment ", '{endormir}'],
    ["Je ne m'endormirai pas ", '{endormir}'],
    ["un lit pour m'endormir ", '{endormir}'],
    ['un jeune homme courageux ', '{courageux}'],
    ['Monana a été très courageuse ', '{courageux}'],
    ['cette confiserie moelleuse ', '{moelleux}'],
    ['la princesse était douce ', '{doux}'],
    ['la scène serait trop douloureuse ', '{douloureux}'],
    ['sont bien trop honteuses ', '{honteux}'],
    ['Ces capacités sont précieuses ', '{précieux}'],
    ['était tellement délicieuse ', '{délicieux}'],

    // [`les appareils ménagers`, '{ménage}'],
    // [`des tâches ménagères`, '{ménage}'],
    [`ce ne sont que quelques formes`, '{forme}'],
    [`l'expérience en tant qu'étudiant enseignant`, '{étudiant}'],
    [`des pensées sombres `, '{pensée}'],
    [`Identifiez vos pensées négatives`, '{pensée}'],
    [`il avait lu mes pensées `, '{pensée}'],
    [`Attirez l'animal `, '{attirer}'],
    // [`des coûts « démontre que le gouvernement exploite »`, '{démontrer}'],
    [`Respirez normalement.`, '{respirer}'],
    [` qu'on respire l'air .`, '{respirer}'],
    [`vous exécutez qu'il active la version`, '{exécuter}'],

    // `bouillonnant` //{bouillir} //present parti
    // [`géante est réveillée `, '{réveiller}'],
    // `que l'Iraq a dissimulées` //{dissimuler} //past participle
    // `Malédiction évitée` {éviter}
    // 'des chiens qui aboient'// {aboyer}

    // ===verbs===
    [`Avant de m'endormir la nuit`, `{endormir}`],
    [`les violettes ne rôtissent pas`, `{rôtir}`],
    [`Détendez-vous et respirez profondément`, `{détendre}`],
    [`laissez-les se détendre.`, `{détendre}`],
    [`vous détendre un peu`, `{détendre}`],
    // [`gémissant et grimaçant de douleur`, `{gémir}`], //present participle
    // [`gémisse-t-elle`, `{gémir}`], //subjunctive
    // [`m'empêchait de lancer`, `{empêcher}`], //imparfait
    // [`Ils dérivaient devant une brise`, `{dériver}`], //imparfait
    // --passive--
    // [`3 brutes coordonnées`, `{coordonner}`],
    [`La saveur été complètement dominée`, `{dominer}`],
    [`Les personnel sont résumés`, `{résumer}`], //passive
    [`les doses sont résumées`, `{résumer}`], //passive
    // [`Cela ne l'a pas empêchée de le poursuivre.`, `{empêcher}`], //passive
    [`et a été incinérée`, `{incinérer}`],
    // [`Les victimes de Doda incinérées `, `{incinérer}`], //adjective

    // ===adjectives===
    [`et boissons fraîches`, `{frais}`],
    [`la bolognaise qui en est ressortie fraîche`, `{frais}`],
    [`C'est une danse vigoureuse`, `{vigoureux}`],
    [`Une poignée de main assez raide`, `{raide}`],
    [`Elle est très affirmée`, `{affirmé}`],
    [`mon amie était occupée`, `{occupé}`],
    [`les plaignants n'étaient pas mûres`, `{mûr}`],

    // ===nouns===
    // [`ses propres règles`, `{règle}`]

    ['Il mange une pomme.', '{manger}'],
    ['Nous avons visité le musée.', '{visiter}'],
    ['Elle danse dans la salle.', '{danser}'],
    ['Tu écris une lettre.', '{écrire}'],
    ['Les oiseaux chantent tôt le matin.', '{chanter}'],
    ["J'ai couru dans le parc.", '{courir}'],
    ['Elles parlent de leurs vacances.', '{parler}'],
    ['Il jouera au tennis demain.', '{jouer}'],
    ['Nous aimons voyager en été.', '{aimer}'],
    ['Il a plu toute la journée.', '{pleuvoir}'],
    ['Elle regarde la télévision.', '{regarder}'],
    ['Tu finis ton devoir.', '{finir}'],
    ['Ils attendent le bus.', '{attendre}'],
    ['Nous avons bu du café.', '{boire}'],
    ['Elle rêve de grandes aventures.', '{rêver}'],
    ['Je travaille chaque jour.', '{travailler}'],
    ['Ils étudient la littérature.', '{étudier}'],
    ['Tu dessines très bien.', '{dessiner}'],
    ['Elle vend sa voiture.', '{vendre}'],
    ['Nous sommes allés à la plage.', '{aller}'],
    ['Le chat dort sur le canapé.', '{dormir}'],
    ['Il répond à la question.', '{répondre}'],
    ['Ils écoutent de la musique.', '{écouter}'],
    ["J'ai lu ce livre.", '{lire}'],
    ['Elle prépare le dîner.', '{préparer}'],
    ['Nous vivons en France.', '{vivre}'],
    ['Il pense à son enfance.', '{penser}'],
    ['Vous choisissez le rouge.', '{choisir}'],
    ['Ils marchent dans la rue.', '{marcher}'],
    ['Elle porte une belle robe.', '{porter}'],
    ["J'ai appris le français à l'école.", '{apprendre}'],
    ['Tu achètes un billet.', '{acheter}'],
    ['Ils habitent près de la gare.', '{habiter}'],
    ["Elle jouit d'une bonne santé.", '{jouir}'],
    ['Nous découvrons un nouveau monde.', '{découvrir}'],
    ['Il perd souvent ses clés.', '{perdre}'],
    ['Ils chantent sous la pluie.', '{chanter}'],
    ['Je crains les serpents.', '{craindre}'],
    ['Elle se brosse les dents.', '{brosser}'],
    ['Nous construisons une maison.', '{construire}'],
    ['Il vole dans le ciel.', '{voler}'],
    ['Vous buvez du vin.', '{boire}'],
    ['Elles cherchent leur chien.', '{chercher}'],
    ['Je commence ma journée tôt.', '{commencer}'],
    ['Elle sourit toujours.', '{sourire}'],
    ['Nous comprenons la leçon.', '{comprendre}'],
    ['Il saute par-dessus la clôture.', '{sauter}'],
    ['Elles courent vite.', '{courir}'],
    ['Vous nagez dans la piscine.', '{nager}'],
    ['Je montre la direction.', '{montrer}'],

    ['Il peint une toile magnifique.', '{peindre}'],
    ['Nous voyageons à travers le monde.', '{voyager}'],
    ['Elle sourit quand elle est heureuse.', '{sourire}'],
    ['Vous partez en vacances.', '{partir}'],
    ['Ils aiment la musique classique.', '{aimer}'],
    ['Je reviens à la maison à six heures.', '{revenir}'],
    ['Tu grimpes la montagne.', '{grimper}'],
    ['Elle lit un roman captivant.', '{lire}'],
    ['Nous cuisinons un repas délicieux.', '{cuisiner}'],
    ['Il joue de la guitare tous les soirs.', '{jouer}'],
    ['Elles se rencontrent au café.', '{rencontrer}'],
    ['Vous vivez une expérience incroyable.', '{vivre}'],
    ['Je nage tous les week-ends.', '{nager}'],
    ['Elle enseigne les mathématiques.', '{enseigner}'],
    ['Ils écoutent la radio en conduisant.', '{écouter}'],
    ['Nous prenons le petit déjeuner.', '{prendre}'],
    ['Elle se promène dans le parc.', '{promener}'],
    ['Vous fermez la porte.', '{fermer}'],
    ['Ils croient en leurs rêves.', '{croire}'],
    ['Je cherche mes lunettes.', '{chercher}'],
    ['Elle se souvient de son enfance.', '{souvenir}'],
    ['Tu réussis ton examen.', '{réussir}'],
    ['Nous planifions notre voyage.', '{planifier}'],
    ['Il grandit trop vite.', '{grandir}'],
    ['Elles se lavent les mains.', '{laver}'],
    ['Je me rappelle cette chanson.', '{rappeler}'],
    ['Il se repose après le travail.', '{reposer}'],
    ['Tu chantes magnifiquement.', '{chanter}'],
    ['Elle plante des fleurs dans le jardin.', '{planter}'],
    ['Nous commandons de la nourriture.', '{commander}'],
    ['Elle reçoit une lettre.', '{recevoir}'],
    ['Je me brosse les cheveux.', '{brosser}'],
    ["Ils s'entraînent pour le marathon.", '{entraîner}'],
    ['Nous apprécions le bon vin.', '{apprécier}'],
    ['Il se réveille tôt le matin.', '{réveiller}'],
    ['Elle se maquille avant de sortir.', '{maquiller}'],
    ['Nous décidons de partir.', '{décider}'],
    ['Elle jette le papier.', '{jeter}'],
    ["Ils s'inquiètent pour leur ami.", '{inquiéter}'],
    ['Je me souviens de cette journée.', '{souvenir}'],
    ['Vous mesurez la pièce.', '{mesurer}'],
    ['Elle rit de la blague.', '{rire}'],
    ['Nous admirons le paysage.', '{admirer}'],
    ['Il compte les étoiles.', '{compter}'],
    ['Ils désirent une nouvelle voiture.', '{désirer}'],
    ["Je rêve d'une vie meilleure.", '{rêver}'],
    ['Elle appelle son frère.', '{appeler}'],
    ['Vous aimez la pizza.', '{aimer}'],
    ['Ils espèrent une promotion.', '{espérer}'],
    ['Je me prépare pour le travail.', '{préparer}'],

    ['Elle désigne le coupable.', '{désigner}'],
    ["Nous jouissons d'une belle vue.", '{jouir}'],
    ['Il invente une nouvelle machine.', '{inventer}'],
    ['Elles adoptent un chaton.', '{adopter}'],
    ['Je répare mon vélo.', '{réparer}'],
    ['Il examine les documents.', '{examiner}'],
    ["Tu te dépêches pour l'école.", '{dépêcher}'],
    ['Nous cultivons des légumes.', '{cultiver}'],
    ['Elle construit une maquette.', '{construire}'],
    ['Je te félicite pour ton succès.', '{féliciter}'],
    ['Il développe une application.', '{développer}'],
    ["Elles fêtent l'anniversaire de Sophie.", '{fêter}'],
    ['Nous consommons trop de sucre.', '{consommer}'],
    ['Je décore ma chambre.', '{décorer}'],
    ['Elles discutent de leurs projets.', '{discuter}'],
    ['Il pratique le yoga chaque matin.', '{pratiquer}'],
    ['Je conserve les photos.', '{conserver}'],
    ['Tu collabores avec ton collègue.', '{collaborer}'],
    ['Il se lamente sur son sort.', '{lamenter}'],
    ['Nous approuvons la décision.', '{approuver}'],
    ['Elle recommande ce restaurant.', '{recommander}'],
    ['Il tente une nouvelle expérience.', '{tenter}'],
    ['Nous prononçons difficilement ce mot.', '{prononcer}'],
    ['Elle envisage de déménager.', '{envisager}'],
    ['Je propose une solution.', '{proposer}'],
    ['Ils respectent la nature.', '{respecter}'],
    ['Elle se relaxe au spa.', '{relaxer}'],
    ['Nous installons le logiciel.', '{installer}'],
    ['Il photographie le paysage.', '{photographier}'],
    ['Elles recueillent des informations.', '{recueillir}'],
    ['Je possède quelques livres anciens.', '{posséder}'],
    ['Elle médite en silence.', '{méditer}'],
    ["Nous investissons dans l'immobilier.", '{investir}'],
    ['Il modifie le document.', '{modifier}'],
    ['Elles diffusent une nouvelle émission.', '{diffuser}'],
    ['Je navigue sur le lac.', '{naviguer}'],
    ['Il se nourrit de légumes.', '{nourrir}'],
    ['Elles illuminent la pièce.', '{illuminer}'],
    ['Nous renforçons les fondations.', '{renforcer}'],
    ['Il analyse les données.', '{analyser}'],
    ['Je boycotte cette marque.', '{boycotter}'],
    ['Elles bronzent à la plage.', '{bronzer}'],
    ['Il évalue les risques.', '{évaluer}'],
    ['Je fusionne les fichiers.', '{fusionner}'],
    ['Elles se hydratent régulièrement.', '{hydrater}'],
    ['Nous initions un nouveau projet.', '{initier}'],
    ["Il licencie l'employé.", '{licencier}'],
    ['Elles masquent leurs sentiments.', '{masquer}'],
    ['Nous optimisons les performances.', '{optimiser}'],
    ['Elle priorise ses tâches.', '{prioriser}'],
    ['Il qualifie le match de décevant.', '{qualifier}'],
    ['Elles se rassemblent devant le cinéma.', '{rassembler}'],
    ['Je sollicite votre aide.', '{solliciter}'],
    ['Elle se réjouit de cette nouvelle.', '{réjouir}'],
    ['Il valide le ticket.', '{valider}'],
    ['Nous interagissons avec les clients.', '{interagir}'],
    ['Elle se situe près du parc.', '{situer}'],
    ['Ils circulent en ville.', '{circuler}'],
    ['Nous embauchons un nouvel employé.', '{embaucher}'],
    ['Elle se fonde sur des faits.', '{fonder}'],
    ['Ils déterminent la cause.', '{déterminer}'],
    ['Elle échange des idées.', '{échanger}'],
    ['Nous exploitons une mine.', '{exploiter}'],
    ["Il neutralise l'ennemi.", '{neutraliser}'],
    ['Je précise ma pensée.', '{préciser}'],
    ['Elles restaurent le tableau.', '{restaurer}'],
    ['Il mobilise ses ressources.', '{mobiliser}'],
    ['Je te surprends en train de rire.', '{surprendre}'],
    ['Elles visualisent le succès.', '{visualiser}'],
    ['Il harmonise les couleurs.', '{harmoniser}'],
    ['Elles intègrent le groupe.', '{intégrer}'],
    ['Je te complimente sur ta tenue.', '{complimenter}'],

    ['Elle supervise les stagiaires.', '{superviser}'],
    ['Nous augmentons la production.', '{augmenter}'],
    ["Il minimise l'impact.", '{minimiser}'],
    ['Elles embellissent la salle.', '{embellir}'],
    ['Je réduis mes dépenses.', '{réduire}'],
    ['Il se familiarise avec les lieux.', '{familiariser}'],
    ['Elles précèdent la cérémonie.', '{précéder}'],
    ['Nous maximisons les profits.', '{maximiser}'],
    ["Elle stimule l'économie.", '{stimuler}'],
    ['Je simplifie la procédure.', '{simplifier}'],
    ['Ils confirment leur présence.', '{confirmer}'],
    ["Elle se venge de l'injustice.", '{venger}'],
    ['Nous réfléchissons à une solution.', '{réfléchir}'],
    ['Elles sympathisent rapidement.', '{sympathiser}'],
    ['Il approfondit ses connaissances.', '{approfondir}'],
    ['Nous éliminons les obstacles.', '{éliminer}'],
    ['Elle organise une surprise.', '{organiser}'],
    ['Il renouvelle son passeport.', '{renouveler}'],
    ["Elles s'opposent à la décision.", '{opposer}'],
    ['Je compatis à sa douleur.', '{compatir}'],
    ['Ils se comportent bien.', '{comporter}'],
    ['Elle compare les prix.', '{comparer}'],
    ['Nous intégrons les feedbacks.', '{intégrer}'],
    ['Il élargit son réseau.', '{élargir}'],
    ['Elles se dévouent à la cause.', '{dévouer}'],
    ['Je manifeste mon mécontentement.', '{manifester}'],
    ['Il se réfère au manuel.', '{référer}'],
    ["Elles formalisent l'accord.", '{formaliser}'],
    ['Nous diversifions nos investissements.', '{diversifier}'],
    ["Il s'adapte à la situation.", '{adapter}'],
    ['Elles établissent un record.', '{établir}'],
    ["Je neutralise l'acide.", '{neutraliser}'],
    ['Il consulte le médecin.', '{consulter}'],
    ['Elles se débarrassent des déchets.', '{débarrasser}'],
    ['Nous éclairons la pièce.', '{éclairer}'],
    ['Il associe le vin et le fromage.', '{associer}'],
    ['Elles déplorent la situation.', '{déplorer}'],
    ['Je priorise mes objectifs.', '{prioriser}'],
    ['Il caractérise le phénomène.', '{caractériser}'],
    ['Elles optimisent le processus.', '{optimiser}'],
    ['Nous célébrons la victoire.', '{célébrer}'],
    ['Elle traite les données.', '{traiter}'],
    ['Il motive ses choix.', '{motiver}'],
    ['Elles dominent le paysage.', '{dominer}'],
    ["Je qualifie cela d'injuste.", '{qualifier}'],
    ['Il justifie son retard.', '{justifier}'],
    ['Elles clarifient la situation.', '{clarifier}'],
    ['Je consolide mes connaissances.', '{consolider}'],
    ['Il exploite une opportunité.', '{exploiter}'],
    ['Elles inspectent le bâtiment.', '{inspecter}'],

    ["Elle s'épanouit dans son travail.", '{épanouir}'],
    ['Nous plongeons dans la piscine.', '{plonger}'],
    ['Il fréquente le musée.', '{fréquenter}'],
    ['Elles appliquent la règle.', '{appliquer}'],
    ['Je fusionne les deux groupes.', '{fusionner}'],
    ['Il se réveille tôt.', '{réveiller}'],
    ['Elles empruntent un chemin.', '{emprunter}'],
    ['Nous illustrons le concept.', '{illustrer}'],
    ['Elle signe le contrat.', '{signer}'],
    ['Je mélange les ingrédients.', '{mélanger}'],
    ['Ils sélectionnent les candidats.', '{sélectionner}'],
    ['Elles persistent dans leurs efforts.', '{persister}'],
    ['Nous manifestons pour la paix.', '{manifester}'],
    ['Il évoque de vieux souvenirs.', '{évoquer}'],
    ['Elles resplendissent de bonheur.', '{resplendir}'],
    ['Je valorise ses contributions.', '{valoriser}'],
    ['Ils restituent les objets.', '{restituer}'],
    ['Elle tranche la pomme.', '{trancher}'],
    ['Nous désinfectons la surface.', '{désinfecter}'],
    ['Il ancre le bateau.', '{ancrer}'],
    ['Elles déduisent la réponse.', '{déduire}'],
    ['Je corrige les erreurs.', '{corriger}'],
    ["Ils s'acquittent de leurs dettes.", '{acquitter}'],
    ['Elle instaure une nouvelle règle.', '{instaurer}'],
    ['Nous délimiterons la zone.', '{délimiter}'],
    ['Il préserve sa santé.', '{préserver}'],
    ["Elles s'émerveillent devant le paysage.", '{émerveiller}'],
    ['Je délivre le message.', '{délivrer}'],
    ['Ils raffinent le pétrole.', '{raffiner}'],
    ['Elles inaugurent le bâtiment.', '{inaugurer}'],
    ['Nous éroderons la roche.', '{éroder}'],
    ['Il incarne la justice.', '{incarner}'],
    ['Elles se fondent dans la foule.', '{fondre}'],
    ['Je dépeins la scène.', '{dépeindre}'],
    ["Ils s'emparent de la ville.", '{emparer}'],
    ["Elle s'immerge dans la culture.", '{immerger}'],
    ['Nous oscillerons entre les options.', '{osciller}'],
    ['Il contemple la mer.', '{contempler}'],
    ['Elles se dispersent rapidement.', '{disperser}'],
    ['Je compromets mes chances.', '{compromettre}'],
    ['Ils sollicitent une augmentation.', '{solliciter}'],
    ['Elle renforce ses compétences.', '{renforcer}'],
    ['Nous émanons de la confiance.', '{émaner}'],
    ['Il infuse le thé.', '{infuser}'],
    ['Elles se délectent de la musique.', '{délecter}'],
    ['Je rehausse la saveur.', '{rehausser}'],
    ['Ils effacent les marques.', '{effacer}'],
    ['Elle implémente le code.', '{implémenter}'],
    ['Nous illuminons la nuit.', '{illuminer}'],
    ['Il coordonne les équipes.', '{coordonner}'],
    ['Elles revendiquent leurs droits.', '{revendiquer}'],
    ['Je bannis cette habitude.', '{bannir}'],
    ['Ils relancent le projet.', '{relancer}'],
    ["Elle s'abstient de commenter.", '{abstenir}'],
    ['Nous instiguons un changement.', '{instiguer}'],
    ['Il dissipe les doutes.', '{dissiper}'],
    ["Elles magnifient l'art.", '{magnifier}'],
    ["Je pérennise l'entreprise.", '{pérenniser}'],
    ['Ils revitalisent le quartier.', '{revitaliser}'],
    ["Elle s'incruste à la fête.", '{incruster}'],
    ['Nous équilibrerons le budget.', '{équilibrer}'],
    ['Il contrevient à la loi.', '{contrevenir}'],
    ['Elles exaltent la nature.', '{exalter}'],
    ["Je postule pour l'emploi.", '{postuler}'],
    ['Ils scellent le pacte.', '{sceller}'],
    ["Elle s'immisce dans la conversation.", '{immiscer}'],
    ['Nous compensons la perte.', '{compenser}'],
    ['Il recouvre le sofa.', '{recouvrir}'],
    ["Elles s'apprêtent à partir.", '{apprêter}'],
    ['Je morcelle le pain.', '{morceler}'],
    ['Ils côtoient les stars.', '{côtoyer}'],
    ['Elle postpose le rendez-vous.', '{postposer}'],
    ["Nous oblitérons l'ancien système.", '{oblitérer}']
  ]
  arr.forEach(function (a) {
    let [str, match] = a
    let doc = nlp(str) //.compute('root')
    let tags = doc.json()[0].terms.map((term) => term.tags[0])
    let msg = `'${(str + "' ").padEnd(20, ' ')}  - '${tags.join(', ')}'`
    t.equal(doc.has(match), true, here + msg)
  })
  t.end()
})
