module.exports = [
  'ap. j.-c.',
  'ap. jc',
  'apr. j.-c.',
  'après jc',
  'après jésus-christ',
  'av. j.-c.',
  'à cheval',
  'guère',
  'à peine',
  'difficilement',
  'pratiquement',
  'basiquement',
  'essentiellement',
  'foncièrement',
  'fondamentalement',
  'sommairement',
  'critiquement',
  'négativement',
  'aimablement',
  'gentiment',
  'cependant',
  'mais',
  'que',
  'seulement',
  'simplement',
  'uniquement',
  'strictement',
  'automatiquement',
  'horriblement',
  'terriblement',
  'abondamment',
  'beaucoup',
  'immensément',
  'largement',
  'vastement',
  'extrêmement',
  'grossièrement',
  'scandaleusement',
  'vulgairement',
  'généralement',
  'la plupart du temps',
  'sensiblement',
  'significativement',
  'appréciablement',
  'notablement',
  'approximativement',
  'environ',
  'peu ou prou',
  'à peu près',
  'absolument',
  'vraiment',
  'en partie',
  'partiellement',
  'bien',
  'complètement',
  'directement',
  'en même temps',
  'entièrement',
  'intégralement',
  'parfaitement',
  'pleinement',
  'totalement',
  'tout',
  'tout à fait',
  'exclusivement',
  'seul',
  's&apos;il te plaît',
  's&apos;il vous plaît',
  'imparfaitement',
  'en entier',
  'alors',
  'bon',
  'faiblement',
  'mal',
  'facilement',
  'mieux',
  'également',
  'richement',
  'avantageusement',
  'favorablement',
  'heureusement',
  'cruellement',
  'durement',
  'tant',
  'amplement',
  'considérablement',
  'copieusement',
  'sérieusement',
  'comme ça',
  'est bon',
  'proprement',
  'gravement',
  'sévèrement',
  'malicieusement',
  'encore',
  'voire',
  'même',
  'assez',
  'relativement',
  'suffisamment',
  'purement',
  'toujours',
  'consécutivement',
  'successivement',
  'constamment',
  'continuellement',
  'jamais',
  'de temps en temps',
  'occasionnellement',
  'parfois',
  'quelquefois',
  'des fois',
  'tantôt',
  'aussi',
  'comme',
  'lorsque',
  'pendant que',
  'puisque',
  'quand',
  'jadis',
  'paradoxalement',
  'arbitrairement',
  'bourgeoisement',
  'classiquement',
  'conventionnellement',
  'ne',
  'niet',
  'non',
  'pas',
  'que dalle',
  'non plus',
  'ou',
  'soit',
  'n&apos;importe où',
  'partout',
  'e part',
  'quelque part',
  'd&apos;une façon ou d&apos;une autre',
  'de toute façon',
  'en tout cas',
  'quand même',
  'nonobstant',
  'néanmoins',
  'pourtant',
  'toutefois',
  'jusqu&apos;',
  'jusqu&apos;alors',
  'jusqu&apos;ici',
  'jusqu&apos;à maintenant',
  'jusqu&apos;à présent',
  'lestement',
  'légèrement',
  'à la légère',
  'outre',
  'de plus',
  'de surcroît',
  'en outre',
  'plus loin',
  'davantage',
  'loin',
  'en vain',
  'inutilement',
  'vainement',
  'ni plus ni moins',
  'plus',
  'déjà',
  'très',
  'fabuleusement',
  'fantastiquement',
  'formidablement',
  'prodigieusement',
  'droit',
  'nettement',
  'vivement',
  'dorénavant',
  'désormais',
  'justement',
  'aussitôt',
  'fissa',
  'illico',
  'immédiatement',
  'instantanément',
  'sur-le-champ',
  'tout de suite',
  'plutôt',
  'un peu',
  'bientôt',
  'incessamment',
  'prochainement',
  'passionnément',
  'fréquemment',
  'souvent',
  'rarement',
  'curieusement',
  'modérément',
  'raisonnablement',
  'équitablement',
  'abusivement',
  'démesurément',
  'excessivement',
  'immodérément',
  'outrageusement',
  'en soi',
  'intrinsèquement',
  'carrément',
  'certainement',
  'certes',
  'décidément',
  'définitivement',
  'emphatiquement',
  'fortement',
  'pertinemment',
  'réellement',
  'sincèrement',
  'véritablement',
  'bien sûr',
  'en effet',
  'bel et bien',
  'effectivement',
  'bien entendu',
  'naturellement',
  'clairement',
  'apparemment',
  'de toute évidence',
  'manifestement',
  'visiblement',
  'évidemment',
  'de nouveau',
  'derechef',
  'à nouveau',
  'accidentellement',
  'fortuitement',
  'inopinément',
  'comme un cheveu sur la soupe',
  'particulièrement',
  'spécifiquement',
  'communément',
  'en général',
  'par bonheur',
  'volontiers',
  'malheureusement',
  'tristement',
  'fâcheusement',
  'hélas',
  'malencontreusement',
  'ainsi',
  'donc',
  'par conséquent',
  'où',
  'ici',
  'tête-à-tête',
  'au-delà',
  'hors',
  'autrement',
  'accessoirement',
  'complémentairement',
  'en addition',
  'en prime',
  'secondairement',
  'supplémentairement',
  'fort',
  'haut',
  'exceptionnellement',
  'extraordinairement',
  'beaucoup trop',
  'bien trop',
  'de trop',
  'trop',
  'itou',
  'notamment',
  'pareillement',
  'fin',
  'finalement',
  'tôt ou tard',
  'à l&apos;heure',
  'éventuellement',
  'avec le temps',
  'en fin de compte',
  'enfin',
  'à la fin',
  'actuellement',
  'aujourd&apos;hui',
  'de nos jours',
  'de notre temps',
  'maintenant',
  'présentement',
  'rasibus',
  'gaiement',
  'gaillardement',
  'gaiment',
  'jovialement',
  'joyeusement',
  'tout droit',
  'dûment',
  'infatigablement',
  'acrimonieusement',
  'aigrement',
  'amèrement',
  'âprement',
  'ok',
  'rapidement',
  'ouvertement',
  'presque',
  'quasiment',
  'probablement',
  'vraisemblablement',
  'pyramidalement',
  'ensuite',
  'momentanément',
  'provisoirement',
  'aisément',
  'manuellement',
  'à la main',
  'affreusement',
  'abominablement',
  'acceptablement',
  'comme ci comme ça',
  'couci-couça',
  'inacceptablement',
  'insupportablement',
  'intolérablement',
  'injurieusement',
  'atrocement',
  'effroyablement',
  'hideusement',
  'redoutablement',
  'épouvantablement',
  'grandement',
  'puissamment',
  'du tout',
  'en aucun cas',
  'exhaustivement',
  'à droite',
  'debout',
  'indirectement',
  'de plus en plus',
  'progressivement',
  'efficacement',
  'antérieurement',
  'auparavant',
  'autrefois',
  'précédemment',
  'avant',
  'devant',
  'tôt',
  'après',
  'derrière',
  'en',
  'par la suite',
  'postérieurement',
  'puis',
  'subséquemment',
  'ultérieurement',
  'abruptement',
  'brusquement',
  'brutalement',
  'précipitamment',
  'soudain',
  'soudainement',
  'subitement',
  'tout d&apos;un coup',
  'délibérément',
  'expressément',
  'exprès',
  'intentionnellement',
  'sciemment',
  'volontairement',
  'à dessein',
  'involontairement',
  'au lieu de',
  'sans parler de',
  'anatomiquement',
  'chronologiquement',
  'convenablement',
  'dument',
  'ponctuellement',
  'précisément',
  'mathématiquement',
  'entre-temps',
  'entretemps',
  'là',
  'pendant ce temps',
  'large',
  'principalement',
  'longuement',
  'depuis',
  'hier',
  'durablement',
  'distraitement',
  'en avant',
  'en face',
  'préalablement',
  'le long de',
  'parallèlement',
  'autour',
  'vis-à-vis',
  'à voix haute',
  'à haute voix',
  'calmement',
  'tranquillement',
  'craintivement',
  'analogiquement',
  'aléatoirement',
  'au hasard',
  'manière aléatoire',
  'rond',
  'désespérément',
  'urgemment',
  'près',
  'quasi',
  'surtout',
  'il y a',
  'voici',
  'arrière',
  'sens devant derrière',
  'en long et en large',
  'effrontément',
  'insolemment',
  'brillamment',
  'catalytiquement',
  'commercialement',
  'cher',
  'chèrement',
  'affectueusement',
  'amoureusement',
  'inversement',
  'franchement',
  'assurément',
  'indubitablement',
  'statistiquement',
  'activement',
  'passivement',
  'au-dessus',
  'dessous',
  'par-dessus',
  'dédaigneusement',
  'contractuellement',
  'cocassement',
  'comiquement',
  'drôlement',
  'journellement',
  'quotidiennement',
  'chaque semaine',
  'annuellement',
  'fallacieusement',
  'illusoirement',
  'trompeusement',
  'là-bas',
  'dichotomiquement',
  'vertigineusement',
  'doublement',
  'empiriquement',
  'spécialement',
  'ailleurs',
  'expérimentalement',
  'diligemment',
  'vite',
  'catégoriquement',
  'inconditionnellement',
  'ad vitam aeternam',
  'éternellement',
  'infiniment',
  'à l&apos;infini',
  'continument',
  'passagèrement',
  'temporairement',
  'impromptu',
  'spontanément',
  'hautement',
  'admirablement',
  'supérieurement',
  'marginalement',
  'géométriquement',
  'dangereusement',
  'périlleusement',
  'vigoureusement',
  'énergiquement',
  'contrecœur',
  'dur',
  'laborieusement',
  'malaisément',
  'péniblement',
  'fermement',
  'arrache-pied',
  'étroitement',
  'brièvement',
  'compendieusement',
  'courtement',
  'succinctement',
  'lamentablement',
  'deçà',
  'en bas',
  'bas',
  'en haut',
  'à la maison',
  'à l&apos;aise',
  'moins',
  'autant',
  'petit',
  'tard',
  'tardivement',
  'positivement',
  'délicatement',
  'délicieusement',
  'exquisément',
  'd&apos;abord',
  'en premier lieu',
  'premièrement',
  'primo',
  'deuxièmement',
  'secondement',
  'tertio',
  'troisièmement',
  'initialement',
  'originairement',
  'à première vue',
  'et ainsi de suite',
  'et cetera',
  'etc',
  'dedans',
  'au minimum',
  'au moins',
  'promptement',
  'unanimement',
  'banalement',
  'couramment',
  'd&apos;habitude',
  'd&apos;ordinaire',
  'habituellement',
  'normalement',
  'ordinairement',
  'usuellement',
  'traditionnellement',
  'remarquablement',
  'dernièrement',
  'récemment',
  'irrégulièrement',
  'doucement',
  'graduellement',
  'pas à pas',
  'peu à peu',
  'là-dessus',
  'ores',
  'par ici',
  'çà',
  'ci-dedans',
  'par-là',
  'historiquement',
  'pacifiquement',
  'paisiblement',
  'scientifiquement',
  'dehors',
  'militairement',
  'littéralement',
  'texto',
  'virtuellement',
  'silencieusement',
  'internationalement',
  'mondialement',
  'universellement',
  'forcément',
  'inévitablement',
  'nécessairement',
  'obligatoirement',
  'fraichement',
  'fraîchement',
  'nouvel',
  'nouvellement',
  'différemment',
  'organiquement',
  'machinalement',
  'mécaniquement',
  'formellement',
  'officiellement',
  'douloureusement',
  'centralement',
  'charnellement',
  'physiquement',
  'peu',
  'politiquement',
  'symboliquement',
  'ensemble',
  'conjointement',
  'collectivement',
  'concurremment',
  'de concert',
  'lors',
  'quel que soit',
  'anciennement',
  'd&apos;un autre côté',
  'en revanche',
  'par contre',
  'd&apos;un côté',
  'simultanément',
  'systématiquement',
  'tellement',
  'astronomiquement',
  'constitutionnellement',
  'anticonstitutionnellement',
  'démocratiquement',
  'économiquement',
  'électroniquement',
  'ethniquement',
  'génétiquement',
  'graphiquement',
  'industriellement',
  'irrévocablement',
  'légalement',
  'professoralement',
  'royalement',
  'scolastiquement',
  'socialement',
  'techniquement',
  'thématiquement',
  'curativement',
  'typiquement',
  'verbalement',
  'oralement',
  'globalement',
  'planétairement',
  'électriquement',
  'chimiquement',
  'pluriraciale',
  'professionnellement',
  'spatialement',
  'sémantiquement',
  'linguistiquement',
  'financièrement',
  'matériellement',
  'pécuniairement',
  'algébriquement',
  'en personne',
  'individuellement',
  'personnellement',
  'catastrophiquement',
  'mystiquement',
  'biologiquement',
  'moralement',
  'métaphysiquement',
  'acoustiquement',
  'allégoriquement',
  'figurativement',
  'localement',
  'régionalement',
  'nationalement',
  'culturellement',
  'syntactiquement',
  'syntaxiquement',
  'sexuellement',
  'lexicalement',
  'chirurgicalement',
  'alternativement',
  'transversalement',
  'respectivement',
  'semblablement',
  'similairement',
  'peut-être',
  'sans doute',
  'intensivement',
  'défectueusement',
  'inaliénablement',
  'artificiellement',
  'chroniquement',
  'immuablement',
  'perpétuellement',
  'épisodiquement',
  'fiévreusement',
  'fébrilement',
  'humainement',
  'inconcevablement',
  'incroyablement',
  'avec insistance',
  'superficiellement',
  'symptomatiquement',
  'vilainement',
  'pour sûr',
  'surement',
  'sûrement',
  'étonnamment',
  'technologiquement',
  'passablement',
  'insuffisamment',
  'après quoi',
  'sic',
  'main dans la main',
  'facile',
  'molle',
  'en fait',
  'à vrai dire',
  'par contumace',
  'tout compte fait',
  'manière de parler',
  'coûte que coûte',
  'à tout prix',
  'à la fois',
  'attentivement',
  'soigneusement',
  'prétendument',
  'censément',
  'soi-disant',
  'illégalement',
  'licitement',
  'originalement',
  'primitivement',
  'confortablement',
  'par cœur',
  'au fait',
  'soit dit en passant',
  'à propos',
  'incomplètement',
  'exactement',
  'juste',
  'montre en main',
  'par exemple',
  'à partir de zéro',
  'amicalement',
  'cordialement',
  'comparativement',
  'proportionnellement',
  'majoritairement',
  'primordialement',
  'lentement',
  'au grand jour',
  'publiquement',
  'à huis clos',
  'secrètement',
  'cul par-dessus tête',
  'au cas où',
  'flegmatiquement',
  'froidement',
  'grièvement',
  'en temps voulu',
  'en règle',
  'longtemps',
  'juste à temps',
  'extemporanément',
  'confidentiellement',
  'à quatre pattes',
  'hypothétiquement',
  'théoriquement',
  'contrairement',
  'au contraire',
  'en cours de route',
  'en route',
  'à la lettre',
  'bec et ongles',
  'audacieusement',
  'courageusement',
  'profondément',
  'impatiemment',
  'patiemment',
  'méthodiquement',
  'aveuglément',
  'hautainement',
  'orgueilleusement',
  'sauvagement',
  'imbécilement',
  'stupidement',
  'symétriquement',
  'asymétriquement',
  'créativement',
  'lourdement',
  'régulièrement',
  'médiocrement',
  'vice versa',
  'jour après jour',
  'radicalement',
  'consciencieusement',
  'religieusement',
  'scrupuleusement',
  'autrement dit',
  'dès que',
  'outre-mer',
  'sainement',
  'amusamment',
  'hilarement',
  'excellemment',
  'merveilleusement',
  'splendidement',
  'épatamment',
  'irréprochablement',
  'benoitement',
  'benoîtement',
  'vrai',
  'de préférence',
  'préférentiellement',
  'rationnellement',
  'intrépidement',
  'compétente',
  'habilement',
  'peureusement',
  'solennellement',
  'maussadement',
  'sereinement',
  'agréablement',
  'conformément',
  'adroitement',
  'astucieusement',
  'ingénieusement',
  'intelligemment',
  'subtilement',
  'centre-ville',
  'c&apos;est-à-dire',
  'est-à-dire',
  'nommément',
  'populairement',
  'ardemment',
  'enthousiastement',
  'intellectuellement',
  'exagérément',
  'fièrement',
  'malhabilement',
  'trivialement',
  'intensément',
  'voir',
  'sympathiquement',
  'méticuleusement',
  'gauchement',
  'maladroitement',
  'victorieusement',
  'assidûment',
  'idéalement',
  'erronément',
  'enfantinement',
  'puérilement',
  'improprement',
  'adéquatement',
  'colossalement',
  'énormément',
  'généreusement',
  'libéralement',
  'librement',
  'commodément',
  'opportunément',
  'inopportunément',
  'concrètement',
  'abstraitement',
  'convulsivement',
  'obstinément',
  'bravement',
  'hardiment',
  'résolument',
  'avidement',
  'supposément',
  'sagement',
  'déraisonnablement',
  'imprudemment',
  'bêtement',
  'intelligiblement',
  'confusément',
  'alphabétiquement',
  'aristocratiquement',
  'noblement',
  'diplomatiquement',
  'indéfiniment',
  'correctement',
  'fidèlement',
  'injustement',
  'charitablement',
  'paresseusement',
  'sombrement',
  'hâtivement',
  'à la hâte',
  'à la va-vite',
  'distinctement',
  'isolément',
  'séparément',
  'ostensiblement',
  'fatalement',
  'infailliblement',
  'inéluctablement',
  'imaginativement',
  'chaleureusement',
  'immodestement',
  'impudiquement',
  'satiriquement',
  'routinièrement',
  'spirituellement',
  'indistinctement',
  'inébranlablement',
  'périodiquement',
  'sporadiquement',
  'furieusement',
  'superbement',
  'productivement',
  'dextrement',
  'surabondamment',
  'bizarrement',
  'singulièrement',
  'ennuyeusement',
  'judicieusement',
  'souverainement',
  'suprêmement',
  'impitoyablement',
  'inexorablement',
  'courtoisement',
  'incorrectement',
  'malhonnêtement',
  'adorablement',
  'joliment',
  'désagréablement',
  'affablement',
  'amènement',
  'gracieusement',
  'explicitement',
  'univoquement',
  'fiablement',
  'violemment',
  'férocement',
  'rigoureusement',
  'anormalement',
  'anachroniquement',
  'plaisamment',
  'mentalement',
  'timidement',
  'bruyamment',
  'intérieurement',
  'défavorablement',
  'avec force',
  'solidement',
  'laconiquement',
  'complaisamment',
  'obligeamment',
  'bénévolement',
  'instinctivement',
  'géographiquement',
  'lugubrement',
  'vaguement',
  'pompeusement',
  'opiniâtrement',
  'dramatiquement',
  'tragiquement',
  'sinistrement',
  'nerveusement',
  'à bon escient',
  'inadvertamment',
  'à juste titre',
  'irrésistiblement',
  'chacun',
  'chacune',
  'analytiquement',
  'anarchiquement',
  'impérativement',
  'spéculativement',
  'consciemment',
  'structurellement',
  'du jour au lendemain',
  'invraisemblablement',
  'farouchement',
  'quantitativement',
  'obscurément',
  'décemment',
  'abjectement',
  'caractéristiquement',
  'artistement',
  'artistiquement',
  'extérieurement',
  'à bord de',
  'uniformément',
  'côte à côte',
  'entre',
  'ad hoc',
  'françois coli',
  'a priori',
  'juridiquement',
  'à plein temps',
  'à temps partiel',
  'bilatéralement',
  'unilatéralement',
  'sens antihoraire',
  'contre-intuitivement',
  'sens horaire',
  'bihebdomadairement',
  'mensuellement',
  'mi-chemin',
  'hiérarchiquement',
  'ibidem',
  'in situ',
  'ter',
  'mot pour mot',
  'mot à mot',
  'gratuitement',
  'au milieu',
  'heures supplémentaires',
  'esthétiquement',
  'approbativement',
  'anonymement',
  'adagio',
  'administrativement',
  'arrogamment',
  'de haut',
  'honteusement',
  'adjectivement',
  'angéliquement',
  'architecturalement',
  'éloquemment',
  'inaudiblement',
  'bestialement',
  'authentiquement',
  'alias',
  'ingratement',
  'arithmétiquement',
  'finement',
  'malignement',
  'obliquement',
  'sur l&apos;arrière',
  'vers l&apos;arrière',
  'à califourchon',
  'avarement',
  'gloutonnement',
  'pieds nus',
  'bénignement',
  'à brûle-pourpoint',
  'prudemment',
  'précautionneusement',
  'sans cesse',
  'interminablement',
  'chastement',
  'chevaleresquement',
  'climatiquement',
  'familièrement',
  'incompatiblement',
  'compulsivement',
  'informatiquement',
  'conceptuellement',
  'bref',
  'concisément',
  'en bref',
  'cyniquement',
  'séquentiellement',
  'bougonnement',
  'grincheusement',
  'artificieusement',
  'conséquemment',
  'mystérieusement',
  'énigmatiquement',
  'court',
  'humidement',
  'densément',
  'possiblement',
  'impossiblement',
  'potentiellement',
  'absurdement',
  'contagieusement',
  'coquettement',
  'élégamment',
  'envieusement',
  'jalousement',
  'ignoblement',
  'dinguement',
  'follement',
  'à la folie',
  'profond',
  'odieusement',
  'diaboliquement',
  'humblement',
  'modestement',
  'indignement',
  'néfastement',
  'sournoisement',
  'diamétralement',
  'didactiquement',
  'pédagogiquement',
  'désastreusement',
  'ignominieusement',
  'honnêtement',
  'vénalement',
  'hypocritement',
  'impartialement',
  'loyalement',
  'déloyalement',
  'impassiblement',
  'respectueusement',
  'irrespectueusement',
  'inconfortablement',
  'rêveusement',
  'ecclésiastiquement',
  'écologiquement',
  'extatiquement',
  'étrangement',
  'égoïstement',
  'inélégamment',
  'éminemment',
  'environnementalement',
  'éruditement',
  'euphémiquement',
  'évasivement',
  'inégalement',
  'impardonnablement',
  'irrémissiblement',
  'exorbitamment',
  'usurairement',
  'couteusement',
  'coûteusement',
  'exponentiellement',
  'à la volée',
  'perfidement',
  'traîtreusement',
  'faussement',
  'bigrement',
  'fanatiquement',
  'incivilement',
  'cinquièmement',
  'quinto',
  'figurément',
  'indolemment',
  'flexiblement',
  'inflexiblement',
  'piano',
  'quarto',
  'quatrièmement',
  'frauduleusement',
  'frugalement',
  'sobrement',
  'frivolement',
  'géologiquement',
  'allègrement',
  'voracement',
  'divinement',
  'magnifiquement',
  'grotesquement',
  'monstrueusement',
  'parcimonieusement',
  'harmonieusement',
  'haineusement',
  'la tête la première',
  'inconsciemment',
  'inconsidérément',
  'témérairement',
  'étourdiment',
  'chaud',
  'lourd',
  'ci-après',
  'héroïquement',
  'luxueusement',
  'somptueusement',
  'horizontalement',
  'verticalement',
  'hygiéniquement',
  'identiquement',
  'doctrinalement',
  'idéologiquement',
  'idiomatiquement',
  'lisiblement',
  'illisiblement',
  'légitimement',
  'réglementairement',
  'logiquement',
  'imperceptiblement',
  'insensiblement',
  'impérieusement',
  'impertinemment',
  'impétueusement',
  'espièglement',
  'imprécisément',
  'pile',
  'précises',
  'tapantes',
  'incognito',
  'incomparablement',
  'indélébilement',
  'indescriptiblement',
  'ineffablement',
  'discrètement',
  'indûment',
  'innocemment',
  'insidieusement',
  'interchangeablement',
  'transitivement',
  'intransitivement',
  'invinciblement',
  'invisiblement',
  'ironiquement',
  'irréparablement',
  'irrévérencieusement',
  'languissamment',
  'langoureusement',
  'lascivement',
  'voluptueusement',
  'latéralement',
  'ridiculement',
  'risiblement',
  'lyriquement',
  'majestueusement',
  'massivement',
  'doucereusement',
  'maximalement',
  'minimement',
  'chichement',
  'maigrement',
  'mesquinement',
  'économement',
  'inoubliablement',
  'sans pitité',
  'bordéliquement',
  'minutieusement',
  'miraculeusement',
  'misérablement',
  'monotonement',
  'morphologiquement',
  'prosaïquement',
  'mutuellement',
  'réciproquement',
  'naïvement',
  'plus jamais',
  'proche',
  'de nuit',
  'notoirement',
  'alimentairement',
  'numériquement',
  'nord-nord-est',
  'nord-nord-ouest',
  'objectivement',
  'obséquieusement',
  'servilement',
  'opérationnellement',
  'optimalement',
  'optimistiquement',
  'optionnellement',
  'fastueusement',
  'bonnement',
  'tolérablement',
  'entre parenthèses',
  'autour de',
  'pitoyablement',
  'pédantement',
  'péjorativement',
  'pharmacologiquement',
  'pittoresquement',
  'placidement',
  'de but en blanc',
  'reconnaissablement',
  'sentencieusement',
  'pneumatiquement',
  'précairement',
  'prématurément',
  'présomptueusement',
  'bégueulement',
  'psychologiquement',
  'chétivement',
  'pénalement',
  'qualitativement',
  'suspectement',
  'radieusement',
  'itérativement',
  'honorablement',
  'révéremment',
  'rhétoriquement',
  'robustement',
  'sonorement',
  'inhumainement',
  'sadiquement',
  'sarcastiquement',
  'sardoniquement',
  'cagotement',
  'sensuellement',
  'inséparablement',
  'septimo',
  'septièmement',
  'soyeusement',
  'pusillanimement',
  'sexto',
  'sixièmement',
  'calomnieusement',
  'sociologiquement',
  'solitairement',
  'sordidement',
  'sud-sud-est',
  'sud-sud-ouest',
  'stoïquement',
  'stratégiquement',
  'superlativement',
  'furtivement',
  'subrepticement',
  'implicitement',
  'tacitement',
  'tendrement',
  'decimo',
  'coléreusement',
  'pétulamment',
  'théologiquement',
  'après-demain',
  'demain',
  'transcendantalement',
  'éphémèrement',
  'typographiquement',
  'inaltérablement',
  'petitement',
  'indéniablement',
  'en dessous',
  'indument',
  'grammaticalement',
  'avec fruit',
  'utilement',
  'vaillamment',
  'véhémentement',
  'verbeusement',
  'vivacement',
  'de tout cœur',
  'd&apos;où',
  'desquelles',
  'desquels',
  'dont',
  'duquel',
  'd’où',
  'là où',
  'soucieusement',
  'ouais',
  'oui',
  'conjugalement',
  'malproprement',
  'en commun',
  'de seconde main',
  'homogènement',
  'mortellement',
  'avant-hier',
  'polygonalement',
  'cursivement',
  'érotiquement',
  'irrémédiablement',
  'radioactivement',
  'récurremment'
];
